### ISSUE TITLE
图表：按周时间段选择

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#103]
从开始的时间分周，周一到周日为一整周;)
![image](https://cloud.githubusercontent.com/assets/12438962/7854379/90f04408-054b-11e5-99b2-bb3bf4b96335.png)
如：
![image](https://cloud.githubusercontent.com/assets/12438962/7854408/cdd8d7d6-054b-11e5-89ec-7525c7c27326.png)

**Comment by xiaoweiqb** [comment]
好的，尽快了哈！

**Comment by xiaoweiqb** [comment]
@Gongyufei 
@zerocoolys 
bug已解决

**Comment by zerocoolys** [comment]
![image](https://cloud.githubusercontent.com/assets/2757581/7875926/db469886-05f5-11e5-8e92-ad425906495d.png)

已经确认!
