### ISSUE TITLE
数据不一致：搜索推广

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#107]
上面小图表中没有相关指标数据，需与下面表格中的数据保持一致
（截图上传不了，QQ补图）

**Comment by xiaoweiqb** [comment]
![qq 20150525175242](https://cloud.githubusercontent.com/assets/11550475/7901659/d183fbd2-07c5-11e5-9079-542ec9f30161.png)

这个是这个意思吗？上下一致？
