### ISSUE TITLE
数据&ui：百度推广-推广方式

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#108]
1，数据缺失
![image](https://cloud.githubusercontent.com/assets/12438962/7858566/b0b0926e-056b-11e5-98b1-fe40c2af55ac.png)

![image](https://cloud.githubusercontent.com/assets/12438962/7858596/0767a912-056c-11e5-9df6-9e44b3e4a73f.png)

2，高级筛选 的 地域过滤 功能没有，如下图修改：
![image](https://cloud.githubusercontent.com/assets/12438962/7858555/99dc730a-056b-11e5-874e-5f802f7ed8db.png)

**Comment by Gongyufei** [comment]
@guochunyan

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/7905590/a24ce922-084d-11e5-9365-8b56fc46211f.png)
地狱过滤功能存在

**Comment by Gongyufei** [comment]
增加地域
![image](https://cloud.githubusercontent.com/assets/12438962/7952361/f4e6e936-09e6-11e5-83d8-e83dbb981d51.png)
