### ISSUE TITLE
日历问题：慧眼所有模块

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#110]
所选时间段日历展现问题；日期区间
![image](https://cloud.githubusercontent.com/assets/12438962/7874295/4c233d9a-05e0-11e5-9948-af1dcd328d7f.png)
如下图：
![image](https://cloud.githubusercontent.com/assets/12438962/7874320/8ceb41b0-05e0-11e5-83b9-804ffae316d5.png)

**Comment by guochunyan** [comment]
#102

**Comment by guochunyan** [comment]
两个issue 相同#102
