### ISSUE TITLE
ui&表格：趋向分析

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#113]
1，没有日期标识；请在图表上方增加日期颜色标识
2，图表下面的文字需修改，勾选。
![image](https://cloud.githubusercontent.com/assets/12438962/7874720/3f3edfa2-05e6-11e5-8ed6-c4b09b189483.png)

例：
![image](https://cloud.githubusercontent.com/assets/12438962/7874783/f01b0896-05e6-11e5-9602-10894ea2b6d6.png)

**Comment by Gongyufei** [comment]
@zerocoolys 
@xiaoweiqb

**Comment by Gongyufei** [comment]
@guochunyan 是今日统计和昨日统计 两块，忽略实时访客

**Comment by fangzhenping** [comment]
@guochunyan @zymin 下面是跟雨菲碰过的效果图
![image](https://cloud.githubusercontent.com/assets/11955235/7875623/17a5080c-05f2-11e5-97f5-5825e815ec7a.png)

**Comment by zerocoolys** [comment]
已经确认.
