### ISSUE TITLE
图表：设备环境 指标展现错误

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#114]
选择的指标和展现出来的不一致
![image](https://cloud.githubusercontent.com/assets/12438962/7874927/0972f388-05e9-11e5-8f51-20fb85230adc.png)

![image](https://cloud.githubusercontent.com/assets/12438962/7874932/281db66a-05e9-11e5-8c6e-fd12cb51f213.png)

**Comment by Gongyufei** [comment]
@zerocoolys

**Comment by zerocoolys** [comment]
@Gongyufei 转化的指标暂时还没有办法计算, 别着急, 只是因为现在后台的配置还没完成. 
你选择的转化,看到的是pv,这是临时显示来用得.

@xiaoweiqb

**Comment by xiaoweiqb** [comment]
@Gongyufei 
转化指标，和贡献量个指标还没计算，所以用的是pv的数据，我现在把这个显示为主页的指标

**Comment by xiaoweiqb** [comment]
点错
