### ISSUE TITLE
【追UI】按来源类型 按来源网站 单行高度均衡统一下

### ISSUE THREAD

**Issue by fangzhenping** [zerocoolys/sshuiyan#116]
单行高度均衡统一下，修改如下，
![image](https://cloud.githubusercontent.com/assets/11955235/7875830/e9d318d0-05f4-11e5-82e6-b7f7fcb5d5d2.png)

所有此行的高度都是统一26px

**Comment by zerocoolys** [comment]
![image](https://cloud.githubusercontent.com/assets/2757581/7877711/1f83cd8c-0611-11e5-887e-6daae3873c78.png)

@liwenkaifzk  请确认一下是否解决.

**Comment by fangzhenping** [comment]
已确认，谢谢各位
