### ISSUE TITLE
ui：来源分析-搜索词-按搜索引擎

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#122]
缺少自定义指标
![image](https://cloud.githubusercontent.com/assets/12438962/7876480/e9fcfe2a-05fe-11e5-9914-0a983bba3e47.png)

**Comment by zerocoolys** [comment]
![image](https://cloud.githubusercontent.com/assets/2757581/7901611/39791c7a-07c3-11e5-8b82-43c232fbc490.png)

@guochunyan

**Comment by guochunyan** [comment]
@ zerocoolys @Gongyufei 跟雨非确认过
