### ISSUE TITLE
[图表] 数据列显示不一致

### ISSUE THREAD

**Issue by zerocoolys** [zerocoolys/sshuiyan#123]
1. ![image](https://cloud.githubusercontent.com/assets/2757581/7877320/00261a80-060c-11e5-8b78-9adce9340303.png)
2. ![image](https://cloud.githubusercontent.com/assets/2757581/7877324/204b38a4-060c-11e5-84ee-9f28f6cd3f53.png)

**Comment by zerocoolys** [comment]
点击 "确定" 查询的结果, 和选择 "客户端属性" 效果不一致

![image](https://cloud.githubusercontent.com/assets/2757581/7877345/6fd03ca8-060c-11e5-9921-c01dbfea88a5.png)

**Comment by SubDong** [comment]
2015年5月29日之后版本可查看
