### ISSUE TITLE
慧眼中所有涉及到默认和自定义数据指标 问题

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#13]
上、下数据指标 应和默认及自定义数据指标一致
![image](https://cloud.githubusercontent.com/assets/12438962/7646079/d10a1998-faf0-11e4-85a1-69b89e0ae4d4.png)

**Comment by zerocoolys** [comment]
这一块我们是以哪一个为准? 
中间系统默认指标为准吗?

**Comment by Gongyufei** [comment]
是的，上下指标是一致的。以中间的默认指标一致；如自定义自选指标，上下指标是一起变化的，是应该一致的。

**Comment by SubDong** [comment]
现在系统中的 上下指标都是保持一直的

**Comment by SubDong** [comment]
2015年5月15号， 问题已解决

**Comment by Gongyufei** [comment]
没有保持一致：）

**Comment by SubDong** [comment]
非非姐 你的意思是  上面和下面保持一直的意思 就  顺序  字样  都必须一直吗？

**Comment by Gongyufei** [comment]
首先，上面的和下面的数据指标字样应该是一致的（包括默认和自定义）；顺序也要一致。

**Comment by zerocoolys** [comment]
@SubDong 是什么原因没有一致?

**Comment by Gongyufei** [comment]
怎么都没有指标自定义了？默认也看不见了？
