### ISSUE TITLE
表格数据不统一：受访页面

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#135]
![image](https://cloud.githubusercontent.com/assets/12438962/7904899/deda9cd0-083f-11e5-85d1-8e6a68b33e1f.png)

**Comment by Gongyufei** [comment]
@zerocoolys

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/7905540/caf02282-084c-11e5-8117-7662f11ad2a1.png)
