### ISSUE TITLE
数据问题：新老访客

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#137]
客户端属性改变时，数据有问题，没有任何变化
![image](https://cloud.githubusercontent.com/assets/12438962/7905823/28bd2b4e-0852-11e5-8eec-dc5be3172421.png)

**Comment by Gongyufei** [comment]
@zerocoolys @SubDong

**Comment by sgWeiMinSheng** [comment]
@Gongyufei 根据百度统计，新老访客页面只是显示统计时间内新老访客的数据。不和客户端属性有关联
