### ISSUE TITLE
搜索推广-单元、关键词、创意、搜索词、推广url中的问题

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#14]
系统默认指标没有标识
下面数据指标没有展现？
![image](https://cloud.githubusercontent.com/assets/12438962/7646013/01a26110-faf0-11e4-8a58-99ebb634ae12.png)
![image](https://cloud.githubusercontent.com/assets/12438962/7646211/f1325dd2-faf2-11e4-8c9b-18a5685bef5f.png)

例：
![Uploading image.png…]()

**Comment by zerocoolys** [comment]
离线宝, 移动搜索, 转化指标暂时不支持.

**Comment by Gongyufei** [comment]
只有 昨日 指标数据吗？
应该还有今日的指标数据吧

**Comment by Gongyufei** [comment]
![image](https://cloud.githubusercontent.com/assets/12438962/7650283/6aa16a26-fb27-11e4-93fa-a87c564833d3.png)

**Comment by zerocoolys** [comment]
这个截图是什么意思?

**Comment by Gongyufei** [comment]
咱们的慧眼只有一个 昨日  ，没有 今天 数据吗？

**Comment by xiaoweiqb** [comment]
我们拉取的是昨日的数据

**Comment by zerocoolys** [comment]
@Gongyufei 推广这块拉取今天的数据 会消耗非常多得API 配额,所以暂时不支持今天的.

**Comment by Gongyufei** [comment]
好的

**Comment by Gongyufei** [comment]
创意、搜索词、推广url中 系统默认指标没有标记；上下指标不一致

**Comment by zerocoolys** [comment]
@Gongyufei 这个issue先关闭了.如果有涉及到得issue, 请重新创建一个issue
