### ISSUE TITLE
【追UI】下拉菜单宽度自适应

### ISSUE THREAD

**Issue by fangzhenping** [zerocoolys/sshuiyan#145]
自适应不需要换行
![image](https://cloud.githubusercontent.com/assets/11955235/7906446/e4c23144-085d-11e5-8393-00c1a0ede847.png)

**Comment by guochunyan** [comment]
![qq 20150601192054](https://cloud.githubusercontent.com/assets/11551612/7911707/3f5190d4-0893-11e5-8a67-f0e581524b87.png)

**Comment by zerocoolys** [comment]
@guochunyan 省略号那里看不到了

**Comment by fangzhenping** [comment]
@zerocoolys 点击会出现全部内容

**Comment by guochunyan** [comment]
@zerocoolys 之前是太长了的话 会折行，现在是底部内容大于上面的就会隐藏长的部分，点击上去会显示全部内容。。
