### ISSUE TITLE
日历问题

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#150]
问题：
1，与其他时间段对比 ，选中时间段后；如再选择其它对比时间段，需要刷新才能选择
（截图后补）

**Comment by xiaoweiqb** [comment]
这个是什么？

**Comment by Gongyufei** [comment]
问题：
选择了一个时间段，如再选一单日日期，点击确认后么有任何改变；还需要刷新此页。
![image](https://cloud.githubusercontent.com/assets/12438962/7932121/76c8ef48-0948-11e5-99d0-3cfc2483e9d4.png)
