### ISSUE TITLE
图表柱状图：推广概况

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#153]
柱状图出现3组；日期时间段展现有问题
![image](https://cloud.githubusercontent.com/assets/12438962/7931514/ca9c5a42-0943-11e5-89aa-b78c475a4c72.png)

**Comment by xiaoweiqb** [comment]
这个是样子有问题还是说什么有问题？

**Comment by Gongyufei** [comment]
选择对比，最多是两组的对比，但出现3组柱状图；
