### ISSUE TITLE
UI：慧眼中所有无数据的指标数据表现形式

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#158]
![image](https://cloud.githubusercontent.com/assets/12438962/7932980/70b3845a-094e-11e5-9788-abb92f0ef38f.png)
没有数据的指标，表现形式如下：
![image](https://cloud.githubusercontent.com/assets/12438962/7933002/989b8d3c-094e-11e5-8df7-614de9e4c800.png)
辛苦修改

**Comment by SubDong** [comment]
与 宫雨菲沟通后 这里保持了原来的0显示方式
