### ISSUE TITLE
默认指标不一致：搜索推广

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#160]
![image](https://cloud.githubusercontent.com/assets/12438962/7933270/a6622e56-0950-11e5-93b3-565c9c63efd8.png)
![image](https://cloud.githubusercontent.com/assets/12438962/7933281/b1eb61b6-0950-11e5-9951-ab134777dbbb.png)

**Comment by SubDong** [comment]
@Gongyufei  这里是点击系统默认指标后  会自动选中指标   但是 需要点击确定后上面和表格的数据才会变化为选中的指标    这个方式 是和百度一直的

**Comment by Gongyufei** [comment]
系统默认指标，是不需要再点击确定的，既然是系统默认好的指标，那么指标应该是一致的呀
