### ISSUE TITLE
表格和小图表数据不一致：设备环境

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#169]
![image](https://cloud.githubusercontent.com/assets/12438962/7976383/dabebafe-0aac-11e5-9eae-4c94a24d149f.png)
![image](https://cloud.githubusercontent.com/assets/12438962/7976386/e4baf2ac-0aac-11e5-816c-87a24a764c37.png)

**Comment by zerocoolys** [comment]
@sgWeiMinSheng 确认没有解决

**Comment by sgWeiMinSheng** [comment]
![123123](https://cloud.githubusercontent.com/assets/10495048/8029413/50d041aa-0def-11e5-9ff2-7f0b2adcb67b.png)
![12312312312312312](https://cloud.githubusercontent.com/assets/10495048/8029414/50fd86b0-0def-11e5-8a1b-2cf80d39763d.png)
