### ISSUE TITLE
表格UI需求：实时访客

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#170]
辛苦春燕，设计图少了些指标，辛苦帮修改
![image](https://cloud.githubusercontent.com/assets/12438962/7978324/ce5c8ee8-0ac6-11e5-8ad5-7e4779842e68.png)
请按以下内容修改：
![image](https://cloud.githubusercontent.com/assets/12438962/7978415/a0a511f4-0ac7-11e5-8b91-7225d530a35c.png)
辛苦啦：）

**Comment by Gongyufei** [comment]
@SubDong

**Comment by guochunyan** [comment]
@xiaoweiqb
