### ISSUE TITLE
[数据] 小数点

### ISSUE THREAD

**Issue by zerocoolys** [zerocoolys/sshuiyan#174]
![image](https://cloud.githubusercontent.com/assets/2757581/8023932/f5651d7c-0d53-11e5-9056-83b22f5664c1.png)

@sgWeiMinSheng

**Comment by sgWeiMinSheng** [comment]
![qq 20150608111700](https://cloud.githubusercontent.com/assets/10495048/8027729/fe11a6da-0dcf-11e5-9d4d-2af5e551c0ec.png)
