### ISSUE TITLE
UI：搜索推广

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#185]
数据指标值为0时，图表和表示表现形式保持一致
![image](https://cloud.githubusercontent.com/assets/12438962/8031076/46a404b4-0dfe-11e5-80bf-519961df04cf.png)
![image](https://cloud.githubusercontent.com/assets/12438962/8031082/518f458c-0dfe-11e5-8ff6-eb25774b7053.png)

**Comment by guochunyan** [comment]
@SubDong @sgWeiMinSheng
