### ISSUE TITLE
图表数据不一致：网站概览

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#186]
同一数据指标&同一日期，数据不一样？
![image](https://cloud.githubusercontent.com/assets/12438962/8031821/f8fd4f76-0e03-11e5-9a4d-4af5b6b873f9.png)
![image](https://cloud.githubusercontent.com/assets/12438962/8031825/05cd093a-0e04-11e5-898f-cf837d329810.png)

**Comment by xiaoweiqb** [comment]
![qq 20150611152010](https://cloud.githubusercontent.com/assets/11550475/8101837/7d93a44c-104d-11e5-9405-99bd4982003e.png)
上面是今日的
下面近7天的
![qq 20150611152234](https://cloud.githubusercontent.com/assets/11550475/8101840/89637324-104d-11e5-8be0-f4c61546af9b.png)
