### ISSUE TITLE
开发任务

### ISSUE THREAD

**Issue by TomDing729** [zerocoolys/sshuiyan#187]
网站统计设置-子目录管理模块

**Comment by TomDing729** [comment]
补充
@zerocoolys

**Comment by zerocoolys** [comment]
@TomDing729 assignee  指派给你自己
然后 @xiaoweiqb , 另外请补充预计完成时间.

**Comment by TomDing729** [comment]
明白了， 预计完成时间2015-6-9。

**Comment by TomDing729** [comment]
该需求和编号#190的需求描述一致，所以关闭。
