### ISSUE TITLE
（指标）访客分析-地域分布：

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#19]
按地级市 不能出现国家
建议可细分（按国家、按省or按地级市）
按地域

![image](https://cloud.githubusercontent.com/assets/12438962/7646897/8f807bf4-fafd-11e4-924b-5d16cf2e6465.png)

**Comment by zerocoolys** [comment]
@Gongyufei 当前的IP库暂时只支持国内的数据
建议到二期更新到世界范围
