### ISSUE TITLE
管理设置-事件转换目标

### ISSUE THREAD

**Issue by iammybest** [zerocoolys/sshuiyan#191]
@zerocoolys @xiaoweiqb @TomDing729  预计6.10完成，包含Redis写入功能

**Comment by iammybest** [comment]
@guochunyan 该功能下的 预览添加 无弹出预览页面

**Comment by zerocoolys** [comment]
@Gongyufei @guochunyan 此功能需要抓取目标页面的 dom元素, 请评估一下难度和时间.

**Comment by TomDing729** [comment]
@iammybest @zerocoolys @xiaoweiqb   这个模块的手动配置已经完成。
