### ISSUE TITLE
页面分析-页面标题

### ISSUE THREAD

**Issue by iammybest** [zerocoolys/sshuiyan#192]
@zerocoolys @xiaoweiqb @TomDing729 需要讲解下热力图业务

**Comment by zerocoolys** [comment]
@iammybest 附上预计解决时间

**Comment by zerocoolys** [comment]
@iammybest @icepros @guochunyan @SubDong @xiaoweiqb 
流程:

```
1 用户在后台配置需要采集鼠标数据的页面url, 比如 www.best-ad.cn/login.html
2 前端追踪js会实时生成当前页面是否启动鼠标数据的功能.
3 如果启用, 追踪js会收集用户在网页上的鼠标点击事件,并把正确的坐标数据传入后端.
4 在热力图页面上, 用户选择在步骤1中配置好的url, 后台会根据时间(今天,昨天,最近7天等),
   然后合并所有该时间段的点击数据,一并推送到热力图中.   
```

[热力图效果](http://image.baidu.com/i?ct=201326592&cl=2&lm=-1&nc=1&ie=utf-8&tn=baiduimage&ipn=r&ps=1&pv=&fm=rs1&word=%E7%BD%91%E9%A1%B5%E7%83%AD%E5%8A%9B%E5%9B%BE&ofr=%E7%83%AD%E5%8A%9B%E5%9B%BE)
