### ISSUE TITLE
UI 数据指标修改-推广概况

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#196]
删掉红框内的指标
增加抵达率、浏览量（PV)
![image](https://cloud.githubusercontent.com/assets/12438962/8051265/f9b80f24-0eac-11e5-9736-890639cea0f5.png)
示例：
（QQ附截图）

**Comment by Gongyufei** [comment]
示例
![image](https://cloud.githubusercontent.com/assets/12438962/8051381/39ff32e6-0eae-11e5-8069-d0e2a1f9f0eb.png)

**Comment by guochunyan** [comment]
![qq 20150609145350](https://cloud.githubusercontent.com/assets/11551612/8052168/493d52ca-0eb7-11e5-8079-20636aa6ed7f.png)
