### ISSUE TITLE
UI&图表：推广概况

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#197]
增加指标：平均访问页数
![image](https://cloud.githubusercontent.com/assets/12438962/8051429/c4529122-0eae-11e5-91c8-1e738ce09241.png)

**Comment by Gongyufei** [comment]
@xiaoweiqb

**Comment by guochunyan** [comment]
![qq 20150609145501](https://cloud.githubusercontent.com/assets/11551612/8052192/7c2980fa-0eb7-11e5-9bf0-dccf709d9d8f.png)
