### ISSUE TITLE
【追UI】网站信息UI

### ISSUE THREAD

**Issue by fangzhenping** [zerocoolys/sshuiyan#198]
![image](https://cloud.githubusercontent.com/assets/11955235/8051788/55d10e36-0eb3-11e5-8fff-7491b9de1b2d.png)
鼠标滑过背景色蓝色统一色值：#01aeef，并下拉框太靠上遮挡了 稍稍网址信息，辛苦按如下截图修改
![image](https://cloud.githubusercontent.com/assets/11955235/8052208/ac22174a-0eb7-11e5-8533-8beb3f1c6484.png)

![image](https://cloud.githubusercontent.com/assets/11955235/8051796/62d3fef4-0eb3-11e5-9d52-11d3e5ba7938.png)
选择框内的字体应该是蓝色 #01aeef 加粗    ，并去掉背景色

**Comment by fangzhenping** [comment]
效果应该是这样![image](https://cloud.githubusercontent.com/assets/11955235/8052269/38050a60-0eb8-11e5-9bf5-4fc79b637093.png)

**Comment by fangzhenping** [comment]
@zymin 麻烦把背景色去掉
![image](https://cloud.githubusercontent.com/assets/11955235/8056119/aec54b82-0ed7-11e5-9075-5bf3d6f51190.png)

**Comment by zymin** [comment]
已解决

**Comment by fangzhenping** [comment]
@zymin 
![image](https://cloud.githubusercontent.com/assets/11955235/8152496/42afa136-1350-11e5-88ee-d3818a55f91f.png)麻烦请将那个位置的背景色去掉，谢谢

**Comment by fangzhenping** [comment]
@zymin 我现在还看不到效果，等我看到了 再确认
