### ISSUE TITLE
(表格）百度推广-推广概况：

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#20]
数据指标没有标识（应该有个提示，哪个颜色是哪个指标）
而且，如果同时在选择两个指标的对比，还会增加对比指标数据（也需要区分开）
![image](https://cloud.githubusercontent.com/assets/12438962/7650381/3c637b76-fb28-11e4-8ea5-8abbf1b7da1e.png)

**Comment by zerocoolys** [comment]
颜色上需要区分, 比如橙色和蓝色指标对应的

**Comment by xiaoweiqb** [comment]
好

**Comment by Gongyufei** [comment]
这块儿请按照百度的来做吧
![image](https://cloud.githubusercontent.com/assets/12438962/7721025/043b4b48-ff06-11e4-939b-e1cb07fb65b7.png)

**Comment by Gongyufei** [comment]
现在的问题：
对比数据指标对比时间段标识
而且对比数据指标累积。
![image](https://cloud.githubusercontent.com/assets/12438962/7721201/ecb71432-ff07-11e4-8e6f-026f8a4658c9.png)

需求：
折线图
对比时间段做出颜色标识，折线对应

**Comment by zerocoolys** [comment]
@Gongyufei 因为现在百思的数据报告是每天拉取一次,时间上没办法做到按小时来.
在二期可以考虑增加这样的功能.一期目前还没办法实现.
