### ISSUE TITLE
图表数据不一致：网站概览-设备环境

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#205]
1，选择今天，日期不对；
![image](https://cloud.githubusercontent.com/assets/12438962/8056646/d663afbc-0edc-11e5-9de6-f59ed5ee1147.png)
2，ip数对不上，访客数也对不上
![image](https://cloud.githubusercontent.com/assets/12438962/8056678/0fce8830-0edd-11e5-9722-d7b9a3aa940c.png)
![image](https://cloud.githubusercontent.com/assets/12438962/8056711/5495841e-0edd-11e5-9b95-34bfb1936f11.png)
![image](https://cloud.githubusercontent.com/assets/12438962/8056715/5c58ac08-0edd-11e5-810c-6d008546f797.png)

**Comment by xiaoweiqb** [comment]
这个是原始数据不对造成的
