### ISSUE TITLE
表格数据联动&不一致 访客地图

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#207]
1，当下面的表格指标条件改变时，上面小图表中的数据也要随之变化，上下数据保持一致：
![image](https://cloud.githubusercontent.com/assets/12438962/8074260/3fb5ad6e-0f62-11e5-9fc1-7bf2f260aa8a.png)
![image](https://cloud.githubusercontent.com/assets/12438962/8074267/6a7f7ee4-0f62-11e5-89b3-1c3f096b7142.png)
2，访客数不准确（新老访客相加不等于上面的访客数）：
![image](https://cloud.githubusercontent.com/assets/12438962/8074285/91c6dc04-0f62-11e5-85b5-7dc4ed1e0d61.png)
![image](https://cloud.githubusercontent.com/assets/12438962/8074289/9c9a5728-0f62-11e5-8764-a304a219b9cd.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/8079054/c5fcbc0a-0f94-11e5-8746-8c3439158646.png)
