### ISSUE TITLE
图表数据 ：新老访客

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#209]
这是什么东东;)

![image](https://cloud.githubusercontent.com/assets/12438962/8074441/39005fc0-0f65-11e5-9f56-94a4261c11ee.png)

**Comment by sgWeiMinSheng** [comment]
@SubDong 返回数据为aN:aN:aN

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/8077039/bd19ab30-0f84-11e5-82dc-e777c9b4290d.png)
