### ISSUE TITLE
UI&表格数据：新老访客

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#212]
1，点击新、老访客的 查看历史数据，链接进入的历史数据页面，需有[老访客]&[新访客]的提示字样
![image](https://cloud.githubusercontent.com/assets/12438962/8074679/215027c2-0f68-11e5-9199-f10bb7bcc1f1.png)
示例如下
![image](https://cloud.githubusercontent.com/assets/12438962/8074794/26d6f7ce-0f69-11e5-9089-a5ddc37618e5.png)
2，数据不准（老访客截图）
![image](https://cloud.githubusercontent.com/assets/12438962/8074760/d9e8bcf4-0f68-11e5-9ed1-cf7a0adf6857.png)
![image](https://cloud.githubusercontent.com/assets/12438962/8074776/f06bb10c-0f68-11e5-9ff6-16226350cfe4.png)

**Comment by Gongyufei** [comment]
@guochunyan

**Comment by SubDong** [comment]
@Gongyufei  @zerocoolys   新老访客数据显示问题是因为  1、在测试过程中  es数据库这边删除过数据  2、在每天晚上0点的 时间跨度上  同一次访问存在了 2天的数据中
