### ISSUE TITLE
日历：所有慧眼涉及到的日历

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#213]
（之前提的问题还没有解决：）
问题：选择某一个单日日期，需要重复分别点击两个日历表、同一个日期2次，否则就会出现一个时间段。这样太麻烦了。
需求：点击一单日日期，确定后就是选择的日期
![image](https://cloud.githubusercontent.com/assets/12438962/8074915/26a99502-0f6b-11e5-92f4-8fb0cc325084.png)

**Comment by xiaoweiqb** [comment]
？

**Comment by Gongyufei** [comment]
例：
1，
![image](https://cloud.githubusercontent.com/assets/12438962/8076104/2ff6dfec-0f7b-11e5-9aef-6e327aafe63d.png)
2，
![image](https://cloud.githubusercontent.com/assets/12438962/8076126/5f188f96-0f7b-11e5-85ed-52a535c5d016.png)
3，
![image](https://cloud.githubusercontent.com/assets/12438962/8076185/eeb6555c-0f7b-11e5-9a84-00deaa66692f.png)
