### ISSUE TITLE
表格UI&表格数据：来源分析中的所有设计到的对比和当页汇总

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#219]
1，单日日期不需要起始日期表现；
2，当页汇总数据有误，当页汇总ui见示例：
![image](https://cloud.githubusercontent.com/assets/12438962/8098395/188acea2-1022-11e5-856f-3054f7b18642.png)
示例：
![image](https://cloud.githubusercontent.com/assets/12438962/8098425/722c12cc-1022-11e5-9f04-3beff9311ba1.png)

**Comment by Gongyufei** [comment]
@SubDong

**Comment by SubDong** [comment]
#210
