### ISSUE TITLE
（表格）网站概况：指标颜色问题

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#22]
默认状态的指标颜色是一样
![image](https://cloud.githubusercontent.com/assets/12438962/7664364/7b1d19c4-fbb6-11e4-8790-ed3168bd829d.png)

**Comment by Gongyufei** [comment]
所有涉及到表格的模块，都有同样的问题

**Comment by zerocoolys** [comment]
这个是图表的问题,非表格
