### ISSUE TITLE
图表UI&功能：搜索引擎（来源分析中的模块都有同样的问题）

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#220]
1，选择单日日期，图表中的弹窗时间表现形式（2:00-3:00)，只展现一个指标（不要把所有的指标都放在一弹窗内）
2，图表下方有所选搜索引擎的指标数据
![image](https://cloud.githubusercontent.com/assets/12438962/8098659/4e0feb54-1025-11e5-879c-e3164f404585.png)
ui设计图：
![image](https://cloud.githubusercontent.com/assets/12438962/8098674/7fc75038-1025-11e5-9828-60588912434c.png)

**Comment by Gongyufei** [comment]
@xiaoweiqb

**Comment by guochunyan** [comment]
#217

**Comment by zerocoolys** [comment]
上面的ui设计图就是小房房设计好的啊，怎么需要重新设计？@Gongyufei @fangzhenping 第二个需要是重新设计的.

**Comment by guochunyan** [comment]
@zerocoolys s@fangzhenping @Gongyufei 
1、时间段已加上；
2、点击单条显示单条数据，我们所使用的chart不支持，未找到方法更改；
![qq 20150611112642](https://cloud.githubusercontent.com/assets/11551612/8099250/b248fbfe-102c-11e5-9aa2-a894a1d084a1.png)目前我们显示的数据每条是按照颜色标示来的，每个颜色点和数据相对应

**Comment by guochunyan** [comment]
@fangzhenping

**Comment by Gongyufei** [comment]
@zerocoolys @guochunyan 这是小房房的ui设计图
![image](https://cloud.githubusercontent.com/assets/12438962/8101304/4501819e-1048-11e5-9f9c-0524c5e580bc.png)

**Comment by zerocoolys** [comment]
这个是搜索引擎页面？把全部页面给我。@Gongyufei @fangzhenping  

![image](https://cloud.githubusercontent.com/assets/2757581/8102060/b33885f2-104f-11e5-95ca-504ae76eeddf.png)

小房房重新设计了一版

**Comment by Gongyufei** [comment]
那右侧的饼图呢？

**Comment by zerocoolys** [comment]
@Gongyufei 什么意思?

**Comment by guochunyan** [comment]
@Gongyufei @zerocoolys @fangzhenping  这个是房房做的一个跟随弹窗的效果，只是一个示意图
