### ISSUE TITLE
ui需求&历史数据不准确：来源分析的所有模块 （这个问题新老访客已提过，慧眼中涉及到的历史数据）

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#222]
1，选择所查看指标的历史趋势，链接到该指标的历史数据页面，需有 改指标名称的提示：（来源分析中都有涉及到此问题，(全部来源，搜索引擎，搜索词、外部链接）
![image](https://cloud.githubusercontent.com/assets/12438962/8098847/e6b859b6-1027-11e5-9183-cf256bd8b897.png)
以下为链接页面（没有标注指标信息，不知道是哪个指标）
![image](https://cloud.githubusercontent.com/assets/12438962/8098955/fc5894ec-1028-11e5-8605-b5fd85ce3645.png)
示例：
![image](https://cloud.githubusercontent.com/assets/12438962/8098995/a7a3ac7e-1029-11e5-983b-2c6a0f8a285b.png)

2，数据问题：
查看历史趋势数据都不一致，见上图（慧眼）；所选时间范围一致，但是数据相差很大，慧眼现在的查看历史趋势数据都对不上。

**Comment by Gongyufei** [comment]
@zerocoolys @SubDong

**Comment by zerocoolys** [comment]
@SubDong 历史趋势做了吗?

**Comment by guochunyan** [comment]
问题1已修改

**Comment by SubDong** [comment]
![image](https://cloud.githubusercontent.com/assets/11551646/8142787/515d8c5a-11bd-11e5-80eb-7a72855b0937.png)
![image](https://cloud.githubusercontent.com/assets/11551646/8142797/74653ffe-11bd-11e5-8c7c-ffb16792521a.png)
![image](https://cloud.githubusercontent.com/assets/11551646/8142800/86e722fa-11bd-11e5-9906-695cd80dcf36.png)

@Gongyufei   @zerocoolys   这里只有只有7天的数据是应为  es里面只有7天的数据
