### ISSUE TITLE
查看历史趋势的ui&数据：慧眼中涉及到的模块

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#223]
红框内的模块都有 查看历史趋势数据的ui和数据问题(前面已经提过问题，不再重复）
![image](https://cloud.githubusercontent.com/assets/12438962/8099589/b4f3cbf4-1031-11e5-9001-d67e5b91193d.png)

**Comment by Gongyufei** [comment]
@zerocoolys @SubDong

**Comment by guochunyan** [comment]
历史趋势数据的显示已解决
