### ISSUE TITLE
图表UI&数据：外部链接

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#224]
1，ui修改：
图表下方加一栏：外部链接网址、指标数据、占比
饼图和表格联动
弹窗内不要出现链接地址
![image](https://cloud.githubusercontent.com/assets/12438962/8100897/16e36c4a-1044-11e5-8d49-a62300fcd4f7.png)
ui设计图示例：
![image](https://cloud.githubusercontent.com/assets/12438962/8100935/889dac7e-1044-11e5-882c-77e9fa7ada3d.png)
2，数据不一致
见下图，时间选择都是最近30天，数据如下：
![image](https://cloud.githubusercontent.com/assets/12438962/8100981/30e136f8-1045-11e5-9a12-8803f6342d79.png)
![image](https://cloud.githubusercontent.com/assets/12438962/8100991/461d6ea6-1045-11e5-93c8-e245fabbdf93.png)

**Comment by Gongyufei** [comment]
@SubDong 
@zerocoolys

**Comment by Gongyufei** [comment]
饼图内出现的是百分比，最多10个（例如，点击上面的浏览量，那么出现浏览量占比的前十个；点击饼图，右边的图表是其相关链接、指标数据，占比

**Comment by fangzhenping** [comment]
@zerocoolys @guochunyan  @Gongyufei 对的 ，我只是做了样式美化效果图，信息内容我是随意在你们已有的现摘取的，饼图信息是百分比，  曲线图是指标信息

**Comment by xiaoweiqb** [comment]
表格数据不一致转给 @SubDong

**Comment by SubDong** [comment]
@Gongyufei   @zerocoolys   表格 数据上的不一致 是因为 es中的数据被删除过，这样uv就会存在差异，还有原因就是在  在晚上12点钟 时间 跨域时也会出现在这种情况。
另  选择近30天数据在 历史趋势里面看的时候也应该是看近30天数据，因为在进到历史趋势之前所统计的数据是30天累加出来的总和，当选择1天时则只需在历史趋势里面查看某一天对应的数据

**Comment by SubDong** [comment]
ps： 上面说的
![image](https://cloud.githubusercontent.com/assets/11551646/8142897/e0cd1536-11c2-11e5-9358-1a509e37b512.png)，不是选择时间近30天  而是表格里面30天数据的总和
