### ISSUE TITLE
（ui）网站概览-访客地图

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#23]
看不清楚地域（傲游、ie浏览器都试过）
![image](https://cloud.githubusercontent.com/assets/12438962/7664402/fe12853e-fbb7-11e4-9d8f-adba40f276a4.png)

**Comment by guochunyan** [comment]
已修改，以下图片为遨游（1280px）,1280PX以下为一个图表一行。。
![qq 20150517141632](https://cloud.githubusercontent.com/assets/11551612/7669310/52727818-fc9f-11e4-861b-788df9f5c4ab.png)
