### ISSUE TITLE
UI需求：增加自定义指标

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#231]
1，点击 查看历史趋势的链接页面后，无自定义指标，请添加此块内容
2，增加模块：涉及到查看历史趋势的模块。（见截图）
辛苦：）

![image](https://cloud.githubusercontent.com/assets/12438962/8146490/f1bd63f0-126c-11e5-8fa7-be4a95331439.png)

**Comment by guochunyan** [comment]
@Gongyufei @zerocoolys  百度模块中历史趋势无自定义指标，建议放到二期考虑
