### ISSUE TITLE
（表格）趋向分析 

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#24]
选择 按日 ，下面的 日期 表格应该按日表现数据
同样如果选择 按周、按月，应该以 周、月 表现；与上面选择条件一样
![image](https://cloud.githubusercontent.com/assets/12438962/7664530/f74ff59a-fbbe-11e4-9be4-affed234f4b3.png)

![image](https://cloud.githubusercontent.com/assets/12438962/7664528/eb7ba8b8-fbbe-11e4-9faf-87460c1f6aa2.png)

**Comment by Gongyufei** [comment]
不能同时出现两个选择时间
![image](https://cloud.githubusercontent.com/assets/12438962/7718307/f52735b0-fee0-11e4-8214-b71de5d62c89.png)

**Comment by SubDong** [comment]
![image](https://cloud.githubusercontent.com/assets/11551646/7722529/d21fa06a-ff13-11e4-95e2-cda50c407df7.png)

**Comment by SubDong** [comment]
在外网上访问  浏览出来后是上图效果
