### ISSUE TITLE
表格：页面分析

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#242]
问题：点击直接访问的 入口页链接
1，入口页面没有显示出 url名称
2，入口页链接打不开
![image](https://cloud.githubusercontent.com/assets/12438962/8147835/ec922e62-12b0-11e5-90bc-19199740bc8f.png)
![image](https://cloud.githubusercontent.com/assets/12438962/8147836/fc8459e4-12b0-11e5-85d8-3ca229c366a7.png)

**Comment by TomDing729** [comment]
属于来源分析- 全部来源--列表下。    生产机器上复测，没有出现上述的情况。
