### ISSUE TITLE
（ui）来源分析模块：

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#25]
新老访客比率？
![image](https://cloud.githubusercontent.com/assets/12438962/7664548/b8b435b6-fbbf-11e4-8418-a60cdfea0ea7.png)

**Comment by guochunyan** [comment]
![qq 20150517141359](https://cloud.githubusercontent.com/assets/11551612/7669299/e9dfe1d2-fc9e-11e4-8081-24a5cf442547.png)

**Comment by Gongyufei** [comment]
![image](https://cloud.githubusercontent.com/assets/12438962/7696734/8fbfd302-fe32-11e4-964f-5f5bb07051f2.png)

**Comment by guochunyan** [comment]
已修改
