### ISSUE TITLE
UI&图表功能：入口页面

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#250]
1，饼图的百分比数在饼图里有些拥挤，是否可以放在图外显示：）
2，饼图所选数据与右侧相关曲线联动，便于客户查看。
辛苦，请调整：）
![image](https://cloud.githubusercontent.com/assets/12438962/8148264/8022c87e-12c7-11e5-9da9-bd39dc90b70b.png)

**Comment by Gongyufei** [comment]
@xiaoweiqb

**Comment by guochunyan** [comment]
1、已处理#412

**Comment by zerocoolys** [comment]
@Gongyufei @guochunyan 
这个bug先关闭，如果仍然有需求请重新开一个issue
