### ISSUE TITLE
数据：推广概况模块

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#252]
选择昨天、最近7天、最近30天；选择任意数据指标，中间图表数据和下面的表格数据，都不一致。
（请查看数据，截图上传不了）

**Comment by Gongyufei** [comment]
@zerocoolys @xiaoweiqb

**Comment by xiaoweiqb** [comment]
现在昨天，7天，30天的推广数据已经有了，因为perfect2015的百度账号绑定的域名为www.perfect-cn.cn,so，所有点击该账号的关键字都跳转到perfect-cn.cn的网站，所以无法跟踪该关键字的流量数据，所以流量数据一直都是0

**Comment by xiaoweiqb** [comment]
@zerocoolys
