### ISSUE TITLE
图表：弹窗指标和数据展现错误

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#260]
问题：
今日统计、昨日统计、最近30天，转化次数和转化率的柱状图指标和数据 为pv；请修改，谢谢！
![image](https://cloud.githubusercontent.com/assets/12438962/8149380/9c7a3e72-12f3-11e5-8218-ff2747a92180.png)

**Comment by xiaoweiqb** [comment]
转化次数和转化率还没有计算

**Comment by Gongyufei** [comment]
嗯呢，没有这个指标数据，柱形图弹窗不要出现pv数据了，要保持一致的哈。

**Comment by xiaoweiqb** [comment]
那我把这个隐藏掉！

**Comment by Gongyufei** [comment]
ok哈，多谢
