### ISSUE TITLE
UI：网站概览（增加浏览量占比）

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#264]
增加指标 浏览量占比
![image](https://cloud.githubusercontent.com/assets/12438962/8226012/8ac86d16-15cd-11e5-8771-f13b76b756a9.png)
![image](https://cloud.githubusercontent.com/assets/12438962/8226020/970a62fa-15cd-11e5-9a07-02bd425bcc31.png)

**Comment by zerocoolys** [comment]
@xiaoweiqb

**Comment by xiaoweiqb** [comment]
i seed
