### ISSUE TITLE
ui：访客分析

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#267]
问题：
当页汇总：平均访问时长空白；如没有数据，平均访问页数为0
没有数据，没有下一级内容，就可以不用+号了。谢谢！
![image](https://cloud.githubusercontent.com/assets/12438962/8322383/c7d32a14-1a66-11e5-96dd-684b33e0122f.png)

**Comment by Gongyufei** [comment]
页面分析模块中的受访页面&入口页面（指标概览），也有以上数据指标问题：）

**Comment by guochunyan** [comment]
#256
