### ISSUE TITLE
（表格）网站概况:

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#27]
选择今天、昨天单日时间，可以按时、按日表现数据；
现在问题是：按日的表现数据 与 按时一样

![Uploading image.png…]()

**Comment by Gongyufei** [comment]
![image](https://cloud.githubusercontent.com/assets/12438962/7673751/009842c2-fd4c-11e4-9723-b08b820f2624.png)

**Comment by xiaoweiqb** [comment]
今日的按日，昨日的按日，其实也就是一天的数据，一天的数据不就是显示的24个小时的数据，如果要像百度那样今日，昨日按日显示一条数据的话，完全没有意义啊，如果确实需要那样改，那也可以，你确认一下就行了！

**Comment by Gongyufei** [comment]
一天的数据就是一个汇总的数据，有意义啊。需要。
