### ISSUE TITLE
[图表] 设备环境-数据完全不统一!

### ISSUE THREAD

**Issue by zerocoolys** [zerocoolys/sshuiyan#28]
![image](https://cloud.githubusercontent.com/assets/2757581/7674222/36112672-fd55-11e4-9cc0-8b9ae298eb2d.png)

表中有"联通" , 图表里面有 电信, 联通等, 另外显示也不全.

**Comment by xiaoweiqb** [comment]
什么？没懂你意思

**Comment by xiaoweiqb** [comment]
因为图表中只允许选择两项，而且图表中的指标是不同步表格的图表的，至于表格显示的联通，图表中不显示的bug已经修改
