### ISSUE TITLE
图表：网站概览-设备环境

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#287]
问题：
点击pc或移动，饼图出现以下问题；
![image](https://cloud.githubusercontent.com/assets/12438962/8491930/63494154-2174-11e5-9fcc-937ab16e8bc5.png)

**Comment by guochunyan** [comment]
@Gongyufei 点击对应的指标就是取消显示，现在是两个都取消了显示 所以页面上就没有相对应的数据图表显示
