### ISSUE TITLE
图表：日期显示

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#289]
选择 按日 ，日期显示有问题。请调整：）

![image](https://cloud.githubusercontent.com/assets/12438962/8493972/e14ae53a-2192-11e5-9d4f-96596f6d4690.png)

**Comment by xiaoweiqb** [comment]
这个是哪个页面呢？

**Comment by Gongyufei** [comment]
网站概览

**Comment by xiaoweiqb** [comment]
我尽快该，这个是后台修改了东西，以前我们时区不对，
