### ISSUE TITLE
（ui）百度统计：增加指标名称解释

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#30]
![image](https://cloud.githubusercontent.com/assets/12438962/7676567/98c6dede-fd77-11e4-85b3-d60a5e1b7eb5.png)

![image](https://cloud.githubusercontent.com/assets/12438962/7676587/c1176912-fd77-11e4-91b9-8a10cf0d9692.png)

**Comment by guochunyan** [comment]
![qq 20150521134619](https://cloud.githubusercontent.com/assets/11551612/7742286/079d7cec-ffc0-11e4-8cd8-90bc44bc3f43.png)
