### ISSUE TITLE
读取数据的时候加入loading效果

### ISSUE THREAD

**Issue by zerocoolys** [zerocoolys/sshuiyan#301]
![Uploading image.png…]()

@guochunyan @xiaoweiqb

**Comment by zerocoolys** [comment]
![image](https://cloud.githubusercontent.com/assets/2757581/8586833/053aa8f8-2626-11e5-97b4-7e27c463d979.png)

**Comment by guochunyan** [comment]
@zerocoolys 这块魏巍在重写方法，完成以后就加上去

**Comment by zerocoolys** [comment]
@sgWeiMinSheng
