### ISSUE TITLE
图表：按周日期显示问题

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#304]
选择按周，日期乱码
![image](https://cloud.githubusercontent.com/assets/12438962/8644543/6af867b2-2972-11e5-9e24-f9626690240c.png)

**Comment by guochunyan** [comment]
![qq 20150713153742](https://cloud.githubusercontent.com/assets/11551612/8644842/158bcf50-2975-11e5-9a9f-5770b03ea634.png)

**Comment by xiaoweiqb** [comment]
问题已经解决，暂未部署！
