### ISSUE TITLE
图表：时间格式

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#306]
时间格式统一吧，如：15:06、15:07.....辛苦调整
![image](https://cloud.githubusercontent.com/assets/12438962/8645023/358b7584-2976-11e5-8c5c-23ed7d5c6480.png)

**Comment by xiaoweiqb** [comment]
所有时间相关的都这样？还是说只有实时访客？

**Comment by Gongyufei** [comment]
只实时访客

**Comment by xiaoweiqb** [comment]
我刚好看到这个！
