### ISSUE TITLE
图表：网站概览

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#309]
网站概览页面，请调整一下;)
![image](https://cloud.githubusercontent.com/assets/12438962/8665807/035f78ee-2a1b-11e5-9acf-b209edb731d2.png)

**Comment by xiaoweiqb** [comment]
这个是网速加载过慢导致！新版本已经优化了加载速度的问题！

**Comment by xiaoweiqb** [comment]
已经重新部署
