### ISSUE TITLE
（ui）页面分析 指标数据单位问题

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#31]
![image](https://cloud.githubusercontent.com/assets/12438962/7676689/9ea062c0-fd78-11e4-8dfb-e1db943d63ea.png)
![image](https://cloud.githubusercontent.com/assets/12438962/7676700/c36fcf0a-fd78-11e4-9fd3-b159b0f08906.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/7876170/f0051c94-05f9-11e5-8fce-dcf9a44c4f57.png)
