### ISSUE TITLE
图表：入口页面

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#315]
需求：
1，饼图和右侧的曲线图 展现的是上面所选数据指标的前三名的url数据（饼图展现百分比、曲线图分时段展现数据和百分比）
2，饼图、曲线图和曲线图下面的url 及数据，都是联动的
辛苦调整;)
![image](https://cloud.githubusercontent.com/assets/12438962/8719393/0bf78e96-2bde-11e5-9f5c-3e9ed79a0b08.png)

**Comment by xiaoweiqb** [comment]
现在曲线图是鼠标点击会显示三条数据，如果联动，下面的文字如何显示？
