### ISSUE TITLE
表格ui：来源分析

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#320]
需求：如果没有下级菜单内容，就不需要 ＋号
![image](https://cloud.githubusercontent.com/assets/12438962/8952953/048f7968-360e-11e5-9d14-7c4870ab6867.png)

![image](https://cloud.githubusercontent.com/assets/12438962/8952927/e4a2922a-360d-11e5-97b2-df4e60f51181.png)

**Comment by Gongyufei** [comment]
![image](https://cloud.githubusercontent.com/assets/12438962/8953089/bf7efda2-360e-11e5-923f-d7b9c0fd3074.png)

**Comment by guochunyan** [comment]
空白已解决，暂部署新版本
