### ISSUE TITLE
UI：网站概览-设备环境

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#325]
问题：点击饼图上的pc，移动模块高亮显示，不符合使用习惯。辛苦调整，点击某一个模块，被点击模块高亮显示。辛苦啦
![image](https://cloud.githubusercontent.com/assets/12438962/9033744/af49c66e-39fc-11e5-90e0-ead4e25f99ed.png)

**Comment by guochunyan** [comment]
#339
