### ISSUE TITLE
UI：百度推广-搜索推广

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#328]
需求：1，请调整下表格当页汇总格式
2，表格中如果只有一页，不需要出现 页码和 每页显示 ；只当页汇总就ok。（表格的需求，慧眼中的所有表格都通用，多谢）
辛苦调整，多谢！

![image](https://cloud.githubusercontent.com/assets/12438962/9076322/a580d5fc-3b53-11e5-8492-d012f4ae52fd.png)

**Comment by Gongyufei** [comment]
@SubDong

**Comment by zymin** [comment]
@Gongyufei #273 中只是说不要上一页和下一页的,确定不要所有分页提示么？

**Comment by Gongyufei** [comment]
如果表格中的数据<20（每页最低显示20）就不需要有分页的提示;)
