### ISSUE TITLE
表格：实时访客

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#331]
红框内的地域是哪里哈？
![image](https://cloud.githubusercontent.com/assets/12438962/9077203/c58a7808-3b5d-11e5-8c99-0241b5afd555.png)

**Comment by conchz** [comment]
@Gongyufei ![qq 20150805155819](https://cloud.githubusercontent.com/assets/9883493/9080981/2adcdf98-3b8b-11e5-8b74-7f9b8a7a02bf.png)

这个是从淘宝的IP地址库解析出来的， 行政区划上对县级市都是这个称呼.
