### ISSUE TITLE
UI：趋向分析

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#334]
趋向分析中：
春燕，来源过滤中增加快捷筛选 （百度付费推广、百度搜索推广、百度网盟推广、百度自然搜索）
![image](https://cloud.githubusercontent.com/assets/12438962/9077800/11bc611c-3b65-11e5-8c4b-fd6d267bc04e.png)

与下面表格联动，辛苦调整，谢谢！

**Comment by Gongyufei** [comment]
@SubDong

**Comment by zymin** [comment]
@SubDong 我增加了快捷筛选，数据联动就麻烦你了~

**Comment by guochunyan** [comment]
#312
