### ISSUE TITLE
表格数据：访客地图

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#335]
问题：表格中的对比数据乱码，请辛苦调整
![image](https://cloud.githubusercontent.com/assets/12438962/9079446/c5c2af2e-3b7c-11e5-8142-e93dd783d2c5.png)
![image](https://cloud.githubusercontent.com/assets/12438962/9079454/d17cce9e-3b7c-11e5-95df-340a53ed91ad.png)

**Comment by SubDong** [comment]
与  #342  属于同一类型问题
