### ISSUE TITLE
饼图ui：慧眼中的所有饼图（入口页面&访客地图）

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#339]
问题：点击饼图上的某一个扇区，被点击的高亮显示。辛苦啦
![image](https://cloud.githubusercontent.com/assets/12438962/9080080/f40fbb28-3b82-11e5-933d-fce9cb32151f.png)
![image](https://cloud.githubusercontent.com/assets/12438962/9080087/fed1cb82-3b82-11e5-99c6-7f76ac8051f3.png)

**Comment by zymin** [comment]
@Gongyufei 要那种高亮？可以具体说下要那种么？

**Comment by Gongyufei** [comment]
点击某一个扇区，突出显示；现在点击某一个扇区，被点击的没有突出显示。
![image](https://cloud.githubusercontent.com/assets/12438962/9162663/4f54caba-3f79-11e5-9a3e-65f60255be28.png)
