### ISSUE TITLE
表格数据：趋向分析-实时访客

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#349]
问题：选择 搜索引擎 ，没有数据（没有联动）；没有搜索词。请辛苦调整，多谢！
![image](https://cloud.githubusercontent.com/assets/12438962/9269435/3403c786-429c-11e5-8857-8af60dcc8576.png)

**Comment by SubDong** [comment]
@Gongyufei   我这边测试选择搜索引擎  有联动 有数据  有搜索词   请再确认下
![qq 20150817102527](https://cloud.githubusercontent.com/assets/11551646/9296990/72887d96-44ca-11e5-87a6-8de8cb6f61a8.png)

**Comment by zerocoolys** [comment]
@Gongyufei 现在百度已经屏蔽了搜索词，这块的功能无法跟百度保持一致
