### ISSUE TITLE
U：外部链接

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#352]
问题：
点击某一扇区，红框内的内容也会动。辛苦调整哈
![image](https://cloud.githubusercontent.com/assets/12438962/9270695/43b01e64-42a6-11e5-82a8-e8154f4d735f.png)

**Comment by guochunyan** [comment]
![qq 20151019112152](https://cloud.githubusercontent.com/assets/11551612/10569084/8355201a-7653-11e5-86de-ed4e9663692d.png)
红框出文字过长后会，当前行会折行，一期时已对文字进行截取！
