### ISSUE TITLE
表格数据：来源分析

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#354]
选择同样日期，但数据不一致。请辛苦查询调整，谢谢！
![image](https://cloud.githubusercontent.com/assets/12438962/9321988/251399ac-45a0-11e5-8722-d959a473647f.png)
![image](https://cloud.githubusercontent.com/assets/12438962/9321992/2dcddc24-45a0-11e5-9df0-15fa509c5413.png)

**Comment by zerocoolys** [comment]
@Gongyufei 这个数据的差别应该从图上就能看出来吧，第一个图没有直接访问的。调整的方案应该考虑是否加上直接访问的方式。

**Comment by zerocoolys** [comment]
![image](https://cloud.githubusercontent.com/assets/2757581/9378058/090437a0-4751-11e5-97d7-e174e0ccb473.png)

@Gongyufei 截图里面也有直接访问的类型

**Comment by Gongyufei** [comment]
谢谢：）

**Comment by Gongyufei** [comment]
全部来源现在数据一致了，下面的这个问题请解决一下。
外部链接里面不应该出现直接访问的数据，请查看。
![image](https://cloud.githubusercontent.com/assets/12438962/11889592/d59bac98-a585-11e5-99d9-e0121b021b48.png)
