### ISSUE TITLE
数据问题  页面分析受访页面 访客数据有误 新访客+老访客＞全部

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#362]
页面地址：http://hy.best-ad.cn/#/page/indexoverview/history

重现路径：慧眼-页面分析-受访页面-指标概览-页面url-查看历史趋势

问题描述：高级筛选的列表中，新访客+老访客＞全部。
![1](https://cloud.githubusercontent.com/assets/14328394/10069929/e7e08a04-62e1-11e5-9ef2-4981daa7b081.jpg)
![2](https://cloud.githubusercontent.com/assets/14328394/10069961/0cbed0d8-62e2-11e5-8518-72730b86dc02.jpg)
![3](https://cloud.githubusercontent.com/assets/14328394/10069968/1a7f54ae-62e2-11e5-83a8-81a952b11740.jpg)

**Comment by TomDing729** [comment]
该数据是这样引发，同一个客户，同一天，访问两次，第一次为新访客，第二次为老访客。 故所以，它在两边都有记录。
