### ISSUE TITLE
数据问题  页面分析受访页面  高级筛选 来源过滤 存在数据覆盖问题

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#363]
页面地址：http://hy.best-ad.cn/#/page/indexoverview/history

重现路径：慧眼-页面分析-受访页面-指标概览-页面url-查看历史趋势

问题描述： 高级筛选的来源过滤功能，有直接访问、搜索引擎、外部链接三个筛选项，当直接在下拉框选择时，功能是生效的，但当点击其下的新访客或老访客时，数据为全部数据，没有起到筛选功能。当点击了新访客或老访客，再点击筛选条件下的全部按钮时，筛选功能也失效。

 页面分析子栏目均存在该问题。

举例：全部数据来源都为直接访问时，点击搜索引擎，数据都为0，但点击新访客或老访客时，出现数据。外部链接同理。

![default](https://cloud.githubusercontent.com/assets/14328394/10070289/1a3ca9a4-62e4-11e5-9b62-ab6c0aa8b568.jpg)
![- -](https://cloud.githubusercontent.com/assets/14328394/10070291/1ec7ad66-62e4-11e5-9431-15e150fe3d08.jpg)
![1](https://cloud.githubusercontent.com/assets/14328394/10070295/26408e0a-62e4-11e5-8b0e-1cd7989bf4bd.jpg)
![2](https://cloud.githubusercontent.com/assets/14328394/10070296/2642b87e-62e4-11e5-971a-308262b248e6.jpg)
![3](https://cloud.githubusercontent.com/assets/14328394/10070297/2642ccc4-62e4-11e5-8b7f-fe1135c3477f.jpg)
![4](https://cloud.githubusercontent.com/assets/14328394/10070298/266bac20-62e4-11e5-9531-7237b42bfedd.jpg)
![1](https://cloud.githubusercontent.com/assets/14328394/10070305/2fd0f298-62e4-11e5-9374-6a27af3283bd.jpg)
![2](https://cloud.githubusercontent.com/assets/14328394/10070443/1521ad88-62e5-11e5-89eb-0e1168c65661.jpg)

**Comment by TomDing729** [comment]
统一修改解决的。  支持多条件过滤。
