### ISSUE TITLE
趋向分析-实时访客

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#368]
趋向分析-实时访客
a.列表中入口页面的链接不能访问
b.展开后入口页面和最后停留的页面链接地址失效
![a](https://cloud.githubusercontent.com/assets/11189612/10070989/d84def08-62e8-11e5-8826-9be605916c2d.png)
![a 1](https://cloud.githubusercontent.com/assets/11189612/10070993/e036fc5a-62e8-11e5-8d76-b3372dbf4ce3.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10600861/250c252e-7740-11e5-91bf-a59238ed5dfa.png)
