### ISSUE TITLE
(日历）所有涉及到日历的模块

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#37]
问题：
1，建议日历由左至右 表现
2，选择开始时间，会默认时间段到今日，不应该默认选择时间到今日
3，选择时间段确定后， 昨天 的时间条件不应该再为蓝色
4，与其他时间段对比 后面的日期取消 （默认时间段问题同上）
![image](https://cloud.githubusercontent.com/assets/12438962/7721472/806f4e9a-ff0a-11e4-8361-300f4110f351.png)

**Comment by guochunyan** [comment]
![rili](https://cloud.githubusercontent.com/assets/11551612/7723666/f2e48f5a-ff1c-11e4-96e6-e1921ce68032.png)
