### ISSUE TITLE
实时访客列表查询-地域过滤重复

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#373]
每一个筛选条件应该是唯一的
![d](https://cloud.githubusercontent.com/assets/11189612/10091690/fe0923ba-6370-11e5-91b9-311344ccdfb2.jpg)

**Comment by sgWeiMinSheng** [comment]
已解决
![qq 20150929112243](https://cloud.githubusercontent.com/assets/10495048/10154630/7fdac12c-669c-11e5-9fd9-bc73b741f500.png)
