### ISSUE TITLE
功能不能实现 页面分析受访页面的子页面 页面价值分析、入口页分析、退出页分析页面的发送报告按钮失效，功能不能实现。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#376]
页面地址：http://hy.best-ad.cn/#/page/indexoverview

重现路径：慧眼-页面分析-受访页面-页面价值分析、入口页分析、退出页分析

问题描述：页面分析受访页面的子页面 页面价值分析、入口页分析、退出页分析页面的发送报告按钮失效，功能不能实现。
                指标概览页面的报告功能正常。但关闭操作成功的按钮后，设置发送报告的时间仍存在，需手动再次关闭设置对话框，用户体验不佳。建议点击操作成功确认按钮或，设置框一起关闭。

![image](https://cloud.githubusercontent.com/assets/14328394/10092042/b90c8f0a-6374-11e5-837a-6140f2df670c.png)

![4](https://cloud.githubusercontent.com/assets/14328394/10091981/0f01faf4-6374-11e5-8b8f-83a4ab3e6f6f.jpg)

**Comment by wangjing1230** [comment]
问题仍然存在。

**Comment by TomDing729** [comment]
和肖伟交流过，页面分析-受访页面-页面价值分析、入口页分析、退出页分析 的发送功能和“指标概览” 是通用的。  @xiaoweiqb
