### ISSUE TITLE
实时访客-列表来源-直接访问-应该不可点击

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#377]
![f](https://cloud.githubusercontent.com/assets/11189612/10092153/0f28cd26-6376-11e5-824c-691ea5b01176.jpg)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10476093/580baaa2-727d-11e5-9b01-f0aeb98ff693.png)
这种还是需要点击的嘛。只有来源是直接访问的。不能点击是不

**Comment by icepros** [comment]
对 不能点击  只是字显示

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10478215/7dc69ca0-728e-11e5-8545-68ff121ed8eb.png)

**Comment by sgWeiMinSheng** [comment]
指令结合ng-switch
