### ISSUE TITLE
趋向分析-今日统计未到时间也显示出来？

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#379]
我测的时候未到12点  但是列表默认显示的24小时的数据  未到当前时间的数据为0
百度上的是未到当前时间的数据不显示
![h](https://cloud.githubusercontent.com/assets/11189612/10092491/7c5553bc-6379-11e5-957b-d48a491b8fda.jpg)

**Comment by zerocoolys** [comment]
@icepros @sgWeiMinSheng 这个不属于bug。
可以考虑在将来完善。
