### ISSUE TITLE
页面逻辑问题 页面分析-入口页面 查看页面url历史趋势 其中点击最近7天数据时，折线图和列表页只显示了有数据的日期。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#382]
页面地址：http://hy.best-ad.cn/#/page/entrancepage/history

重现路径：慧眼-页面分析-入口页面-指标概览-页面url-查看历史趋势-最近7天

问题描述：查看页面url历史趋势 其中点击最近7天数据时，折线图和列表页只显示了有数据的日期。按页面逻辑，无论有数据否，都应该显示7天的数据，而且目前最近30天的数据，也是全部显示，而非只展示有数据的日期，所以前后页面逻辑也不相同。百度统计也是全部展示。

![6](https://cloud.githubusercontent.com/assets/14328394/10095672/1280fe3a-639e-11e5-8e22-ba0480df5da7.jpg)

![6 2](https://cloud.githubusercontent.com/assets/14328394/10095665/0507fdd0-639e-11e5-9b5d-2642802e8d4e.jpg)

![6 1](https://cloud.githubusercontent.com/assets/14328394/10095663/02b584ee-639e-11e5-9aa0-e5137fca561a.jpg)
![6 3](https://cloud.githubusercontent.com/assets/14328394/10095694/308d1210-639e-11e5-8403-6f5e8fbb79b7.jpg)

**Comment by TomDing729** [comment]
没有重现该问题。分析，可能是因为环境刚刚搭建，后台数据索引还没有创建。

**Comment by wangjing1230** [comment]
外网百思账号，仍然存在该问题。

**Comment by wangjing1230** [comment]
![8](https://cloud.githubusercontent.com/assets/14328394/10874610/7e2f0fc8-8162-11e5-98b1-e5f26247dac3.jpg)

**Comment by wangjing1230** [comment]
无法重现，先关闭该问题。
