### ISSUE TITLE
来源分析-全部来源

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#384]
直接访问没有展开项吧
![zz](https://cloud.githubusercontent.com/assets/11189612/10126987/d1138c56-65cd-11e5-8b8e-b2156f621190.png)

**Comment by sgWeiMinSheng** [comment]
这个问题以前悲催姐改过源代码，但是没有改出来，

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10784448/242c576e-7d99-11e5-83e3-5728eb911ee0.png)
