### ISSUE TITLE
全部来源-外部连接扩展项无法访问且入口页无数据

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#386]
![j](https://cloud.githubusercontent.com/assets/11189612/10129151/9ada55e6-65ed-11e5-9c73-8c7770d0d1cf.jpg)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10571888/dff48226-7675-11e5-9c6e-6faa104a4588.png)
