### ISSUE TITLE
数据问题 查看地域历史趋势 无论今天、昨天、最近7天或自定义查看日期时，顶部显示均为最近30天数据。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#387]
页面地址：http://hy.best-ad.cn/#/visitor/provincemap/history

重现路径：慧眼-访客分析-访客地图-最近7天-自定义指标-查看地域历史趋势自定义日期

问题描述：查看历史趋势时，顶部彩色数据，为最近30天数据，且不随页面汇总变化，被固定了。无论是今天、昨天、最近7天或自定义查看日期时，显示的数据均为最近30天数据。

![c](https://cloud.githubusercontent.com/assets/14328394/10129264/bbbb300e-65ee-11e5-858f-9c75ef36a3f4.jpg)

![a](https://cloud.githubusercontent.com/assets/14328394/10129160/b3a7847c-65ed-11e5-91a4-72953370668c.jpg)
![b](https://cloud.githubusercontent.com/assets/14328394/10129161/b3dcafd0-65ed-11e5-9297-c29027f4c6a2.jpg)
![d](https://cloud.githubusercontent.com/assets/14328394/10129268/c2b8f4f4-65ee-11e5-8f77-a1f839d8a684.jpg)

**Comment by TomDing729** [comment]
#399，已描述。 已修复
