### ISSUE TITLE
数据错误 查看历史趋势，高级筛选，新访客数据错误。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#389]
页面地址：http://hy.best-ad.cn/#/visitor/provincemap/history

重现路径：慧眼-访客分析-访客地图-最近7天-自定义指标-查看地域历史趋势自定义日期

问题描述：查看历史趋势时，查看最近30天数据，在高级筛选中，选择新访客功能，则数据错误，调用的数据来源暂未找到，核实后不是全部地域最近30天的浏览量，虽然17456和17532差距并不是很大。

![e](https://cloud.githubusercontent.com/assets/14328394/10129452/8b41f4e2-65f0-11e5-9aa5-e09afde00c75.jpg)

**Comment by TomDing729** [comment]
请复测。

**Comment by zerocoolys** [comment]
@TomDing729 为什么需要复测？是无法重现还是？

**Comment by wangjing1230** [comment]
问题仍然存在。
![7](https://cloud.githubusercontent.com/assets/14328394/10874431/1f452dc4-815f-11e5-982c-a8724e71153b.jpg)

**Comment by TomDing729** [comment]
生产机上的数据， 是正确的， 页面右下角，每页显示条数，调至到50。

**Comment by TomDing729** [comment]
描述： 初始值正确，需要点击查询条件后，即可显示出来。  之前我没有理解正确。 
  建议： 此类问题，增加个重现步骤，这样定为问题更准确。

**Comment by wangjing1230** [comment]
好的
