### ISSUE TITLE
（图表）访客分析：访客地图 和设备环境

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#39]
没有图表
![image](https://cloud.githubusercontent.com/assets/12438962/7745018/8e78edd6-ffda-11e4-913c-11c9223d2921.png)

**Comment by Gongyufei** [comment]
肖伟，饼图需求：点击饼图上的某一地域色块后，突出显示；）
![image](https://cloud.githubusercontent.com/assets/12438962/7745449/c178823e-ffdd-11e4-920e-f662a26b6676.png)

**Comment by zerocoolys** [comment]
@Gongyufei @xiaoweiqb 第二个需求作为改进放入到二期开发.

**Comment by zerocoolys** [comment]
![image](https://cloud.githubusercontent.com/assets/2757581/7745588/faaaff4a-ffde-11e4-847a-93b5d9d036ff.png)

@Gongyufei 已经修复
