### ISSUE TITLE
全部来源-对比数据显示不一致

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#391]
![m](https://cloud.githubusercontent.com/assets/11189612/10129819/1497c57e-65f5-11e5-9d48-8e69b707f8bc.jpg)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10601192/61a6d784-7742-11e5-855f-fb4430471049.png)
![image](https://cloud.githubusercontent.com/assets/10495048/10601202/67e42bba-7742-11e5-8a34-c157e8ed312b.png)

**Comment by icepros** [comment]
经测试未解决

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10687103/1a03d3de-799d-11e5-92cb-8af4abea5f90.png)
![image](https://cloud.githubusercontent.com/assets/10495048/10687134/3911083c-799d-11e5-9f4f-e2ebe188e250.png)
