### ISSUE TITLE
数值错误 客户端属性柱状图横坐标皆为“NaN-aN-aN”

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#392]
页面地址：http://hy.best-ad.cn/#/visitor/equipment

重现路径：慧眼-访客分析-设备环境-客户端属性-柱状图

问题描述：柱状图横坐标皆为“NaN-aN-aN”，客户端属性下拉框中所有选项的柱状图都是这样。

![f](https://cloud.githubusercontent.com/assets/14328394/10130236/2eac645c-65f9-11e5-8162-925bf9c1bd18.jpg)

![g](https://cloud.githubusercontent.com/assets/14328394/10130173/93a013be-65f8-11e5-8232-a8f332013c11.jpg)

**Comment by zerocoolys** [comment]
@wangjing1230 
如果暂时无法重现，就先关闭
