### ISSUE TITLE
搜索引擎-统计指标数据不一致

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#393]
![n](https://cloud.githubusercontent.com/assets/11189612/10130174/940a8bc2-65f8-11e5-8430-0451e915db28.jpg)

**Comment by icepros** [comment]
跳出率和平均访问页数   也是不一致的

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10536873/dceffe22-7420-11e5-819c-c32c10bd39f3.png)

**Comment by icepros** [comment]
暂时无法测试
