### ISSUE TITLE
功能强化  设备环境中CSV数据，只能下载一次，不能连续下载，如要再次下载，则需刷新。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#395]
页面地址：http://hy.best-ad.cn/#/visitor/equipment

重现路径：慧眼-访客分析-设备环境-下载

问题描述：设备环境中在不同客户端属性下，下载CSV数据，只能下载一次，不能连续下载。如果要再次下载，则需刷新。

![r](https://cloud.githubusercontent.com/assets/14328394/10131566/c5189dc0-6603-11e5-8174-6d925c1d274d.jpg)

**Comment by TomDing729** [comment]
内网，外网测试，可重复下载。

**Comment by wangjing1230** [comment]
这个问题来源变化榜当时也遇到过，不知道是不是魏民生一起修复了。bug号#448，请查看。

**Comment by zerocoolys** [comment]
@sgWeiMinSheng 请确认一下这个issue
