### ISSUE TITLE
搜索词-统计指标值不唯一

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#396]
![o](https://cloud.githubusercontent.com/assets/11189612/10131759/31188f84-6605-11e5-8ef2-8a24be75e128.jpg)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10537510/e3c4e04c-7424-11e5-8399-d66ce75607bc.png)

**Comment by icepros** [comment]
暂时无法测试
