### ISSUE TITLE
功能矛盾  查看新老访客历史趋势时，高级筛选中存在访客过滤（新老访客选项） 

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#397]
页面地址：http://hy.best-ad.cn/#/visitor/novisitors/history

重现路径：慧眼-访客分析-新老访客-访客历史趋势

问题描述：查看新老访客历史趋势时，高级筛选中存在访客过滤（新老访客选项），但这是已经存在的前提，例如查看老访客历史记录就应全是老访客的数据，不应再有新老访客选项。
百度统计中也访客过滤的选项。

PS：时间选项样式有误，暂时无法重现过程。

![s](https://cloud.githubusercontent.com/assets/14328394/10132017/be3a9c26-6606-11e5-9da2-99f35091bae9.jpg)
![u](https://cloud.githubusercontent.com/assets/14328394/10132159/8a87680e-6607-11e5-91ed-fd9cc0e1491a.jpg)
![v](https://cloud.githubusercontent.com/assets/14328394/10132161/8ad0dfe8-6607-11e5-8120-bacbc6851ebb.jpg)

![t](https://cloud.githubusercontent.com/assets/14328394/10132206/d3e01ae6-6607-11e5-9196-b6e6aa1d4b44.jpg)

**Comment by zerocoolys** [comment]
@TomDing729 @wangjing1230 
这个issue涉及到多个问题，请修复可以重现的问题

**Comment by zerocoolys** [comment]
![image](https://cloud.githubusercontent.com/assets/2757581/10862238/337a766c-7fdb-11e5-99db-ed865ff63eef.png)

**Comment by wangjing1230** [comment]
时间样式问题无法重现，请完善新老访客问题。
