### ISSUE TITLE
功能失效  新老访客历史趋势页面，下载数据CSV失效

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#398]
页面地址：http://hy.best-ad.cn/#/visitor/novisitors/history

重现路径：慧眼-访客分析-新老访客-访客历史趋势

问题描述：新老访客历史趋势页面，下载数据CSV失效。

![w](https://cloud.githubusercontent.com/assets/14328394/10132635/0917d9f4-660a-11e5-931a-7538784c8481.jpg)

**Comment by TomDing729** [comment]
在内网，测试没有问题。 外网   414 Request-URI Too Large，可能需要修改  nginx 的参数。  
client_header_buffer_size 
large_client_header_buffers
