### ISSUE TITLE
搜索词-列表后台无数据

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#400]
![source_search7](https://cloud.githubusercontent.com/assets/11189612/10153938/ed5584b6-6693-11e5-8643-980fe37c0b85.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10537253/0fa02d40-7423-11e5-8e56-44614d00d1e5.png)

**Comment by icepros** [comment]
暂时无法测试
