### ISSUE TITLE
全部来源-对比数据列表数据问题

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#405]
![source_all](https://cloud.githubusercontent.com/assets/11189612/10183528/609a3816-6763-11e5-9ffa-58b0ba88c992.png)
![source_all_bug](https://cloud.githubusercontent.com/assets/11189612/10183557/a38c8566-6763-11e5-9c1a-ec52eef4d389.jpg)

统计指标的对比数据都有但是charts的数据没有
![source_all_charts](https://cloud.githubusercontent.com/assets/11189612/10183611/4d18cb3a-6764-11e5-8d5c-76b2c86eca4d.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10723655/1c4fa958-7bf8-11e5-96f3-64555f65c6d3.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10723670/2f2b4ea6-7bf8-11e5-91ec-990188b2a61e.png)

**Comment by icepros** [comment]
![source_502](https://cloud.githubusercontent.com/assets/11189612/10748043/fd6bc630-7c96-11e5-9b83-2de64be66b4a.png)
