### ISSUE TITLE
数据问题 查看页面分析历史趋势 无论今天、昨天、最近7天或自定义查看日期时，顶部显示均为最近30天数据。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#406]
页面地址：http://hy.best-ad.cn/#/page/indexoverview/history

重现路径：慧眼-页面分析-受访页面（入口页面）-查看页面url历史趋势

问题描述：查看历史趋势时，顶部彩色数据，为最近30天数据，且不随页面汇总变化，被固定了。无论是今天、昨天、最近7天或自定义查看日期时，显示的数据均为最近30天数据。

![a](https://cloud.githubusercontent.com/assets/14328394/10183518/46f254f2-6763-11e5-9db7-eb514f72c15d.jpg)
![d](https://cloud.githubusercontent.com/assets/14328394/10183519/47219eec-6763-11e5-948b-a14c7109ac80.jpg)

**Comment by TomDing729** [comment]
重复的BUG， 之前已经修改

**Comment by wangjing1230** [comment]
回归数据正确，但大量报错。
![1](https://cloud.githubusercontent.com/assets/14328394/10873142/8d0710ee-814a-11e5-8556-325491fda0e0.jpg)

**Comment by TomDing729** [comment]
目前版本，生产机器上没有报错。  属于关联代码，已被别的问题，统一修复。
