### ISSUE TITLE
数据问题 页面分析 受访页面历史趋势中平均访问时长数据有误

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#407]
页面地址：http://hy.best-ad.cn/#/page/indexoverview/history

重现路径：慧眼-页面分析-受访页面-指标概览-查看url历史趋势

问题描述：平均访问时长指标折线图数据和顶部彩色汇总数据，列表当页汇总数据不一致。查看数据请求，返回的数值均为0.

![b](https://cloud.githubusercontent.com/assets/14328394/10183635/87d32bb2-6764-11e5-8c84-34f07058b7fb.jpg)

![c](https://cloud.githubusercontent.com/assets/14328394/10183662/d42710d2-6764-11e5-8d77-59dc3d2a7ce4.jpg)

**Comment by wangjing1230** [comment]
问题在外网百思账号，仍然存在，请修复。

**Comment by TomDing729** [comment]
11/3 修复，  11/4 号测试。

**Comment by wangjing1230** [comment]
回归该问题已解决，关闭问题。
