### ISSUE TITLE
全部来源-对比日期相同的时候第一行数据没有或未做限定不能对比统一时间段的数据

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#408]
![source_all_sametime](https://cloud.githubusercontent.com/assets/11189612/10183767/331a0800-6766-11e5-8842-7559590df0ba.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10687455/cee802be-799f-11e5-89c2-40b326468f77.png)
可以对比相同时间啊
