### ISSUE TITLE
样式问题 页面分析入口页面 饼状图百分比数值重叠

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#412]
页面地址：http://hy.best-ad.cn/#/page/entrancepage

重现路径：慧眼-页面分析-入口页面

问题描述：入口页面中指标概览、流量分析、新访客分析、吸引力分析、转化分析，饼状图百分比数值均有重叠。
![n](https://cloud.githubusercontent.com/assets/14328394/10185742/f09e7f5c-677d-11e5-8f29-17228c2b6725.jpg)

**Comment by guochunyan** [comment]
此issuse的修改方法为#250 提出
