### ISSUE TITLE
外部链接-不能直接访问且当页汇总的最后一列的指标无数据

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#413]
PS：自定义指标查询后列表中最后一列指标的汇总一直为空(chrome中存在，firefox中不存在)
PS2：查看历史数据同上，IE9中直接看不到当页汇总这一行数据，IE11正常显示
![source_link](https://cloud.githubusercontent.com/assets/11189612/10185838/a0b2cede-677e-11e5-9a0a-0d0fc1807a6d.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10425291/f0698ce0-7108-11e5-80b2-147d4925c920.png)
可以显示啊。。

**Comment by sgWeiMinSheng** [comment]
不可以直接访问那个是设计如此么？

**Comment by icepros** [comment]
是可以直接点击访问的

**Comment by icepros** [comment]
显示问题存在不同浏览器不同版本的问题

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10720510/f72374d6-7bd2-11e5-98f5-16dc1f764f8d.png)
