### ISSUE TITLE
外部连接-charts图裂的UI显示

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#415]
这个浮框太大了吧
![source_link_ui](https://cloud.githubusercontent.com/assets/11189612/10186183/c4403014-6781-11e5-85c0-3ab3b48849ce.jpg)

**Comment by sgWeiMinSheng** [comment]
解决方案是截取还是显示固定长度的链接

**Comment by zerocoolys** [comment]
@Gongyufei 这个issue你看看呢

**Comment by Gongyufei** [comment]
截取吧

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10423467/5a744572-70f9-11e5-9ff3-8cbec2ad82bb.png)
