### ISSUE TITLE
历史记录UI-我只标记了来源分析其它模块也有

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#416]
![source_link_history](https://cloud.githubusercontent.com/assets/11189612/10186734/f8843056-6785-11e5-98bc-9d9d3ee5a173.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10421145/d4910e32-70d4-11e5-8e1b-b15e8065a7ce.png)

**Comment by icepros** [comment]
@zymin  @guochunyan  @sgWeiMinSheng  你们保留的多少个字符？
