### ISSUE TITLE
数据问题 页面分析入口页面 UV数据echart和列表页不一致。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#419]
页面地址：http://hy.best-ad.cn/#/page/entrancepage

重现路径：慧眼-页面分析-入口页面-指标概览-最近30天

问题描述：访客数echart和列表页数据不一致，其它指标未出现该情况。访客数、访问次数、浏览量的百分比计算也有误差。
PS：IP数的echart表格折线图数据有误，饼状图不能显示。

![f](https://cloud.githubusercontent.com/assets/14328394/10359938/721236ee-6dcf-11e5-83f7-57549f66b6a1.jpg)
![g](https://cloud.githubusercontent.com/assets/14328394/10359939/723b688e-6dcf-11e5-9f08-630b3025bc37.jpg)
![h](https://cloud.githubusercontent.com/assets/14328394/10360120/e419c10c-6dd0-11e5-97cb-56c2684fb2ca.jpg)

**Comment by TomDing729** [comment]
```
 访客数echart和列表页数据不一致，其它指标未出现该情况。访客数、访问次数、浏览量的百分比计算也有误差。   上述问题由，重复访客因素引起。  列如：同样的客户的，在 两天内分别进行了访问，按天来统计时为两个客户，按周期统计时为一个客户。 
```
