### ISSUE TITLE
[图表] 数据展示-柱状图-平均分布指标

### ISSUE THREAD

**Issue by zerocoolys** [zerocoolys/sshuiyan#42]
指标靠得太紧密了..

**Comment by zerocoolys** [comment]
![image](https://cloud.githubusercontent.com/assets/2757581/7746729/5e9c92cc-ffe7-11e4-85d1-94c16a72af18.png)

**Comment by xiaoweiqb** [comment]
先解决其他bug，这个优化放后

**Comment by xiaoweiqb** [comment]
无意中解决了！！！
