### ISSUE TITLE
数据问题 页面分析入口页面流量分析 贡献浏览量数据有误。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#420]
页面地址：http://hy.best-ad.cn/#/page/entrancepage_fa

重现路径：慧眼-页面分析-入口页面-流量分析（转化分析）

问题描述：页面分析入口页面流量分析 列表页贡献浏览量数据和访问数据一模一样，但列表浏览量数据和折线图数据并不一致，怀疑是浏览量数据拷贝的访问数据。
ps：页面url查看历史趋势中，浏览量数据也和访问数据一致。
转化分析也存在该问题。
![i](https://cloud.githubusercontent.com/assets/14328394/10361124/a249dd5e-6dd8-11e5-8628-b131926d08f4.jpg)

**Comment by TomDing729** [comment]
客数echart和列表页数据不一致，其它指标未出现该情况。访客数、访问次数、浏览量的百分比计算也有误差。
   上述问题由，重复访客因素引起。  列如：同样的客户的，在 两天内分别进行了访问，按天来统计时为两个客户，按周期统计时为一个客户。
