### ISSUE TITLE
数据问题 页面分析入口页面新访客分析 列表页访客数与折线图数据不一致，且新访客比率出现大于100%。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#422]
页面地址：http://hy.best-ad.cn/#/page/entrancepage_nv

重现路径：慧眼-页面分析-入口页面-新访客分析

问题描述：新访客分析列表页访客数与折线图数据不一致（列表页数据小于折线图数据），且新访客比率出现大于100%。贡献浏览量列表页数据和折线图数据也不一致。
PS：吸引力分析和转化分析中，贡献浏览量数据和折线图数据也不一致。
![j](https://cloud.githubusercontent.com/assets/14328394/10362308/6d201352-6de0-11e5-8642-7c3282741530.jpg)

**Comment by wangjing1230** [comment]
@TomDing729 回归没有解决。
图片一直上传失败，见后。

**Comment by wangjing1230** [comment]
![1](https://cloud.githubusercontent.com/assets/14328394/10867032/be2c93c4-8087-11e5-857c-4285d8f737ed.jpg)
![2](https://cloud.githubusercontent.com/assets/14328394/10867031/be2c0ca6-8087-11e5-9e35-f566824a5398.jpg)

**Comment by TomDing729** [comment]
新访客分析列表页访客数与折线图数据不一致（列表页数据小于折线图数据）。
上述问题由，重复访客因素引起。 列如：同样的客户的，在 两天内分别进行了访问，按天来统计时为两个客户，按周期统计时为一个客户。
