### ISSUE TITLE
搜索词-列表指标排序无效

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#423]
![source_searchsort](https://cloud.githubusercontent.com/assets/11189612/10363041/a20fe692-6de4-11e5-854a-e58b8dd9e72d.jpg)

**Comment by sgWeiMinSheng** [comment]
排序是按照字符串顺序来的。悲剧

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10604324/36bf821e-7756-11e5-8bc5-ca746abcb2ae.png)
![image](https://cloud.githubusercontent.com/assets/10495048/10604326/3a6aa3c6-7756-11e5-9d45-08555ef89bf5.png)
