### ISSUE TITLE
功能重复 页面分析受访页面 高级筛选搜索引擎功能重复

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#425]
页面地址：http://hy.best-ad.cn/#/page/indexoverview

重现路径：慧眼-页面分析-受访页面-指标概览-高级筛选

问题描述：外部的百度、Google筛选功能和搜索引擎筛选重复。
受访页面-页面价值分析、访客分析-访客地图，也存在该问题。

![c](https://cloud.githubusercontent.com/assets/14328394/10390513/b04c4350-6eab-11e5-9cbd-d7f22b24a297.jpg)
![d](https://cloud.githubusercontent.com/assets/14328394/10390514/b092e850-6eab-11e5-955e-662de1a8db47.jpg)

**Comment by guochunyan** [comment]
@wangjing1230 右侧是一个快速条件筛选

**Comment by zerocoolys** [comment]
@wangjing1230 这个不是bug哈，类似快捷方式

**Comment by wangjing1230** [comment]
好的，收到。
