### ISSUE TITLE
平均访问时长汇总计算错误

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#426]
我梳理下计算公式
平均访问时长(当页的即列表中的行数据) = 对当前页面的每个访客的访问时间进行累计 / 访问次数
平均访问时长(当页汇总的) = (对当前页面的每个访客的访问时间进行累计的累加) / (有平均访问时长的对应的访问次数的累加)
如下图
当页汇总的平均访问时长等于
(5秒这一条的访问时间和 + 243秒这一条的访问时间和 + 3秒这一条的访问时间和 + 1秒这一条的访问时间和 + 9秒这一条的访问时间和) / (2 + 2 + 3 + 4 + 4)
![avgtimeerror](https://cloud.githubusercontent.com/assets/11189612/10422849/9ff5b5d8-70f2-11e5-959f-056066686301.jpg)

**Comment by zerocoolys** [comment]
请参考正确的计算方式，
另外如果遇到为0值的数据，请显示『-』

**Comment by sgWeiMinSheng** [comment]
应该是每条数据的平均访问时长之和除以有几条数据吧

**Comment by wangjing1230** [comment]
平均访问时长有个四舍五入的过程，加起来误差很大噢

**Comment by icepros** [comment]
平均访问时长本身就有一个四舍五入  你这样加起来再来一个平均  到时候误差更大
