### ISSUE TITLE
今日统计-列表汇总和统计指标数据不一致

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#429]
![trend_today_count](https://cloud.githubusercontent.com/assets/11189612/10425543/0b9596ba-710b-11e5-9e3c-8d5355da1290.png)
![trend_today_listcount](https://cloud.githubusercontent.com/assets/11189612/10425547/12ca3684-710b-11e5-8d35-dea5f557f872.png)

**Comment by sgWeiMinSheng** [comment]
列表和统计这个。列表是按照时间段统计出 的数据，上面统计是按照一天来计算的数据，有一些重复的数据就不会计算。每个时间段之间有交集的。不同应该是正常的。
