### ISSUE TITLE
[图标] 日历选择时间与数据显示时间不一致

### ISSUE THREAD

**Issue by zerocoolys** [zerocoolys/sshuiyan#43]

**Comment by zerocoolys** [comment]
![image](https://cloud.githubusercontent.com/assets/2757581/7763124/f6a3a42a-006e-11e5-9a11-a5c4dc0aea38.png)

日历上显示4月23日, 但是数据有4月22日

**Comment by xiaoweiqb** [comment]
你是点了自定义时间后，然后再点的近30天
