### ISSUE TITLE
今日统计-高级筛选，来源过滤选中搜索引擎后点击google再在右侧点击百度会覆盖下拉选项中的google

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#432]
google覆盖百度同理
![trend_todaysource](https://cloud.githubusercontent.com/assets/11189612/10447195/1c49d700-71b5-11e5-8762-2f3e96241eb5.png)

**Comment by zymin** [comment]
这个bug和#431是一样的问题，已经解决
