### ISSUE TITLE
今日统计，按指定时间对比，图例无数据，且按日显示后列表未变动任然按时显示

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#433]
变化率显示，如果下面的数据为0，那么变化率也应该是0  显示为  '--'
昨日统计存在同上问题
![trend_todaycontrast](https://cloud.githubusercontent.com/assets/11189612/10447607/7c2eeb94-71b8-11e5-9c79-74de10767ea7.png)
![trend_todaytotime](https://cloud.githubusercontent.com/assets/11189612/10447637/b5535086-71b8-11e5-84d7-20a5022469d5.png)

**Comment by icepros** [comment]
这也是个BUG
![trend_30](https://cloud.githubusercontent.com/assets/11189612/10448731/4b34fafc-71c1-11e5-8d33-4688025cdfd9.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10754792/f77b9cd0-7cd4-11e5-91e0-e80013391711.png)
![image](https://cloud.githubusercontent.com/assets/10495048/10754793/fa9bc49e-7cd4-11e5-8bd0-fd3f60275fff.png)

**Comment by icepros** [comment]
echarts 图例无数据
![trend_today](https://cloud.githubusercontent.com/assets/11189612/10779047/c6ac3258-7d66-11e5-8d93-daa56c9d2f54.png)

**Comment by icepros** [comment]
显示也有问题

**Comment by icepros** [comment]
显示的应该是指标吧  不是日期  
只要鼠标悬浮在图例上悬浮框显示  日期吧

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10783347/1cc8b4a6-7d92-11e5-894e-a5de37c8b1a3.png)
