### ISSUE TITLE
全部来源-搜索引擎，外部连接，点击扩展项后台返回数据UI未显示

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#438]
![source_allcons](https://cloud.githubusercontent.com/assets/11189612/10476365/a86f481c-727f-11e5-8151-c5ffb543dac9.png)

![source_allcons3](https://cloud.githubusercontent.com/assets/11189612/10476504/0a7c09a4-7281-11e5-9ade-9cec10aa1471.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10511059/503560ba-7369-11e5-886e-1c3a8d56ac9d.png)
