### ISSUE TITLE
全部来源-指定时间数据对比，按来源网站显示报错

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#439]
切换按来源类型，按来源网站会清除右侧的对比时间导致切换后无法对比数据
![source_allchange](https://cloud.githubusercontent.com/assets/11189612/10478054/72a20ee6-728d-11e5-84c0-269af10b5244.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10572418/e629930c-767a-11e5-9e7d-13c9b78ee6e9.png)

**Comment by icepros** [comment]
当页汇总的变化率未做
![source_all](https://cloud.githubusercontent.com/assets/11189612/10658924/2bd57e84-78ce-11e5-9370-d44710c346fd.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10686741/c43c3ffc-7999-11e5-8645-18132784bf18.png)
