### ISSUE TITLE
数据计算错误  变化情况百分比计算错误。乘以100%只添加了%，小数点没有前进两位。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#440]
页面地址：http://192.168.100.10:8000/#/source/changelist

重现路径：慧眼-来源分析-来源变化榜

问题描述：变化情况百分比计算错误。乘以100%只添加了%，小数点没有前进两位。

![1](https://cloud.githubusercontent.com/assets/14328394/10480304/119dd616-729c-11e5-82c9-c5e0dd7c2b19.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10503923/835b04f4-732d-11e5-912b-a30172fe629c.png)
