### ISSUE TITLE
样式问题  变化情况在summary和当页汇总中无颜色样式。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#442]
页面地址：http://192.168.100.10:8000/#/source/changelist

重现路径：慧眼-来源分析-来源变化榜

问题描述：变化情况在summary和当页汇总中无颜色样式。
![3](https://cloud.githubusercontent.com/assets/14328394/10480607/be1a37bc-729d-11e5-8afd-1df82da14cd9.jpg)

**Comment by wangjing1230** [comment]
@zymin 变化情况在summary中颜色被覆盖，看不到。可以取消summary中的颜色。当页汇总 “升”状态颜色为蓝色，应为红色，蓝色为平状态的颜色。
![1](https://cloud.githubusercontent.com/assets/14328394/10595849/d30d4ea4-770f-11e5-98f3-e3c8fa3275c8.jpg)
![1 1](https://cloud.githubusercontent.com/assets/14328394/10595882/435230ee-7710-11e5-80a7-b3fe804d2869.jpg)

**Comment by wangjing1230** [comment]
当页汇总 “全部”状态如果值为正，颜色也应为红色，蓝色为平状态（0）的颜色。
![1 2](https://cloud.githubusercontent.com/assets/14328394/10595957/1370f0e4-7711-11e5-951a-728127f1f2b7.jpg)

**Comment by wangjing1230** [comment]
@zymin 当页汇总平状态的0，现在显示为红色，应为蓝色。

![1](https://cloud.githubusercontent.com/assets/14328394/10626101/567d8f00-77de-11e5-90d0-284dc17b76f9.jpg)

**Comment by wangjing1230** [comment]
@zymin 在内网测试时，发现当对比日期数据均为0时，当页汇总0显示为红色。
![8](https://cloud.githubusercontent.com/assets/14328394/10660472/d79c820c-78d9-11e5-9282-c1f45755e0f1.jpg)

**Comment by zymin** [comment]
![image](https://cloud.githubusercontent.com/assets/8341699/10689101/5af8a42e-79ab-11e5-829a-190735fc3060.png)
