### ISSUE TITLE
功能不能实现 发送报告动作完成，但在当天设置时间，邮箱并未收到邮件。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#444]
页面地址：http://192.168.100.10:8000/#/source/changelist

重现路径：慧眼-来源分析-来源变化榜

问题描述：发送报告动作完成，但在当天设置时间，邮箱并未受到邮件。后期能否受到，待补充。

**Comment by wangjing1230** [comment]
邮件已能收到，但是收到的是txt格式的报告，不是常用的excel。
![d](https://cloud.githubusercontent.com/assets/14328394/10532408/9012a206-73f0-11e5-9ff4-2f4ab0ad6cee.jpg)
![e](https://cloud.githubusercontent.com/assets/14328394/10532409/90142158-73f0-11e5-935c-779fc19d71a4.jpg)

**Comment by wangjing1230** [comment]
设置了一次发送，邮箱会收到多份发送报告。

![f](https://cloud.githubusercontent.com/assets/14328394/10532539/043c6760-73f2-11e5-81dc-caffab810e99.jpg)

**Comment by wangjing1230** [comment]
回归再测，没有收到报告邮件。

**Comment by wangjing1230** [comment]
@sgWeiMinSheng 我重新打开了噢

**Comment by xiaoweiqb** [comment]
这个应该是魏民升再弄了，我没做这个变化榜的邮件发送

在 2015年10月16日 10:28, 汪静 写道:

**Comment by wangjing1230** [comment]
@sgWeiMinSheng 外网测试不能收到邮件。

**Comment by wangjing1230** [comment]
@sgWeiMinSheng 外网今天收到了邮件，但时间有延后，设置的是10:35发送，在10:55收到报告。延后20分钟左右，因为共发送了三次。
![3](https://cloud.githubusercontent.com/assets/14328394/10656033/3b42f8d6-78ad-11e5-9e94-d58dcf792ba1.jpg)
