### ISSUE TITLE
样式问题 确定按钮一直为选中效果。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#445]
页面地址：http://192.168.100.10:8000/#/source/changelist

重现路径：慧眼-来源分析-来源变化榜

问题描述：确定按钮一直为选中效果。正确情况应为：在定义对比日期后，确定键呈未选中效果，点击确定后，确定按钮呈选中效果，汇总和table显示查询日期的数据。（默认今天与昨天对比时，确定键为选中效果，汇总和table显示今天与昨天的数据。）

![7](https://cloud.githubusercontent.com/assets/14328394/10502819/a68d1a80-7322-11e5-825d-cbda42df6d27.jpg)

**Comment by zymin** [comment]
@wangjing1230 @guochunyan 确定按钮未选中的时候样式是什么？确定按钮难道不是一直都是一种状态么？和高级搜索下面的确定按钮一样？

**Comment by guochunyan** [comment]
@zymin 没有点击的时候
![qq 20151019114601](https://cloud.githubusercontent.com/assets/11551612/10569311/d9ca3496-7656-11e5-82e4-b105d8ab75d1.png)，点击之后再加current

**Comment by wangjing1230** [comment]
对的，对的，就是这个意思。有个状态的区分。

**Comment by zymin** [comment]
ok
