### ISSUE TITLE
计算问题 当table第二列数据均为0时，变化情况当页汇总计算错误，显示为Infinity%。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#447]
页面地址：http://192.168.100.10:8000/#/source/changelist

重现路径：慧眼-来源分析-来源变化榜

问题描述：当table第二列数据均为0时（目前发现的规律），变化情况当页汇总计算错误，显示为Infinity%。
![4](https://cloud.githubusercontent.com/assets/14328394/10503031/b89a2d56-7324-11e5-8259-dcd63f348847.jpg)
![5](https://cloud.githubusercontent.com/assets/14328394/10503033/b89da6e8-7324-11e5-81a6-89534e15f8bb.jpg)
![6](https://cloud.githubusercontent.com/assets/14328394/10503032/b89d7bdc-7324-11e5-8425-a4a091a12ca9.jpg)
![9](https://cloud.githubusercontent.com/assets/14328394/10503111/70fcdfe2-7325-11e5-86ad-ac3290b9426e.jpg)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10504223/a331fa6e-7330-11e5-819c-ba014dc006b1.png)
