### ISSUE TITLE
网站统计设置-子目录管理，点击保存报错，且无效

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#452]
![config_sonsave](https://cloud.githubusercontent.com/assets/11189612/10533290/c5e7be26-73f9-11e5-95c3-75dd96f93f5e.png)

**Comment by iammybest** [comment]
问题确认，URL后面带参数了 & 符号导致 请求参数不能正确解析

**Comment by icepros** [comment]
http://tuan.zhiuxing.com:9999/?view=10
这种是可以添加的

**Comment by icepros** [comment]
要分析的页面和目录
