### ISSUE TITLE
功能不能实现 刷新、发送、下载三个按钮功能均不能实现。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#459]
页面地址：http://192.168.100.10:8000/#/group_analysis/sameGroupAnalysis

重现路径：慧眼-同类群组分析

问题描述：刷新、发送、下载三个按钮功能均不能实现。
![5](https://cloud.githubusercontent.com/assets/14328394/10568960/c78e3520-7651-11e5-8613-c6453143ba18.jpg)

**Comment by TomDing729** [comment]
刚和北京同事确认，该功能算新增需求。

**Comment by wangjing1230** [comment]
来源变化分析也有这几个功能，魏民生修复过，不晓得对亲来说有没参考价值。

**Comment by wangjing1230** [comment]
@TomDing729 
发送功能，留存率样式有误，%显示为了*。
下载PDF，报错，不能实现。

**Comment by wangjing1230** [comment]
![5](https://cloud.githubusercontent.com/assets/14328394/10900284/cf8d7f6a-8218-11e5-800b-5251b3e6d5f0.jpg)

**Comment by wangjing1230** [comment]
抱歉，另一张截图一直上传失败。
