### ISSUE TITLE
计算问题  table颜色判断有误。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#461]
页面地址：http://192.168.100.10:8000/#/group_analysis/sameGroupAnalysis

重现路径：慧眼-同类群组分析

问题描述：table颜色判断有误。根据mrd，计算公式见图片注明。
![10](https://cloud.githubusercontent.com/assets/14328394/10571570/10980b08-7673-11e5-876d-67dca3c41550.png)
![10 1](https://cloud.githubusercontent.com/assets/14328394/10571583/2426167e-7673-11e5-94b5-bd2c9f33eeba.jpg)

**Comment by TomDing729** [comment]
已按照上述要求，进行修复.  等待下个版本，进行回归测试。

**Comment by wangjing1230** [comment]
今天内网更新了，但是168,178的颜色并没变成最浅。
![6](https://cloud.githubusercontent.com/assets/14328394/10602622/03185eea-774c-11e5-8ee9-14cbb17bbc52.jpg)

**Comment by wangjing1230** [comment]
浏览量指标下，颜色计算错误。如图数据，1应该也为最浅色。
![dmc sbnfknq9rds3nmj0 bb](https://cloud.githubusercontent.com/assets/14328394/10811722/fef8ddb2-7e49-11e5-825d-542a9df9c7ca.jpg)

**Comment by zymin** [comment]
@wangjing1230 这个暂时等下解决，我现在看不到这个页面

**Comment by wangjing1230** [comment]
这个需要改样式么？不是公式直接计算出来么？

**Comment by zymin** [comment]
@TomDing729
