### ISSUE TITLE
单选设置-其他输入

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#465]
输入框点击其他可输入
如果点击非其它选项  输入框应该为空
在输入框输入后 单选框自动选中其他
![ad_orido](https://cloud.githubusercontent.com/assets/11189612/10573464/334aa3b8-7682-11e5-9a94-c7f0ffa15ca5.png)

**Comment by zymin** [comment]
@icepros 你这问题有点矛盾哦，点击其他的时候才可以输入，那么非其他则不可以输入，那你最后一个要求：输入内容自动选择其他我怎么可能实现呢？？？请再次确认一下！

**Comment by guochunyan** [comment]
@zymin  请参考页面转化目标-新增页面转化

**Comment by icepros** [comment]
@zymin 可以实现的，百度都是这样的

**Comment by zymin** [comment]
。。。我知道了，已经改了~

**Comment by icepros** [comment]
没选择其他的时候不予提示
![ad_media](https://cloud.githubusercontent.com/assets/11189612/10778066/ca24e222-7d5c-11e5-8394-e74c4406b335.png)
