### ISSUE TITLE
样式问题 当页汇总变化情况统一成数字+百分比

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#469]
页面地址：http://192.168.100.10:8000/#/source/changelist

重现路径：慧眼-来源变化榜

问题描述：当页汇总变化情况上面只写了百分比，和北京确认， 需要统一成数字+百分比。
![11](https://cloud.githubusercontent.com/assets/14328394/10573829/e72063d0-7684-11e5-858f-c1189c35a529.jpg)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10574687/3a26d636-768a-11e5-8f1c-7d6b464f2b8a.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10574700/5514d8e4-768a-11e5-9b89-0636cf703697.png)
