### ISSUE TITLE
关于入口页面的来源分布

### ISSUE THREAD

**Issue by conchz** [zerocoolys/sshuiyan#47]
![qq 20150522112907](https://cloud.githubusercontent.com/assets/9883493/7763588/cbd90882-0075-11e5-8fb4-fbbc1130e634.png)
![qq 20150521190150](https://cloud.githubusercontent.com/assets/9883493/7763591/d1558876-0075-11e5-8996-10c6a7c24ab6.png)
1. 来源类型中, 在搜索引擎占比较大的情况下, 为什么在来源URL没有见到关于搜索引擎的相关链接?
2. 针对某一入口页面, 来源URL是指其referer？
3. 来源URL中的来源次数是指访问次数吗?
4. 当前入口页面的来源URL的带来浏览量是如何计算的？
@zerocoolys  @Gongyufei

**Comment by zerocoolys** [comment]
@Gongyufei 亲, 这个需求请确认一下

**Comment by Gongyufei** [comment]
1，需要再确认告知：）
2，QQ已沟通过
3，不是访问次数
4，浏览量是累积的
