### ISSUE TITLE
数据问题 table数据偶尔会加载失误，当页汇总显示NaN，但彩色汇总有数据。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#470]
页面地址：http://192.168.100.10:8000/#/source/changelist

重现路径：慧眼-来源变化榜

问题描述：table数据偶尔会加载失误，当页汇总显示NaN，但彩色汇总有数据。
无法准确重现，是从其它页面第一次到来源变化榜偶尔才会出现的情况，刷新后数据加载正常，无报错。
![12](https://cloud.githubusercontent.com/assets/14328394/10574937/b40557a6-768b-11e5-8761-39e8987a19ef.jpg)

**Comment by wangjing1230** [comment]
在此页面，点击确定，console报错。
![13](https://cloud.githubusercontent.com/assets/14328394/10575012/365d2030-768c-11e5-803b-e306109f2fbe.jpg)

**Comment by sgWeiMinSheng** [comment]
出现这种情况，可能是由于网络问题表格配置未加载成功。

**Comment by zerocoolys** [comment]
@sgWeiMinSheng 
1. 什么情况下会导致网络问题？查询效率太低？这个是内网的服务器，请核查！
2. 如果发生网络问题，需要增加检测代码避免报错。

**Comment by sgWeiMinSheng** [comment]
@zerocoolys 网络卡的时候，这个已经处理了。内网代码还没有更新

**Comment by wangjing1230** [comment]
@sgWeiMinSheng 外网刚才出现了该情况。
![13](https://cloud.githubusercontent.com/assets/14328394/10633910/9e184700-7820-11e5-9264-ce4b2581f5a2.jpg)

**Comment by wangjing1230** [comment]
@sgWeiMinSheng 从其它页面点回来源变化榜时，出现了该情况。与上个备注不同的地方是第一列有数据，第二列和第三列没有数据才显示的NaN。
![2](https://cloud.githubusercontent.com/assets/14328394/10655583/84098576-78a8-11e5-9b3b-433b5cbb1589.jpg)
