### ISSUE TITLE
其它首页，网站首页，未做

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#471]
![config_suitenodo](https://cloud.githubusercontent.com/assets/11189612/10575288/eb6fd1d8-768d-11e5-9b48-c81089971d34.png)

**Comment by icepros** [comment]
这是单选吧

**Comment by iammybest** [comment]
@guochunyan 这个UI的

**Comment by guochunyan** [comment]
@iammybest  我稍微修改了一下，@icepros 反馈的是未做对应功能
