### ISSUE TITLE
网站列表，列表UI显示

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#473]
这中情况下显示不好看吧
颜色or间距
![config_uisuite](https://cloud.githubusercontent.com/assets/11189612/10575373/765ec524-768e-11e5-882d-a365214f2e83.png)

**Comment by guochunyan** [comment]
@icepros  间距已调整，颜色是设计图上的颜色不做修改！![qq 20151020102909](https://cloud.githubusercontent.com/assets/11551612/10596398/4cdd8770-7716-11e5-81f1-177ebfb1aca6.png)
![qq 20151020102918](https://cloud.githubusercontent.com/assets/11551612/10596397/4cdb1940-7716-11e5-90f2-23934db908da.png)
