### ISSUE TITLE
所有下拉菜单的通病问题

### ISSUE THREAD

**Issue by fangzhenping** [zerocoolys/sshuiyan#48]
所有带有下拉菜单，点击下拉菜单后 值不应该是清空的
![Uploading image.png…]()

**Comment by fangzhenping** [comment]
![image](https://cloud.githubusercontent.com/assets/11955235/7764846/a8c86266-0089-11e5-9109-55e1c4f1938a.png)
![image](https://cloud.githubusercontent.com/assets/11955235/7764849/b4c7d95c-0089-11e5-83c2-9ce86ae7e5f4.png)

**Comment by fangzhenping** [comment]
点击小箭头鼠标应该是小手哦
![image](https://cloud.githubusercontent.com/assets/11955235/7804958/d7fd6354-039c-11e5-8e92-a4129711c5ca.png)
效果可以，但是样式按下面的改
![-2_markman](https://cloud.githubusercontent.com/assets/11955235/7805126/4f7839de-039f-11e5-98b7-024b20c2458a.png)

**Comment by guochunyan** [comment]
![qq 20150526161454](https://cloud.githubusercontent.com/assets/11551612/7808099/4ffa54ea-03c3-11e5-8a35-0c61682c5d9e.png)

**Comment by fangzhenping** [comment]
收到，挺好的
