### ISSUE TITLE
数据问题 同一天的数据 在不同对比状态下，数据不一致。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#482]
页面地址：http://192.168.100.10:8000/#/source/changelist

重现路径：慧眼-来源变化榜

问题描述：同一天的数据 在不同对比状态下，数据不一致。该问题目前只发现在10月19日的数据上。原因未知，等待外网再测试。
![4](https://cloud.githubusercontent.com/assets/14328394/10600835/040c3e54-7740-11e5-8162-4d8b68806dec.png)
![4 1](https://cloud.githubusercontent.com/assets/14328394/10600842/0eca9e3a-7740-11e5-9f4b-06c113aaaad1.jpg)

**Comment by sgWeiMinSheng** [comment]
出现这个问题估计是因为数据本身的问题。。

**Comment by zerocoolys** [comment]
@sgWeiMinSheng 
如果是数据本身的问题，请给出截图来说明。

**Comment by wangjing1230** [comment]
@sgWeiMinSheng 外网也存在类似的问题。
![5 1](https://cloud.githubusercontent.com/assets/14328394/10627166/d3b25910-77e8-11e5-8f7c-2b11c9de3437.jpg)
![5](https://cloud.githubusercontent.com/assets/14328394/10627167/d3b6795a-77e8-11e5-854d-86f44306903a.jpg)

**Comment by wangjing1230** [comment]
@sgWeiMinSheng 外网又发现了一组数据不一致。
![11](https://cloud.githubusercontent.com/assets/14328394/10632277/f544e03e-7815-11e5-9eef-01de118b0b5c.jpg)
![12](https://cloud.githubusercontent.com/assets/14328394/10632278/f5480232-7815-11e5-8da7-ab9d13a27ff2.jpg)
