### ISSUE TITLE
【优化UI】百度推广-推广概况 

### ISSUE THREAD

**Issue by fangzhenping** [zerocoolys/sshuiyan#49]
![-5](https://cloud.githubusercontent.com/assets/11955235/7765204/cea459aa-008d-11e5-9026-a43a81f329f6.jpg)
统一下去掉右上角的 “时间”，指标色块的小方格改为半角 2px，效果如图

**Comment by guochunyan** [comment]
![qq 20150522161629](https://cloud.githubusercontent.com/assets/11551612/7766639/d9c33bac-009d-11e5-9ee8-25ba01c11632.png)

**Comment by fangzhenping** [comment]
方块 改为12px*12px ，跟字一样大
