### ISSUE TITLE
页面转化目标-批量删除未做,展开后无修改删除功能，且展开项页数为静态数据

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#490]
![config_pagelist](https://cloud.githubusercontent.com/assets/11189612/10602944/ffb6cf82-774d-11e5-846b-ba256215bd11.png)

**Comment by iammybest** [comment]
@guochunyan 这个批量删除UI去掉和别的一样 页码不需要@icepros 只有第一级才有删除功能的

**Comment by guochunyan** [comment]
@iammybest  按照需求这一项不能删除！！

**Comment by iammybest** [comment]
@guochunyan 那把管理设置里面UI缺少这个的恢复下吧

**Comment by iammybest** [comment]
@guochunyan 我稍后添加批量删除方法

**Comment by guochunyan** [comment]
@iammybest 网站管理首页没有这个需求，只有事件转化目标、页面转化目标，指定广告跟踪有这个功能！

**Comment by iammybest** [comment]
该页面已经修改为不展开2级情况
