### ISSUE TITLE
页面转化新增页，插入订单号会覆盖输入的网页

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#492]
![config_pageins](https://cloud.githubusercontent.com/assets/11189612/10603474/bf33e99c-7750-11e5-9b04-d44d2481a37a.png)

**Comment by icepros** [comment]
![cfg_ins](https://cloud.githubusercontent.com/assets/11189612/10879245/c509b3b4-818d-11e5-8c73-85c0611f47b0.png)

**Comment by icepros** [comment]
插入订单号没有实现

**Comment by iammybest** [comment]
请重新核对 是否选择在 订单转化上
