### ISSUE TITLE
事件转化目标-未对事件预览目标URL进行验证，且进入预览后未进行事件获取

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#494]
事件预览目标URL只能是本站或跨域内的URL
![config_list](https://cloud.githubusercontent.com/assets/11189612/10626755/a7306d7c-77e4-11e5-8805-c729d68253c3.png)
![config_eventtar](https://cloud.githubusercontent.com/assets/11189612/10626773/c8612662-77e4-11e5-89d3-ed8fa7794197.png)

**Comment by icepros** [comment]
![cofg](https://cloud.githubusercontent.com/assets/11189612/10879192/73969718-818d-11e5-8f34-5ae7b5ee85dd.png)

**Comment by iammybest** [comment]
![qq 20151103192616](https://cloud.githubusercontent.com/assets/6211919/10906963/e7a5b4a8-8260-11e5-890b-317d10383409.png)

**Comment by icepros** [comment]
不加 http 报错
