### ISSUE TITLE
统计问题 不能统计到移动端的访问数据。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#499]
页面地址：http://hy.best-ad.cn/#/source/changelist

重现路径：慧眼-来源变化榜

问题描述：不能统计到移动端的访问数据。mrd上有具体需求，见图片。
![7](https://cloud.githubusercontent.com/assets/14328394/10629013/c9e09694-77fd-11e5-9522-e7ac1ce63f02.jpg)

**Comment by sgWeiMinSheng** [comment]
如果es里面有dm为移动端的数据，就会计算出来吧

**Comment by wangjing1230** [comment]
我今天用手机访问，试过了的。

**Comment by zerocoolys** [comment]
@wangjing1230 外网测试的吗？另外你可以通过改变浏览器agent来模拟移动端
![image](https://cloud.githubusercontent.com/assets/2757581/10632436/1022677c-7817-11e5-9cda-d81b8e30523f.png)

@sgWeiMinSheng 你查一下es里面是否有对应的记录

**Comment by wangjing1230** [comment]
好的，我学习下噢。

**Comment by sgWeiMinSheng** [comment]
@wangjing1230 域名是一个嘛。用移动端和网页都是访问的那一个域名

**Comment by wangjing1230** [comment]
@sgWeiMinSheng 需求上说的移动端和网页分开统计的嘛，而且通过移动端访问了，数据都没有变化。
