### ISSUE TITLE
慧眼涉及到到时间展示的问题

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#5]
慧眼涉及到到时间展示的问题：
今天、昨天、最近7天，可选择 按时、按日；（按周、按月等不可选的展示范围，为灰色不可选）
同样，最近30天，可选择 按时、按日、按周 （按月 为灰色不可选）
自选时间段同上。
![image](https://cloud.githubusercontent.com/assets/12438962/7627439/da721140-fa49-11e4-91ad-704f0c56158a.png)

**Comment by Gongyufei** [comment]
1.不能同时出现两个时间条件
2，选择 按周 ，没有展现出来
2，按自然月，最近30天 应可选择 按月
![image](https://cloud.githubusercontent.com/assets/12438962/7664442/1c72217c-fbba-11e4-9a8c-670c9d38b302.png)

**Comment by Gongyufei** [comment]
![image](https://cloud.githubusercontent.com/assets/12438962/7720089/c23aecd0-fefb-11e4-92c3-dbc534d895ea.png)

**Comment by Gongyufei** [comment]
按周没有出来（而且，选择按周，按日 不应该为 蓝色

![image](https://cloud.githubusercontent.com/assets/12438962/7740140/52f4c4e6-ff9f-11e4-8989-473152fbc22b.png)

**Comment by Gongyufei** [comment]
最近30天，是从今天算起的最近30天
请标出按周展现 的时间段

**Comment by xiaoweiqb** [comment]
近30天要包括今天么？

**Comment by Gongyufei** [comment]
包括今天

**Comment by xiaoweiqb** [comment]
呃、。。。

**Comment by Gongyufei** [comment]
用 时间段 展示周
![image](https://cloud.githubusercontent.com/assets/12438962/7792876/a886066a-02ea-11e5-90e2-d4ffab45d5e4.png)
例：
![image](https://cloud.githubusercontent.com/assets/12438962/7792888/c261e0c2-02ea-11e5-8b0d-708677089d74.png)

**Comment by zerocoolys** [comment]
@Gongyufei @xiaoweiqb 新创建issue #63 . 当前issue关闭.
