### ISSUE TITLE
时长转化-时长和页数可输入非数值

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#500]
![config_timeconvert](https://cloud.githubusercontent.com/assets/11189612/10629410/2e56d46e-7801-11e5-91bb-408a02e2a4c2.png)

**Comment by guochunyan** [comment]
![Uploading QQ截图20151021152717.png…]()提issuse前已进行修改并提交

**Comment by guochunyan** [comment]
![qq 20151021153005](https://cloud.githubusercontent.com/assets/11551612/10630410/d748668a-7808-11e5-9ff2-ad2941128553.png)
