### ISSUE TITLE
功能问题 默认排序不是A列数据由高到低。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#503]
页面地址：http://hy.best-ad.cn/#/source/changelist

重现路径：慧眼-来源变化榜

问题描述：默认排序不是A列数据由高到低。内网测试环境该功能点正常。
![9](https://cloud.githubusercontent.com/assets/14328394/10631538/40f78892-7811-11e5-8790-2a1142ff8d73.jpg)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10632323/59a7bd58-7816-11e5-9b87-01ec16374ac4.png)
