### ISSUE TITLE
退出登陆报错 账号切换退出登陆时，报错。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#505]
页面地址：http://sem.best-ad.cn/login?url=hy.best-ad.cn

重现路径：慧眼-登陆-退出登陆

问题描述：退出登陆均报错。
![qq 20151022140107](https://cloud.githubusercontent.com/assets/14328394/10658019/64b834c0-78c5-11e5-8eef-d4ff829c421b.png)
因为不属于哪个模块，找不到负责的开发，所以先@的张哥哥，张哥哥后面再分配噢。

**Comment by zhanghr** [comment]
经测试在chrome浏览器上会出现这个问题

**Comment by zerocoolys** [comment]
@zhanghr @wangjing1230 
console里面报错的原因如下
![image](https://cloud.githubusercontent.com/assets/2757581/10862384/7260d056-7fe0-11e5-8b23-b41e4e08719f.png)

这里是把返回值作为一个 script文件执行

实际上返回值一张图片
![image](https://cloud.githubusercontent.com/assets/2757581/10862389/a79f5e68-7fe0-11e5-8d43-7f26d0a50ee1.png)

![image](https://cloud.githubusercontent.com/assets/2757581/10862392/b6d081e6-7fe0-11e5-914f-5eed1250985b.png)

这个不属于bug问题，所以关闭issue
