### ISSUE TITLE
来源变化榜

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#510]
百分比表现形式请修改，谢谢！
1，数值/数值×100%，第一个表现为600%
2，数值/0的百分比统一表现为（-）

![image](https://cloud.githubusercontent.com/assets/12438962/10661630/e75591b8-78e1-11e5-998e-317cc42d7a7c.png)

**Comment by wangjing1230** [comment]
@Gongyufei 这个bug9天前已经提交，并且修复了，bug号#440。
PS：来源变化榜的开发是魏民生，丁伟是同类群组分析。2f是在哪个网址测的呢？内网测试网址是：http://192.168.100.10:8000   外网是hy.best-ad.cn。有关来源变化榜的bug可以在issue上面查看，属于来源分析板块，我提交的，时间范围是9天前到今天，部分bug回归没有问题后，已经关闭，在close里面可以查看。
目前来源变化榜测试和bug修复基本完成，今天回归测试。

**Comment by TomDing729** [comment]
那这个问题，可以关闭了否？
