### ISSUE TITLE
【优化UI】首页中搜索词模块，修改如图

### ISSUE THREAD

**Issue by fangzhenping** [zerocoolys/sshuiyan#52]
http://182.92.227.79:8000/#/index

![image](https://cloud.githubusercontent.com/assets/11955235/7770736/3f9e0f94-00c4-11e5-867e-4ecb49a30af1.png)

**Comment by guochunyan** [comment]
![qq 20150522212414](https://cloud.githubusercontent.com/assets/11551612/7771281/d06ab94c-00c8-11e5-8f8d-05f6298fe22b.png)

**Comment by fangzhenping** [comment]
怎么居中了呢
![image](https://cloud.githubusercontent.com/assets/11955235/7804904/3f2f18e8-039c-11e5-8d30-6b811469b0e5.png)

**Comment by guochunyan** [comment]
![2](https://cloud.githubusercontent.com/assets/11551612/7808125/8429ebcc-03c3-11e5-86df-43b1de76a99d.png)

**Comment by fangzhenping** [comment]
ok
