### ISSUE TITLE
ui少了转化指标，基础指标少了转化次数，转化率

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#523]
![ad_quito](https://cloud.githubusercontent.com/assets/11189612/10781444/0f66d6ae-7d82-11e5-9128-5140873117c6.png)

**Comment by icepros** [comment]
来源，媒介，计划，关键词，创意每个页面都少了这些

**Comment by zymin** [comment]
@icepros 有没有默认选中的？

**Comment by icepros** [comment]
默认指标：浏览量（PV），访客数，IP数，跳出率，平均访问时长

**Comment by icepros** [comment]
![ad_convertp](https://cloud.githubusercontent.com/assets/11189612/10837253/14ce3b7a-7ef2-11e5-84c7-19baa8fcb7b2.png)
