### ISSUE TITLE
页面报错 点击百度推广页面报错。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#526]
页面地址：http://hy.best-ad.cn/#/extension/survey

重现路径：慧眼-百度推广

问题描述：百度推广点击报错（tuser登陆状态一点击百度推广就会报错，perfect2015点击网盟推广时，才报错）。
![1](https://cloud.githubusercontent.com/assets/14328394/10808578/091a0d60-7e28-11e5-98a3-09edf9a5a43b.jpg)
![2](https://cloud.githubusercontent.com/assets/14328394/10808585/1df54344-7e28-11e5-8e39-33d10b4f4b27.jpg)

**Comment by sgWeiMinSheng** [comment]
@wangjing1230 报错的原因是因为sem账户没有对应的百度账户。请求链接出错，
