### ISSUE TITLE
页面和需求设计稿不一致  事件转化目标预览页部分功能缺失。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#527]
页面地址：http://hy.best-ad.cn/#/conf/webcountsite/eventchange

重现路径：慧眼-管理设置-事件转化目标

问题描述：设计稿和需求文档均有按照生成日期时间进行排序的功能，而目前页面没有该功能。目前页面还缺失事件预览页面列，设置和取消字段也有相应的变化，见设计稿。
![5](https://cloud.githubusercontent.com/assets/14328394/10812155/53712d50-7e4e-11e5-8ee7-605415626def.jpg)
![6](https://cloud.githubusercontent.com/assets/14328394/10812156/539d9ff2-7e4e-11e5-8434-8bf3aeecc2d8.jpg)

**Comment by iammybest** [comment]
未影响到功能 暂不修改 4号版本后修改

**Comment by iammybest** [comment]
已修改

**Comment by wangjing1230** [comment]
@iammybest 按生成日期排序功能未实现。
![31](https://cloud.githubusercontent.com/assets/14328394/10988716/f01809fe-8479-11e5-8023-f1adbb366f31.jpg)

**Comment by iammybest** [comment]
已经添加 下个版本测试

**Comment by wangjing1230** [comment]
@iammybest 问题仍然存在
![3](https://cloud.githubusercontent.com/assets/14328394/11024469/ba2d423a-86c9-11e5-8d26-d8c275672bce.jpg)
