### ISSUE TITLE
功能问题 批量删除network显示已成功删除，但页面还有数据，刷新后删除数据才没有显示。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#528]
页面地址：http://hy.best-ad.cn/#/conf/webcountsite/eventchange

重现路径：慧眼-管理设置-事件转化目标

问题描述：批量删除network显示已成功删除，但页面还有数据，刷新后删除数据才没有显示。
![7](https://cloud.githubusercontent.com/assets/14328394/10812401/b8636bcc-7e50-11e5-9ccb-eec7c235d119.jpg)
![9](https://cloud.githubusercontent.com/assets/14328394/10812402/b86c3a04-7e50-11e5-84f3-61f35f2accc8.jpg)

**Comment by iammybest** [comment]
@guochunyan 去掉批量删除功能
