### ISSUE TITLE
样式问题 下拉框分页功能，样式错位。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#529]
页面地址：http://hy.best-ad.cn/#/conf/webcountsite/eventchange

重现路径：慧眼-管理设置-事件转化目标

问题描述：下拉框分页功能，样式错位。
![8](https://cloud.githubusercontent.com/assets/14328394/10812602/d888ef56-7e52-11e5-8426-386cd9facde1.jpg)

**Comment by iammybest** [comment]
@guochunyan  请和对象下样式问题，如果是后台配置问题@我
