### ISSUE TITLE
【追UI】百度推广——推广概况

### ISSUE THREAD

**Issue by fangzhenping** [zerocoolys/sshuiyan#53]
http://182.92.227.79:8000/#/extension/survey
![image](https://cloud.githubusercontent.com/assets/11955235/7771105/89b77f40-00c7-11e5-8d2a-897a0dfd3cd0.png)
页面优化如下图
![image](https://cloud.githubusercontent.com/assets/11955235/7771120/ababd4b6-00c7-11e5-9c3e-9d6d240d8df8.png)

**Comment by zymin** [comment]
已解决
