### ISSUE TITLE
推广方式-指标说明，未详细显示

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#530]
![tg_what](https://cloud.githubusercontent.com/assets/11189612/10812976/3d08dc04-7e56-11e5-9ba8-9fa0fa742c12.png)

**Comment by icepros** [comment]
![tg_tp](https://cloud.githubusercontent.com/assets/11189612/10879010/56f8d266-818c-11e5-966e-3204f99b6efd.png)

**Comment by icepros** [comment]
![tg_tp1](https://cloud.githubusercontent.com/assets/11189612/10879031/72077d8c-818c-11e5-85f5-2ee57cd1414c.png)

**Comment by guochunyan** [comment]
@icepros 
![qq 20151103112431](https://cloud.githubusercontent.com/assets/11551612/10900621/5b6ed692-821d-11e5-8682-234f4eb90512.png)部分指标未找到对应解释！

**Comment by icepros** [comment]
事件转化：客户点击您期望触发的事件，并且这个事件被设置为转化目标，那么这样的用户操作就是一次事件转化。

页面转化：如果您认为网站上的某个页面特别重要(如表单提交后出现的“提交成功”页面)，到达了该页面表示访客完成了您的期望，您可以将到达您设定的目标作为一种转化来统计。

事件点击总数：所有事件被触发的总次数，不区分普通事件和事件转化目标。

**Comment by icepros** [comment]
千次展现消费：获得一千次展现机会所付出的推广费用

**Comment by icepros** [comment]
转化：即指潜在客户完成一次您期望的行动。
