### ISSUE TITLE
功能问题 当事件统计处于暂停的状态，访问数据仍然在被统计。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#545]
页面地址：http://hy.best-ad.cn/#/conf/webcountsite/eventchange

重现路径：慧眼-管理设置-事件转化目标

问题描述：当事件统计处于暂停的状态，访问数据仍然在被统计。

![13](https://cloud.githubusercontent.com/assets/14328394/10839094/62d2e02e-7f0a-11e5-85a1-08a3129e391b.jpg)

**Comment by iammybest** [comment]
@wangjing1230 图里标注的取消设置是 事件配置是否为转化，新UI里面的暂停启用才是事件是否统计
目前已经完成。代码稍后提交

**Comment by wangjing1230** [comment]
好的
