### ISSUE TITLE
功能未实现   事件转化、页面转化，时间等查询表头项固定。PS：见需求34页。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#549]
页面地址：http://hy.best-ad.cn/#/transform/transformAnalysis

重现路径：慧眼-转化分析-事件转化

问题描述：事件转化、页面转化，时间等查询表头项固定。PS：见需求34页。
![10](https://cloud.githubusercontent.com/assets/14328394/10839735/6ca37336-7f12-11e5-9622-7ac35b122601.jpg)

**Comment by zerocoolys** [comment]
@guochunyan 
看一下这个功能是否能实现
