### ISSUE TITLE
功能问题 事件转化  当自定义指标确定后，summary显示了两列数据，但前提并没有选择对比日期。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#550]
页面地址：http://hy.best-ad.cn/#/transform/transformAnalysis

重现路径：慧眼-转化分析-事件转化

问题描述：当自定义指标确定后，summary显示了两列数据，但前提并没有选择对比日期。且可以选择0项，未做最低选择项的限制。
![11](https://cloud.githubusercontent.com/assets/14328394/10839808/07bd82c6-7f13-11e5-89ba-1518e77a2a04.jpg)
![12](https://cloud.githubusercontent.com/assets/14328394/10839850/6bf629b4-7f13-11e5-952a-f236318f28f7.jpg)

**Comment by wangjing1230** [comment]
附报错
![20](https://cloud.githubusercontent.com/assets/14328394/10841927/9f3c9ac8-7f28-11e5-9b17-269ca1329ad1.jpg)

**Comment by zerocoolys** [comment]
@iammybest 
这个是跨域问题，你看下是否请求错误

请求地址应该是
hy.best-ad.cn/api 吧
