### ISSUE TITLE
功能问题  table的排序默认是按照表格中第一个指标（从高到低）排序（见需求文档）。目前非此排序。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#553]
页面地址：http://hy.best-ad.cn/#/transform/transformAnalysis

重现路径：慧眼-转化分析-事件转化

问题描述：table的排序默认是按照表格中第一个指标（从高到低）排序。当前默认排序规则未知，发现也不是按照事件转化设置的顺序排序的。
![5](https://cloud.githubusercontent.com/assets/14328394/10840015/73c0401a-7f15-11e5-8b3f-5e196527e168.jpg)

**Comment by iammybest** [comment]
@wangjing1230  这个有文档要求 初始就排序么？

**Comment by wangjing1230** [comment]
@iammybest 文档有具体要求，p36，具体内容见截图，下次遇到这种情况，我会把截图一起贴到issue里，方便你确认哈。
![3](https://cloud.githubusercontent.com/assets/14328394/11735386/8ebf5700-9ffb-11e5-9c6c-8be7313d9dc2.png)
