### ISSUE TITLE
功能不能实现 高级筛选功能均不能实现。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#555]
页面地址：http://hy.best-ad.cn/#/transform/transformAnalysis

重现路径：慧眼-转化分析-事件转化和页面转化

问题描述：高级筛选功能均不能实现。没有根据筛选条件返回值。查询事件动作也不能实现。
![16](https://cloud.githubusercontent.com/assets/14328394/10840137/ddc40a5e-7f16-11e5-829a-a9f5092417f3.jpg)

**Comment by wangjing1230** [comment]
页面转化情况相同。

**Comment by wangjing1230** [comment]
@iammybest 页面转化的筛选功能，没有实现。

**Comment by iammybest** [comment]
@wangjing1230  这个是解决了吧
