### ISSUE TITLE
功能问题 下载和发送功能报错，不能实现。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#558]
页面地址：http://hy.best-ad.cn/#/transform/transformAnalysis

重现路径：慧眼-转化分析-事件转化和页面转化

问题描述：下载和发送功能报错，不能实现。
![6](https://cloud.githubusercontent.com/assets/14328394/10840347/63417dc2-7f19-11e5-9c21-d4b7a4e9906b.jpg)
![7](https://cloud.githubusercontent.com/assets/14328394/10840348/6345c468-7f19-11e5-907d-1d350b86c1d1.jpg)

**Comment by wangjing1230** [comment]
页面转化出现相同情况。

**Comment by wangjing1230** [comment]
@sgWeiMinSheng 发送报告内容有误，不是当前页面内容。
下载CSV，部分指标用的英文缩写。
下载PDF不能实现。
![3](https://cloud.githubusercontent.com/assets/14328394/10900131/069ec4fc-8217-11e5-9b28-4eb81134a42b.jpg)

**Comment by wangjing1230** [comment]
![4](https://cloud.githubusercontent.com/assets/14328394/10900156/6ca73b08-8217-11e5-860e-246ae0dd64b7.jpg)

**Comment by sgWeiMinSheng** [comment]
下载CSV修复

**Comment by sgWeiMinSheng** [comment]
下载PDF修复

**Comment by wangjing1230** [comment]
@sgWeiMinSheng 回归问题没有解决，请确认代码是否更新上了。

**Comment by zerocoolys** [comment]
@sgWeiMinSheng 如果修复的话，附上一个截图，方便测试的同学先确认

**Comment by sgWeiMinSheng** [comment]
@wangjing1230 代码提交了，估计没有部署

**Comment by wangjing1230** [comment]
@sgWeiMinSheng 
下载csv格式中，百分率的*请修复成%。
下载pdf格式中，事件名称用的数字，请换成汉字，如果汉字不能实现，至少数字要有序。
发送，采用的是txt格式，如能采用csv格式更好，不能实现就算了。
![1](https://cloud.githubusercontent.com/assets/14328394/10958718/092e8b30-83ac-11e5-8d2f-c2717dc7f0d5.jpg)
![2](https://cloud.githubusercontent.com/assets/14328394/10958719/092ec9c4-83ac-11e5-9cb2-9909c1a877ef.jpg)

**Comment by wangjing1230** [comment]
@sgWeiMinSheng 百分比符号问题，同类群组修复过，参考请见#624。

**Comment by sgWeiMinSheng** [comment]
@wangjing1230 那个pdf是不支持中文的。。事件名称的中文被截取了。。

**Comment by wangjing1230** [comment]
@sgWeiMinSheng 好的

**Comment by sgWeiMinSheng** [comment]
下载csv格式中，百分率的*请修复成%。解决了
