### ISSUE TITLE
【优化UI】所有单选统一样式

### ISSUE THREAD

**Issue by fangzhenping** [zerocoolys/sshuiyan#56]
![image](https://cloud.githubusercontent.com/assets/11955235/7772643/152dfdec-00d2-11e5-8b27-597e780394e5.png)
![image](https://cloud.githubusercontent.com/assets/11955235/7772421/a54e0ad6-00d0-11e5-894c-4813a51740b3.png)
统一如下图：
![image](https://cloud.githubusercontent.com/assets/11955235/7772425/ab7cf412-00d0-11e5-9af4-3b1490c27835.png)
![image](https://cloud.githubusercontent.com/assets/11955235/7772561/94d18e52-00d1-11e5-9953-1ca62aecb20e.png)

**Comment by fangzhenping** [comment]
![radio](https://cloud.githubusercontent.com/assets/11955235/7772945/cc21b51a-00d3-11e5-9a0a-145f6bcba354.png)

**Comment by guochunyan** [comment]
![qq 20150526161433](https://cloud.githubusercontent.com/assets/11551612/7808141/a8a243be-03c3-11e5-9813-f0e194856b5f.png)

**Comment by fangzhenping** [comment]
挺好的
