### ISSUE TITLE
推广方式-高级筛选-地域过滤所有地域数据一样，点击全部和任何一个地域的数据也一样

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#564]
![tg_typebestarea](https://cloud.githubusercontent.com/assets/11189612/10862164/6166d9a6-7fd8-11e5-8dc7-8bb6ddc80963.png)

**Comment by sgWeiMinSheng** [comment]
@zerocoolys 刚刚问了小白他们，查询的接口数据里面没有地域这个字段，推广方式里面加入地域过滤是为了什么呐
