### ISSUE TITLE
推广方式-echarts图例 消费指标未做保留值处理

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#565]
![tg_typecost](https://cloud.githubusercontent.com/assets/11189612/10862204/ea79a6e6-7fd9-11e5-9f81-d0666069a523.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10873511/bfa4121c-8150-11e5-9838-873f6fb51ef4.png)
