### ISSUE TITLE
[访客地图]第一次进入访客地图页面浏览器console报错

### ISSUE THREAD

**Issue by zerocoolys** [zerocoolys/sshuiyan#568]
错误信息如下:
![image](https://cloud.githubusercontent.com/assets/2757581/10862365/dad30c68-7fdf-11e5-9e8d-85b83903bcd6.png)

**Comment by TomDing729** [comment]
@guochunyan ，请看看这个问题。

**Comment by TomDing729** [comment]
目前去复测的时候没有发现这个报错。
