### ISSUE TITLE
搜索推广-搜索词数据不对

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#573]
![tg_searchsea](https://cloud.githubusercontent.com/assets/11189612/10862603/33b60aa6-7fea-11e5-8730-bfcbd5b0a179.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10936221/6974c99a-8326-11e5-9828-0d74c0001484.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10936243/937a22b2-8326-11e5-9357-3155e708e740.png)

**Comment by icepros** [comment]
昨天筛选 echarts没数据

**Comment by icepros** [comment]
浏览量(PV) 
访问次数 
访客数(UV) 
新访客数 
平均访问页数

统计指标数据不对

**Comment by sgWeiMinSheng** [comment]
和哪里的数据不对？？
