### ISSUE TITLE
搜索推广-推广url-----UI数据未显示

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#575]
![tg_searchurldata](https://cloud.githubusercontent.com/assets/11189612/10862846/626c1804-7ff4-11e5-999c-ffe208b34d07.png)

**Comment by sgWeiMinSheng** [comment]
这个问了舒舒，下面显示的是某个关键词相关的URL信息。查询出来的那个只是关键词的数据，但是该关键词下面没有URL
