### ISSUE TITLE
功能问题  页面转化  收益设置-转化收益，小数点不能识别。字母，字符不能输入，但没有提示。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#580]
页面地址：http://hy.best-ad.cn/#/conf/webcountsite/pagechange

重现路径：慧眼-管理设置-页面转化目标

问题描述：收益设置-转化收益，小数点不能识别。字母，字符不能输入，但没有提示。
![8](https://cloud.githubusercontent.com/assets/14328394/10867456/2ebcf9c4-809e-11e5-9e00-abcef667546c.jpg)

**Comment by iammybest** [comment]
同#581 一起修改了

**Comment by wangjing1230** [comment]
@iammybest 小数点已经能识别，但是删除输入内容后，默认了0，而且不能删除。
重现步骤：
输入12.30
删除
输入框出现0
再输入12.30
0一直存在。
![2](https://cloud.githubusercontent.com/assets/14328394/10899970/3cac88a6-8215-11e5-8bc5-eaf439a8bc5b.jpg)

**Comment by iammybest** [comment]
那默认为空？这个根本就没给有涉及，不是看怎么理解么？
