### ISSUE TITLE
功能完善 页面转化 收益设置-转化率 非法字符，直接不能输入，没有提示。数字能输入三位数。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#581]
页面地址：http://hy.best-ad.cn/#/conf/webcountsite/pagechange

重现路径：慧眼-管理设置-页面转化目标

问题描述：收益设置-转化率 非法字符，直接不能输入，没有提示。数字能输入三位数。
![10](https://cloud.githubusercontent.com/assets/14328394/10867462/7afdcfde-809e-11e5-995b-969b9e67863d.jpg)

**Comment by wangjing1230** [comment]
@iammybest 不在0—100范围内的数字，输入后显示100。
且提示应为红字“请输入1-100之间整数”。请按需求文档实现哈。

重现步骤：
输入300
输入框出现100
再输入30.0
输入框出现100
![2](https://cloud.githubusercontent.com/assets/14328394/10899915/8f47ad4e-8214-11e5-8026-4d838b5294b1.jpg)

**Comment by iammybest** [comment]
那就把非法数字都变成0
