### ISSUE TITLE
功能完善 页面转化  路径类型   步骤没有删除按钮。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#586]
页面地址：http://hy.best-ad.cn/#/conf/webcountsite/pagechange

重现路径：慧眼-管理设置-页面转化目标

问题描述：路径类型   步骤没有删除按钮。
![14](https://cloud.githubusercontent.com/assets/14328394/10867554/531e5902-80a3-11e5-863e-26b6e96e6075.jpg)

**Comment by zymin** [comment]
与#587相同

**Comment by wangjing1230** [comment]
第一个页面后的删除，即删除整个步骤，故问题相同，已解决，关闭问题。
