### ISSUE TITLE
功能缺失 预览页面转化目标 没有按目标生成日期排序功能。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#592]
页面地址：http://hy.best-ad.cn/#/conf/webcountsite/pagechange

重现路径：慧眼-管理设置-页面转化目标

问题描述：预览页面转化目标 没有按目标生成日期排序功能。
![25](https://cloud.githubusercontent.com/assets/14328394/10867627/63d1bf9c-80a7-11e5-9237-c94c2e2bc511.jpg)
![26](https://cloud.githubusercontent.com/assets/14328394/10867628/63dbacc8-80a7-11e5-87da-de483908eef0.jpg)

**Comment by guochunyan** [comment]
@iammybest  页面已加上，请配一下数!
