### ISSUE TITLE
功能缺失 页面转化  没有启用和暂停功能。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#593]
页面地址：http://hy.best-ad.cn/#/conf/webcountsite/pagechange

重现路径：慧眼-管理设置-页面转化目标

问题描述：预览页面转化目标 没有启用和暂停功能。
![25](https://cloud.githubusercontent.com/assets/14328394/10867653/4bd14272-80a8-11e5-87c1-bd582e0c0e01.jpg)
![26](https://cloud.githubusercontent.com/assets/14328394/10867654/4bd47870-80a8-11e5-9d20-212f57406e62.jpg)

**Comment by guochunyan** [comment]
@iammybest  页面已加上暂停使用和重新启用
