### ISSUE TITLE
功能缺失 预览页面转化目标 没有分页功能。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#595]
页面地址：http://hy.best-ad.cn/#/conf/webcountsite/pagechange

重现路径：慧眼-管理设置-页面转化目标

问题描述：预览页面转化目标 没有分页功能。
![19](https://cloud.githubusercontent.com/assets/14328394/10867705/acf3fc04-80ab-11e5-90ba-801ebc097e65.jpg)

**Comment by guochunyan** [comment]
@wangjing1230 @iammybest ，目前是有分页功能， 前期分页@Gongyufei 要求是超过二十条才显示分页！

**Comment by wangjing1230** [comment]
@guochunyan 测试的时候已经添加超过二十条数据。但每页显示只出现了文字，没有选择下拉框。

**Comment by guochunyan** [comment]
@wangjing1230 
![qq 20151103101730](https://cloud.githubusercontent.com/assets/11551612/10899851/f7f3d328-8213-11e5-9efb-12b7a7e01c2c.png)已经好了哦

**Comment by wangjing1230** [comment]
好的哈
