### ISSUE TITLE
新增指定跟踪 管理设置页面

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#597]
URL是唯一的，不应该是关键词多少个就生成多少个url（下面的截图是，我输入了两个关键词，生成了两个url）
![image](https://cloud.githubusercontent.com/assets/12438962/10867728/5b021c80-80ad-11e5-8700-b007c1309eaa.png)

**Comment by icepros** [comment]
@Gongyufei 
功能是这样的哈  输入几个关键词生成几条url
