### ISSUE TITLE
【图表UI】来源分析、页面分析、访客分析中有几处图表线色值需要统一下

### ISSUE THREAD

**Issue by fangzhenping** [zerocoolys/sshuiyan#60]
这个红框出来的灰色 统一成其他灰色竖线 #F0F0F0
![-1](https://cloud.githubusercontent.com/assets/11955235/7792292/977cfc00-02e2-11e5-9a7c-b733c0fcafa3.png)
有以下页面中图表涉及此问题
http://182.92.227.79:8000/#/source/source
http://182.92.227.79:8000/#/source/searchengine
http://182.92.227.79:8000/#/source/externallinks
http://182.92.227.79:8000/#/page/entrancepage
http://182.92.227.79:8000/#/visitor/equipment

**Comment by xiaoweiqb** [comment]
![qq 20150525175242](https://cloud.githubusercontent.com/assets/11550475/7795336/9236de90-0306-11e5-9731-9513bdd69a45.png)

**Comment by xiaoweiqb** [comment]
看到了吗？

**Comment by fangzhenping** [comment]
看到了 谢谢o(∩_∩)o
