### ISSUE TITLE
转化分析-事件转化

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#602]
有几个问题需要帮忙解决，谢谢！
1，产生点击次数的事件&设置为转化目标并有转化次数的事件，需要表格中展现相关数据；
2，新增事件转化中，ID（事件）是唯一的，在一个id上只能建一个事件，不能建重复事件；
3，新增事件转化中，选择一个网页一个ID，不能跳转出去（现在会有跳转）；选择一个事件ID后，点击保存确定后，直接到事件列表页。
4，事件转化列表页，请增加筛选框。

**Comment by Gongyufei** [comment]
请修改一下ui，（这个ui版本应该不是最新的）
![image](https://cloud.githubusercontent.com/assets/12438962/10868474/6963a326-80ca-11e5-9faa-84dd05dec915.png)

**Comment by Gongyufei** [comment]
新增事件转化目标：元素、id等请设置相应规则。
![image](https://cloud.githubusercontent.com/assets/12438962/10868489/c0855960-80ca-11e5-9bcb-fd4040b16dc2.png)

**Comment by zerocoolys** [comment]
@Gongyufei 
相关数据是哪些数据？

**Comment by iammybest** [comment]
@Gongyufei  
1 中  "需要表格中展现相关数据"是什么
2 中  与你们之前提的事件目标名称也要唯一冲突 已修改
3 中  大致确定为浏览器兼容性问题，可否另开个BUG 或者需求 
4 中  是转化分析下-事件转化么？如果是已经完成

**Comment by Gongyufei** [comment]
1，表格中展现的是：产生基础指标数据的事件&设置为转化目标并有转化次数的事件的数据。（清海已线上沟通了
2，ok
3，新增事件转化目标，出现以下问题
![image](https://cloud.githubusercontent.com/assets/12438962/10933821/33c72168-8316-11e5-81a9-ea1cbd7bcfd4.png)

4，ok

**Comment by iammybest** [comment]
1.并未沟通啊，现在擦发现解决中
3.问题已经修改

**Comment by iammybest** [comment]
@Gongyufei 此BUG先关闭 涉及到具体的 请单独提出BUG吧，列表中不方便看是什么问题.谢谢
