### ISSUE TITLE
UI-同类群组分析

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#603]
把“所有会话”-所有访客，谢谢
![image](https://cloud.githubusercontent.com/assets/12438962/10868017/3d024b02-80bb-11e5-9908-101756c0b557.png)

**Comment by TomDing729** [comment]
已修复，已提交代码。  11/2 下午3点发布版本测试。

**Comment by wangjing1230** [comment]
@TomDing729 问题仍然存在，请确认代码是否更新上了。
