### ISSUE TITLE
数据问题 页面转化 今天才配置的页面转化，昨天最近7天最近30天有其它数据。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#604]
页面地址：http://hy.best-ad.cn/#/transform/pageTransform

重现路径：慧眼-转化分析-页面转化

问题描述：今天才配置的页面转化，昨天最近7天最近30天有其它数据。
![1](https://cloud.githubusercontent.com/assets/14328394/10868020/5a7e171a-80bb-11e5-90b3-6fb04417b0ca.jpg)
![2](https://cloud.githubusercontent.com/assets/14328394/10868021/5a84d32a-80bb-11e5-8ad5-1013780abefa.jpg)
![3](https://cloud.githubusercontent.com/assets/14328394/10868022/5a84f526-80bb-11e5-847f-9fddfa883ed2.jpg)

**Comment by zerocoolys** [comment]
@iammybest 应该是你没有传typeid的原因导致的哈

**Comment by zerocoolys** [comment]
@sgWeiMinSheng 麻烦帮忙查一下是否是因为漏掉typeid

**Comment by sgWeiMinSheng** [comment]
@zerocoolys 传递了typeid的。Request URL:http://localhost:8000/api/transform/getDayPagePVs?start=-1&end=-1&type=4ac087da7e10abafa7341647e1a763ae&showType=day&queryOptions=pv,uv&urls=[%22192.168.1.102:3000/index%22]

**Comment by zerocoolys** [comment]
@sgWeiMinSheng 如果传了typeid,后面的查询是否也包括在里面？

**Comment by iammybest** [comment]
这个问题我来解决 是没有传页面转化配置的时间

**Comment by iammybest** [comment]
@zerocoolys @sgWeiMinSheng
