### ISSUE TITLE
功能缺失 页面转化 无转化目标的下拉筛选框。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#607]
页面地址：http://hy.best-ad.cn/#/transform/pageTransform

重现路径：慧眼-转化分析-页面转化

问题描述：页面转化 目前无转化目标的下拉筛选框。需求mrd和设计图上有此需求。

图片一直上传失败见后。

**Comment by wangjing1230** [comment]
![6](https://cloud.githubusercontent.com/assets/14328394/10868102/c2420e9a-80bd-11e5-8200-926e6af655c3.jpg)
![7](https://cloud.githubusercontent.com/assets/14328394/10868103/c2445fec-80bd-11e5-8c9b-ce52ec98f508.jpg)

**Comment by guochunyan** [comment]
#616

**Comment by guochunyan** [comment]
@zerocoolys @wangjing1230  @iammybest 这个转化目标之前页面上所有的转化目标都隐藏了的，现在是需要做这个功能嘛？

**Comment by guochunyan** [comment]
#618

**Comment by wangjing1230** [comment]
问题重复，关闭该问题。
