### ISSUE TITLE
功能问题 页面转化 table第一列应为“来源”，且能展开。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#608]
页面地址：http://hy.best-ad.cn/#/transform/pageTransform

重现路径：慧眼-转化分析-页面转化

问题描述：页面转化table第一列应为“来源”，且能展开。
![8](https://cloud.githubusercontent.com/assets/14328394/10868127/c14763d6-80be-11e5-9535-5d8a56154187.jpg)

**Comment by iammybest** [comment]
@wangjing1230 这里我和阿福确认的不是这样哦，第一级是点击跳转，第二级才是展开 目前UI上问题第二级不能用+展开。稍后修正

**Comment by wangjing1230** [comment]
好的哈

**Comment by iammybest** [comment]
已经完成 忘记fixbug了
