### ISSUE TITLE
同类群组分析

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#610]
需求：
选择指标后，只有在点击 确定 后，才统一更新所选指标。
![image](https://cloud.githubusercontent.com/assets/12438962/10868147/66e671c4-80bf-11e5-8eac-19987efb5605.png)

**Comment by TomDing729** [comment]
已修复，已提交代码。  11/2 下午3点发布版本测试。

**Comment by wangjing1230** [comment]
@TomDing729 
指标选中后，就自动确认，加载数据了。
