### ISSUE TITLE
功能完善 页面转化 统计指标的缺失。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#611]
页面地址：http://hy.best-ad.cn/#/transform/pageTransform

重现路径：慧眼-转化分析-页面转化

问题描述：页面转化缺少了跳出率，平均转化成本、利润三个指标。
图片上传一直失败，见后。

**Comment by wangjing1230** [comment]
![11](https://cloud.githubusercontent.com/assets/14328394/10868165/b7eb79a2-80bf-11e5-9677-041b1e99f297.jpg)
![12](https://cloud.githubusercontent.com/assets/14328394/10868166/b7f05828-80bf-11e5-8a2b-ed81407de3a0.jpg)

**Comment by guochunyan** [comment]
@wangjing1230  #300

**Comment by iammybest** [comment]
@wangjing1230 @guochunyan  这个在前面个版本本来就不做的。后面会加，好了我再来处理

**Comment by wangjing1230** [comment]
好的，那我先把这个问题关闭了。
