### ISSUE TITLE
功能缺失 页面转化 折线图没有指标选择项。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#613]
页面地址：http://hy.best-ad.cn/#/transform/pageTransform

重现路径：慧眼-转化分析-页面转化

问题描述： 页面分析 折线图没有指标选择项。设计稿和需求文档，有此需求。
![15](https://cloud.githubusercontent.com/assets/14328394/10868173/31369d8c-80c0-11e5-9e1c-308813f18526.jpg)
![14](https://cloud.githubusercontent.com/assets/14328394/10868174/3137d6ac-80c0-11e5-80f6-54a636b5ecb3.jpg)

**Comment by wangjing1230** [comment]
@zymin 页面分析已有指标，可以选择。但是选择订单金额和订单转化率会报错。
![1](https://cloud.githubusercontent.com/assets/14328394/10899724/a29a748c-8212-11e5-838b-a852fd9b6177.jpg)

**Comment by zymin** [comment]
@iammybest 这里数据处理的有点问题，当点击了订单金额的时候就会报这个错，上面两个数据是正常的，zui'hou最后那个数据是不正确的
![Uploading eeQQ截图20151103102952.png…]()

**Comment by zymin** [comment]
![eeqq 20151103102952](https://cloud.githubusercontent.com/assets/8341699/10900039/08f95dda-8216-11e5-873a-02b979595cca.png)
