### ISSUE TITLE
转化分析-页面转化管理设置

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#615]
需求：
默认情况下不选择添加路径的情况下，请不要出现此红框内容，谢谢！
![image](https://cloud.githubusercontent.com/assets/12438962/10868452/e3b43664-80c9-11e5-9519-bee73193cf85.png)

**Comment by liwenkaifzk** [comment]
![qq 20151102111338](https://cloud.githubusercontent.com/assets/12439508/10873666/cc8d44e2-8152-11e5-8a25-73a7a95ba5c1.png)
