### ISSUE TITLE
来源变化榜

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#619]
用ie浏览器，表格怎么没有汇总呢？
![image](https://cloud.githubusercontent.com/assets/12438962/10900390/1e62a0b0-821a-11e5-875b-a60be1d25ca0.png)

**Comment by wangjing1230** [comment]
@Gongyufei 我这边打开有噢，ie11。请确认下呢。
![image](https://cloud.githubusercontent.com/assets/14328394/10900572/ac419844-821c-11e5-855d-cc5094232e55.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10900805/50310e60-821f-11e5-9494-4f900e19ab09.png)

**Comment by Gongyufei** [comment]
我刚才试了一下，还是不行。是不是兼容性问题呢？

**Comment by sgWeiMinSheng** [comment]
@liwenkaifzk 他们好像说ie9不行
