### ISSUE TITLE
ui：百度推广-推广方式

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#62]
请将指标选择放在 左侧：）
![image](https://cloud.githubusercontent.com/assets/12438962/7792694/0872fe36-02e9-11e5-89a1-f312a133f621.png)

**Comment by Gongyufei** [comment]
春燕，请将指标展开来放，不需要隐藏了：）谢谢

**Comment by zerocoolys** [comment]
@Gongyufei UI设计上是这样得?

**Comment by guochunyan** [comment]
指标多了也全部直接展示吗？
![qq 20150525144025](https://cloud.githubusercontent.com/assets/11551612/7792975/ecbea3a4-02eb-11e5-9852-1b73e54e5df1.png)

**Comment by fangzhenping** [comment]
ui上这么设计的，当时指标很多有6排所以
![image](https://cloud.githubusercontent.com/assets/11955235/7792986/fb64d252-02eb-11e5-94bd-cdfd03f3d4b0.png)

![image](https://cloud.githubusercontent.com/assets/11955235/7792954/b930c2b0-02eb-11e5-80b6-ac6efbffe09e.png)
，这个问题我私下有跟小燕燕沟通过，指标不多的话，就与其他页面统一，直接展示

**Comment by zerocoolys** [comment]
![image](https://cloud.githubusercontent.com/assets/2757581/7797404/28cb0d06-031e-11e5-9370-16a8fb9c1d30.png)

已确认.
