### ISSUE TITLE
查看链接点击图没有内容

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#620]
查看链接点击图 没有内容，请帮忙看一下，谢谢！
![image](https://cloud.githubusercontent.com/assets/12438962/10900909/cfac458c-8220-11e5-97bb-1224ae271f8f.png)

**Comment by wangjing1230** [comment]
@zhanghr 这个问题外网还没有解决噢
![4](https://cloud.githubusercontent.com/assets/14328394/11805407/3d7431a6-a346-11e5-8333-8d716ef07685.png)
