### ISSUE TITLE
时常转化目标

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#623]
问题：
进入此页面，默认红圈处不能修改，需刷新才能修改操作，请调整。多谢
![image](https://cloud.githubusercontent.com/assets/12438962/10903470/0bbfb51c-8245-11e5-889e-ed50a705c00f.png)

**Comment by guochunyan** [comment]
@Gongyufei  请问一下你是在什么情况下出现这个问题的呢？我这边没有测出来

**Comment by icepros** [comment]
取消功能未做

**Comment by iammybest** [comment]
@icepros  取消要做什么操作
