### ISSUE TITLE
样式问题 指定广告跟踪 自定义指标选择 报错

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#625]
页面url：http://hy.best-ad.cn/#/ads/adsSource

路径：慧眼-指定广告跟踪-来源-今天

问题：当反复选择自定义指标时，样式有误，且报错。
![7](https://cloud.githubusercontent.com/assets/14328394/10903730/d4c8e08a-8247-11e5-9b0e-7bda9f37ae17.jpg)

**Comment by wangjing1230** [comment]
@zhanghr

**Comment by wangjing1230** [comment]
![8](https://cloud.githubusercontent.com/assets/14328394/10903793/76c1ffd4-8248-11e5-9199-a0c4e1f52880.png)

**Comment by guochunyan** [comment]
@wangjing1230 
![qq 20151103163734](https://cloud.githubusercontent.com/assets/11551612/10903895/81646e8a-8249-11e5-9a40-a84f90b8e47d.png)汪汪 本地这边没有重现这个问题，你那边是在什么样的情况下出现的呢

**Comment by wangjing1230** [comment]
重复选择，多点几次就出现了。外网在孙邦雄的电脑也重现过这个问题。

**Comment by wangjing1230** [comment]
可以先改到其他的，这个放后点，都没关系。
开发本地不能重现，暂时关闭，发现后，再打开。
