### ISSUE TITLE
访客分析

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#626]
问题：
高级筛选，不能选择推广平台；请调整，谢谢！
![image](https://cloud.githubusercontent.com/assets/12438962/10903991/7c9e4ea6-824a-11e5-8748-eeacf3712259.png)

**Comment by wangjing1230** [comment]
@TomDing729

**Comment by wangjing1230** [comment]
问题不存在了，关闭问题。
