### ISSUE TITLE
功能报错 趋向分析-实时访客-刷新报错

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#638]
页面url：http://hy.best-ad.cn/#/trend/realtime

路径：慧眼-趋向分析-实时访客

问题描述：趋向分析-实时访客-刷新报错

重现路径：刷新
![4](https://cloud.githubusercontent.com/assets/14328394/10960902/c77f0d3c-83c3-11e5-9fb1-77cf846e53e5.jpg)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10961636/c57be0de-83cb-11e5-84cd-1916909dd0d1.png)
