### ISSUE TITLE
网站概览-搜索词查看更多

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#643]
跳转到
http://hy.best-ad.cn/#/source/searchterm_yq
按搜索引擎，设备过滤，点击计算机，移动设备报 500 错误
地域过滤 点击除了全部 其他点击也报500

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10961896/3cdaa6c2-83ce-11e5-9203-f18a3681f607.png)
