### ISSUE TITLE
【所有数据列表】中的涉及到小功能样式和效果细节问题，修改如图

### ISSUE THREAD

**Issue by fangzhenping** [zerocoolys/sshuiyan#65]
![image](https://cloud.githubusercontent.com/assets/11955235/7793343/3ce85272-02f0-11e5-81fe-a203dedde430.png)
图中的 小图标应该是鼠标滑过就出现 弹层 而不是点击事件

**Comment by zymin** [comment]
只改变了图标对其和弹出框内的样式

**Comment by fangzhenping** [comment]
@zymin 还差些细节麻烦修改下哦
![image](https://cloud.githubusercontent.com/assets/11955235/7805913/34c5b040-03ad-11e5-8798-f9f05d5dc486.png)

**Comment by fangzhenping** [comment]
很好
