### ISSUE TITLE
功能报错 来源分析-搜索词-按搜索引擎 查询事件报错

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#651]
页面url：http://hy.best-ad.cn/#/trend/today

路径：慧眼-来源分析-搜索词-按搜索引擎

问题描述：查询事件报错。

重现路径：来源分析-搜索词-按搜索引擎-查询
![18](https://cloud.githubusercontent.com/assets/14328394/10963007/cbbb181e-83d7-11e5-9ae6-0dd29070dc18.jpg)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10964583/031febb2-83e3-11e5-8bac-389bd4e8d9b2.png)

**Comment by wangjing1230** [comment]
@sgWeiMinSheng 问题仍然存在。
![29](https://cloud.githubusercontent.com/assets/14328394/10966073/235d9a92-83ec-11e5-83ec-f9b481b7d4d4.jpg)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10966629/ca5b7d2a-83ef-11e5-9c80-e251d633dacb.png)
