### ISSUE TITLE
样式问题 页面分析 受访页面 页面价值分析 汇总间距太远。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#654]
页面url：http://hy.best-ad.cn/#/trend/today

路径：慧眼-页面分析-受访页面-页面价值分析

问题描述：汇总间距太远。

重现路径：页面分析-受访页面-页面价值分析
![20](https://cloud.githubusercontent.com/assets/14328394/10963709/9277c5b0-83dd-11e5-9bcc-3183dcbdc040.jpg)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10965040/51255098-83e5-11e5-9319-ffd26ae83629.png)

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/10966245/413213bc-83ed-11e5-9cfc-e2b281b3a505.png)
