### ISSUE TITLE
功能报错 访客分析 设备环境 展开项报错。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#659]
页面url：http://hy.best-ad.cn/#/visitor/equipment

路径：慧眼-访客分析-设备环境

问题描述：设备环境中客户端属性，展开项报错。除前二不报错。

重现路径：慧眼-访客分析-设备环境-浏览器-点+
![25](https://cloud.githubusercontent.com/assets/14328394/10965139/f6ef9fc4-83e5-11e5-9fed-56233600012e.jpg)

**Comment by TomDing729** [comment]
该业务，目前只有前两项支持展开功能。

**Comment by wangjing1230** [comment]
复测仍然报错。如果只有前两项支持展开功能，那不能展开的，是否取消+号。

**Comment by wangjing1230** [comment]
复测问题已解决。关闭该问题。
