### ISSUE TITLE
【追UI】来源分析——搜索词：按搜索引擎中缺失图标，修改如图

### ISSUE THREAD

**Issue by fangzhenping** [zerocoolys/sshuiyan#66]
![image](https://cloud.githubusercontent.com/assets/11955235/7793721/33cb0cf2-02f5-11e5-9af5-4e425e4be161.png)

**Comment by zerocoolys** [comment]
@guochunyan @fangzhenping 需要的图标素材已经有了吗?

**Comment by guochunyan** [comment]
有了 房房已经发给我了
