### ISSUE TITLE
设备环境下载csv打开后  表头显示问题

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#662]
![qq 20151106141200](https://cloud.githubusercontent.com/assets/11189612/10990672/b311cf38-8490-11e5-92d7-954bdb01277c.jpg)

**Comment by zerocoolys** [comment]
@TomDing729 可能是输出了uigrid的内部属性

**Comment by TomDing729** [comment]
这个页面有展开页，输出了子级别的数据，目前针对子级别的数据做了处理。

**Comment by icepros** [comment]
展开项的数据不用下载下来吗？  @TomDing729

**Comment by TomDing729** [comment]
可以下载下来。

**Comment by icepros** [comment]
需求要求下载下来不
