### ISSUE TITLE
数据问题 转化分析 页面转化 转化率和新访客比率值有误。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#665]
页面url：http://hy.best-ad.cn/#/transform/pageTransform

路径：慧眼- 转化分析-页面转化

问题描述： 转化率和新访客比率值有误。

重现路径：慧眼- 转化分析-页面转化-自定义指标-转化率和新访客比率
![2](https://cloud.githubusercontent.com/assets/14328394/11025186/0aaa0ba4-86d3-11e5-8dc5-6b4c4c2dc5fb.jpg)

**Comment by iammybest** [comment]
@wangjing1230  所有小数点的修改完了。。2015年11月17日 部署后请再统一验证下吧

**Comment by wangjing1230** [comment]
好的
