### ISSUE TITLE
功能问题 管理设置 页面转化目标修改 路径类型成了必填项

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#672]
页面url：http://hy.best-ad.cn/#/conf/webcountsite/pagechange_update

路径：慧眼-管理设置-页面转化目标

问题描述：修改页面转化目标， 没有填写路径类型的状态下，保存，跳出对话框，要求必须填写，否则不能保存。

重现路径：慧眼-管理设置-页面转化目标-修改-没有填写路径类型-保存
![8](https://cloud.githubusercontent.com/assets/14328394/11027430/406bdcaa-86f0-11e5-9f9b-4ac6d47ebba5.jpg)

**Comment by iammybest** [comment]
@wangjing1230  此问题已修改 修改后 若未勾选则随意填写，勾选后必须填写正确
