### ISSUE TITLE
功能完善 指定广告跟踪 查看历史趋势隐藏不全。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#674]
页面url：http://hy.best-ad.cn/#/ads/adsSource

路径：慧眼-指定广告跟踪

问题描述：查看历史趋势隐藏不全。

重现路径：指定广告跟踪-选择自定义指标-确认
![9](https://cloud.githubusercontent.com/assets/14328394/11028007/9cf7f616-86f5-11e5-9913-d4da09d81739.jpg)

**Comment by zhanghr** [comment]
已经修复请测试
