### ISSUE TITLE
ui&表格指标展现形式-受访页面

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#678]
需求
1，删掉 访问次数，流量质量指标：增加  入口页次数
![image](https://cloud.githubusercontent.com/assets/12438962/11177263/4768a21a-8c7f-11e5-943c-2ed53f1f9e40.png)
2，受访页面会涉及到一个访客访问多个页面，表格中受访url正常统计，但是汇总时筛重，访客数只为1个。
以下是cnzz的计算页面截图
![image](https://cloud.githubusercontent.com/assets/12438962/11177812/33f0fbca-8c83-11e5-9326-d74c0985a1ea.png)

**Comment by guochunyan** [comment]
#677

**Comment by icepros** [comment]
我把我的哪个关闭了  就按这个来

**Comment by guochunyan** [comment]
@icepros  第一条已经处理了

**Comment by icepros** [comment]
看了

**Comment by wangjing1230** [comment]
@zhanghr 目前页面这个指标还没有数据，麻烦张哥哥确认完善了噢。

**Comment by icepros** [comment]
这个入口页面统计本身有误

**Comment by icepros** [comment]
入口页面只显示入口页面的数据不显示从入口页面跳转的统计等，受访页面才显示所有页面
