### ISSUE TITLE
图表：来源分析涉及到的柱状图表

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#69]
需求：做成折线图
![image](https://cloud.githubusercontent.com/assets/12438962/7794944/aee02406-0302-11e5-91cb-f12aae5e971b.png)
ui样式
![image](https://cloud.githubusercontent.com/assets/12438962/7794975/fadcda70-0302-11e5-9013-7532f037d384.png)

**Comment by zerocoolys** [comment]
已确认
