### ISSUE TITLE
数据问题 来源分析 按来源类型 展开项和汇总项，数据不一致。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#695]
页面url：http://hy.best-ad.cn/#/source/source

路径：慧眼-来源分析-全部来源

问题描述：来源分析 全部来源 按来源类型 展开项和汇总项，数据不一致。
截图一直上传失败，用文件夹的形式发到qq.
![Uploading 3.png…]()

**Comment by wangjing1230** [comment]
![3](https://cloud.githubusercontent.com/assets/14328394/11389577/07d1c3a2-937d-11e5-85f4-52fade6d0d05.png)

**Comment by sgWeiMinSheng** [comment]
根据百度统计对比，展开项和汇总的项没有必然的相加关系。展开项每条数据是自己算出的指标
