### ISSUE TITLE
当搜索词是www.best-ad.cn类似的时候可能会漏掉信息

### ISSUE THREAD

**Issue by zerocoolys** [zerocoolys/sshuiyan#7]
![image](https://cloud.githubusercontent.com/assets/2757581/7627945/ac2b6bbe-fa4f-11e4-9ec5-2324cabceded.png)
具体可以参考截图.

**Comment by xiaoweiqb** [comment]
我觉得可以把这个补全为账号的域名

**Comment by zerocoolys** [comment]
@xiaoweiqb 需要找到引起这个bug的原因

**Comment by SubDong** [comment]
引起这个的原因找到了   是IE7 的问题  通过IE7访问的时候我去获取他的  referer  获取出来就这样了
