### ISSUE TITLE
【列表数据】数据联动性问题，问题如截图

### ISSUE THREAD

**Issue by fangzhenping** [zerocoolys/sshuiyan#70]
![-1](https://cloud.githubusercontent.com/assets/11955235/7795417/7a366dc8-0307-11e5-8f32-a6504c74769a.png)
默认指标是ok的 但是点击自定义其他指标是 顶部位置的指标数没有随着变化，应该3个处都是联动性的变化

**Comment by zerocoolys** [comment]
@SubDong  确认, 在点击 "确定" 按钮之后指标才能变化

**Comment by fangzhenping** [comment]
恩恩 看到了点击确定后上面指标发生变更，有个疑问，点击自定义下方列表是即时发生变更，这种操作方式让我忘记还需要点击确认按钮，所以想有2种方式
一、不要确认按钮，直接勾选指标即时变更信息，这种看起来操作会减少一部确认步骤，是不是会更方便呢？
二、保留确认按钮，点击确认后，上下信息同时才发生变更

@SubDong

**Comment by fangzhenping** [comment]
@zerocoolys @Gongyufei

**Comment by zerocoolys** [comment]
@fangzhenping 
1 不需要确认按钮的情况下, 最大的问题就是每次点击都会去刷新数据, 如果用户需要增加多个指标,中间会增加多次数据请求.

**Comment by fangzhenping** [comment]
@zerocoolys 那这种情况看起来第一种不合适，那可以改为第二种，点击确认，上下数据才变更

**Comment by zerocoolys** [comment]
@fangzhenping 那就按照目前实现的方式, 不做修改吧.

@SubDong

**Comment by fangzhenping** [comment]
@zerocoolys 现在的方式 不对哦，它是 点选自定义标签 下方的数表列表是即时变更的，并不是点击确认才发生的事件哦, @SubDong 目前的操作让我忘记需要点击确认这个步骤，往往认为已经生效了

**Comment by SubDong** [comment]
@fangzhenping  现在我们系统中的这个指标是和百度保持一直还是保留联动？

**Comment by fangzhenping** [comment]
@zerocoolys @SubDong 我和雨菲讨论结果与百度保持一致，点击确认后数据才变更，抛开百度，这种操作也加强了确认按钮
