### ISSUE TITLE
功能完善 事件转化 查询动作 当页汇总和图表没有随之改变。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#700]
页面url：http://hy.best-ad.cn/#/transform/transformAnalysis

路径：慧眼-转化分析-事件转化

问题描述：事件转化 查询动作 当页汇总和图表没有随之改变。

重现步骤：慧眼-转化分析-事件转化-查询事件
![5](https://cloud.githubusercontent.com/assets/14328394/11420023/55ec15c6-9466-11e5-999f-0deeea2cc981.png)

**Comment by iammybest** [comment]
@wangjing1230  核对下，我做这个时候说的是 这个过滤就是过滤表格 不影响其其他位置内容

**Comment by wangjing1230** [comment]
确认过滤就是过滤表格 不影响其其他位置内容。关闭该问题。
