### ISSUE TITLE
功能问题 页面转化 转化目标筛选框 功能未完成。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#704]
页面url：http://hy.best-ad.cn/#/transform/pageTransform

路径：慧眼-转化分析-页面转化

问题描述：页面转化 转化目标筛选框 功能未完成。
![2](https://cloud.githubusercontent.com/assets/14328394/11433490/cc382fac-94f8-11e5-99d3-a9514ff85a5a.png)

**Comment by iammybest** [comment]
已完成
