### ISSUE TITLE
算法修正 慧眼表格当页汇总新访客比率和跳出率算法应为求和相除，而非均值。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#706]
问题描述：慧眼表格当页汇总新访客比率和跳出率目前为该列数据平均值，存在误差。参考百度，采用的是求和相除。
![3](https://cloud.githubusercontent.com/assets/14328394/11436738/696f9f48-9522-11e5-94ca-003be3c764fe.png)
![4](https://cloud.githubusercontent.com/assets/14328394/11436737/696e42ba-9522-11e5-8215-4a2ac9bc36f0.png)
![5](https://cloud.githubusercontent.com/assets/14328394/11436739/6972f1de-9522-11e5-9cfb-c6f778faaec7.png)

**Comment by wangjing1230** [comment]
@zerocoolys 晟哥，麻烦看看这个算法对不勒，如果改动的话，很多地方都要改，工作量很大，目前要改么？

**Comment by zerocoolys** [comment]
@wangjing1230 你说的这个是正确的哈，应该是这样计算出来。
辛苦找一下对应指标的相关负责人修正算法哈

**Comment by wangjing1230** [comment]
@iammybest @zhanghr @TomDing729 麻烦关注下这个问题噢，等巍巍改出一个模板了，再在群里通知大家修正哈。
