### ISSUE TITLE
推广URL打开速度

### ISSUE THREAD

**Issue by SubDong** [zerocoolys/sshuiyan#71]
url打开速度指，页面完全打开。  访客点击链接到完全打开页面的平均时间（例：www.best-ad.cn点击了50次，则算出这50次的平均时间）
页面完全打开指：文字、图片、falsh全部加载完毕。

@zerocoolys   @Gongyufei

**Comment by Gongyufei** [comment]
@zerocoolys  Sorry子栋，再确认，需和百度统计一致。还请再重新制定规则，多谢。
确认：客户完全打开网站页面（不包括加载完全部图片和flash）的时间。
