### ISSUE TITLE
样式问题 指定广告跟踪 图表比率和平均访问时长纵坐标有误。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#720]
页面url：http://hy.best-ad.cn/#/ads/adsSource

路径：慧眼-指定广告跟踪

问题描述：图表比率和平均访问时长纵坐标有误。

![10](https://cloud.githubusercontent.com/assets/14328394/11521807/188170b2-98eb-11e5-83fe-f75594e44326.png)
![11](https://cloud.githubusercontent.com/assets/14328394/11521808/18a4d75a-98eb-11e5-87de-339fe4770fc8.png)

**Comment by iammybest** [comment]
@wangjing1230 平均访问时上 都是现实的数字
