### ISSUE TITLE
表格：慧眼中所有涉及到对比项的模块

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#73]
与其他时间段对比：数据指标需体现出来对比数据
![image](https://cloud.githubusercontent.com/assets/12438962/7804354/5e8514de-0394-11e5-8970-77ddc14c99d9.png)

样例：
![image](https://cloud.githubusercontent.com/assets/12438962/7804444/cc95952e-0395-11e5-9fa6-b0dd048c8c95.png)

**Comment by Gongyufei** [comment]
@zerocoolys

**Comment by sgWeiMinSheng** [comment]
![qq 20150526123059](https://cloud.githubusercontent.com/assets/10495048/7805352/2035840c-03a3-11e5-9fc7-4fef8fee1bfd.png)
已解决
