### ISSUE TITLE
样式问题 图表气泡显示样式完善。百分比没有百分号。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#732]
页面url：http://hy.best-ad.cn/#/trend/today

路径：慧眼-趋向分析-今日统计

问题描述：图表气泡显示样式完善。百分比没有百分号。平均访问时长只显示了整数。

**Comment by wangjing1230** [comment]
![3](https://cloud.githubusercontent.com/assets/14328394/11623820/3d52c472-9d0a-11e5-89a3-f5307df6c55e.png)

**Comment by sgWeiMinSheng** [comment]
markPoint属性不能对数据进行格式化。把数据换成字符串的百分比要出错，图表不显示。

**Comment by wangjing1230** [comment]
@zerocoolys 晟哥，还有种办法是把最大值取消了，是先保持原状，还是取消最大值呢？

**Comment by zerocoolys** [comment]
@sgWeiMinSheng 为什么右侧Y轴的值是能显示百分比的，这个是echart自动生成的吗？

**Comment by sgWeiMinSheng** [comment]
@zerocoolys 坐标轴的显示，有一个坐标轴标签，可以格式化数据显示自己的东西
