### ISSUE TITLE
样式问题 来源分析 搜索引擎 饼状图字符重叠。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#740]
页面url：http://hy.best-ad.cn/#/source/searchengine

路径：慧眼-来源分析-搜索引擎

问题描述：当搜索引擎较多时，饼状图字符重叠。以前修改过类似的问题。bug号#412，#250。

重现步骤：慧眼-来源分析-搜索引擎-自定义日期（11.19-12.10）
![4](https://cloud.githubusercontent.com/assets/14328394/11710082/b24edcd0-9f57-11e5-973e-ff43f238adc2.png)

**Comment by guochunyan** [comment]
@wangjing1230  之前搜索引擎这块@Gongyufei 要求文字在饼图上显示 但是对应模块数据不多，模块只有那么大，所以区域内有文字显示重叠，这个避免不了，@wangjing @Gongyufe解决方法是文字在饼图外部显示，你们确认一下呢

**Comment by guochunyan** [comment]
@wangjing1230  @Gongyufe还有一点 可以点击对应模块的时候显示内容！烦请确认一下

**Comment by wangjing1230** [comment]
@guochunyan 已经确认了哈，采用文字在饼图外部显示的形式，和其他版块一样。
![y3 j0ghtyk 5 zyqh 047 t](https://cloud.githubusercontent.com/assets/14328394/11710762/7990b6a2-9f5c-11e5-85ba-c988ddc6fd0f.png)

**Comment by guochunyan** [comment]
@wangjing1230 ok!
