### ISSUE TITLE
UI-新增指定广告跟踪

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#744]
1,目标URL填写时，提示文字红框内改为“某”
![image](https://cloud.githubusercontent.com/assets/12438962/11738097/931e6e16-a01a-11e5-981b-3f1014a216ae.png)
2,广告类型应该高级选项之前，为必填项
![image](https://cloud.githubusercontent.com/assets/12438962/11737959/59c399da-a019-11e5-8ea7-0b8572facdc7.png)

**Comment by wangjing1230** [comment]
@Gongyufei 广告类型调整这个，阿福哥前两天提过，好像后来是确定放在三期了，请确认下呢。
