### ISSUE TITLE
UI-新增页面转化目标

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#745]
1，转化类型由选填改为必填
![image](https://cloud.githubusercontent.com/assets/12438962/11738208/91b5fa70-a01b-11e5-83e3-4a8b69b03ac1.png)
2，转化类型中的其他后面增加一个输入框
![image](https://cloud.githubusercontent.com/assets/12438962/11738227/b18d7b70-a01b-11e5-8e4a-d7328196e0a1.png)

**Comment by iammybest** [comment]
@Gongyufei 其他后面有输入框  要点击其他才显示

**Comment by Gongyufei** [comment]
好的，谢谢

**Comment by wangjing1230** [comment]
@guochunyan 路径类型应该是选填，转化类型才是必填，应该是改错位置了吧。修改设置页面也多注意噢，现在还没有修改的，都是选填。
![2](https://cloud.githubusercontent.com/assets/14328394/11774525/03f52dfc-a271-11e5-859e-a26955d32106.png)
