### ISSUE TITLE
数据问题 页面分析-受访页面-指标概览 新访客+老访客不等于总访客数。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#748]
页面url：http://hy.best-ad.cn/#/page/indexoverview

路径：慧眼-页面分析-受访页面-指标概览

问题描述： 新访客+老访客不等于总访客数。最近7天，或自定义时间段数据误差比较明显。
![1](https://cloud.githubusercontent.com/assets/14328394/11800266/f1c67dd4-a315-11e5-9a9d-f8839acb26fc.png)
![2](https://cloud.githubusercontent.com/assets/14328394/11800265/f1c50c1a-a315-11e5-9d70-a5d7045f850d.png)
![3](https://cloud.githubusercontent.com/assets/14328394/11800267/f1cb6060-a315-11e5-8386-3324bdaafcde.png)

**Comment by iammybest** [comment]
新访客 -- 汇总数 等于各行相加 因为新房客只记录一次
老访客 -- 汇总<= 各行相加  老访客存在访问去重
因此在 新访客过滤下访客数和老访客过滤下访客数 相加数量 应该>=总的访客数
两个指标中的访客数存在包含关系
