### ISSUE TITLE
[配置页]导航有问题

### ISSUE THREAD

**Issue by zerocoolys** [zerocoolys/sshuiyan#75]
![image](https://cloud.githubusercontent.com/assets/2757581/7805465/56d442b2-03a5-11e5-9ea6-063eac1155ec.png)

首页图标应该回到 首页, 而不是配置页

@liwenkaifzk

**Comment by guochunyan** [comment]
已经修改了

**Comment by zerocoolys** [comment]
![image](https://cloud.githubusercontent.com/assets/2757581/7829880/6dc9672a-0479-11e5-8bbf-eece8c6f8f50.png)

@liwenkaifzk @guochunyan 

问题仍然没有解决

**Comment by zerocoolys** [comment]
@liwenkaifzk
