### ISSUE TITLE
【所有的地域过滤】目前只有中国，当时设计时定的是 五大洲下的国家下的城市

### ISSUE THREAD

**Issue by fangzhenping** [zerocoolys/sshuiyan#76]
![qq 20150526140007](https://cloud.githubusercontent.com/assets/11955235/7806157/ed2bed46-03af-11e5-86b4-af4ff46519ca.jpg)

**Comment by zerocoolys** [comment]
@fangzhenping 这个挪到二期来实现吧

**Comment by fangzhenping** [comment]
@zerocoolys 好的，那我关闭了

**Comment by zerocoolys** [comment]
已经注明到二期了. milestone

@fangzhenping  不用关哈...

**Comment by fangzhenping** [comment]
好的

**Comment by zerocoolys** [comment]
@fangzhenping 要维护所有城市信息很困难，所以这个功能就取消，只过滤国内的地级市以上级别。
