### ISSUE TITLE
设备环境-自定义时间查询echarts图例横轴显示不对

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#762]
![qq 20151215163656](https://cloud.githubusercontent.com/assets/11189612/11805858/308e9cd4-a34a-11e5-9e8c-cb28659a507a.png)

**Comment by Gongyufei** [comment]
选择最近7天也是这样，请调整哈，多谢
![image](https://cloud.githubusercontent.com/assets/12438962/11862789/af7491ea-a4c9-11e5-8d14-a4ca77b7f4c2.png)
