### ISSUE TITLE
数据问题 转化分析 页面分析 部分来源乱码。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#775]
页面url：http://hy.best-ad.cn/#/transform/pageTransform

路径：慧眼-转化分析-页面分析

问题描述：部分来源乱码。

重现步骤：慧眼-转化分析-页面分析-最近7天-按搜索引擎-百度
![b5yob2 y8__p9ywi27us 07](https://cloud.githubusercontent.com/assets/14328394/11835510/13803d6c-a40f-11e5-88e5-8f337015dd16.png)

**Comment by iammybest** [comment]
以前数据乱码已无法恢复 后续数据 中文乱码已解决  测试方式为 设置页面转化名称为中文用 IE浏览器访问 @wangjing1230 请测试所有可能出现中文位置的情况

**Comment by iammybest** [comment]
该ISSUE 测试完所有中文情况再关闭

**Comment by wangjing1230** [comment]
好的
