### ISSUE TITLE
数据问题 转化分析 页面分析 搜索引擎展开前后汇总数据不一致。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#777]
页面url：http://hy.best-ad.cn/#/transform/pageTransform

路径：慧眼-转化分析-页面分析

问题描述：搜索引擎展开前后汇总数据不一致。

重现步骤：慧眼-转化分析-页面分析-最近7天-按搜索引擎
![8](https://cloud.githubusercontent.com/assets/14328394/11835886/b518e726-a411-11e5-87d7-d11b8fc82a2a.png)

**Comment by wangjing1230** [comment]
![9](https://cloud.githubusercontent.com/assets/14328394/11837919/c38e5324-a41e-11e5-9b89-c6536a8be0a2.png)

**Comment by iammybest** [comment]
搜索引擎展开前后汇总数据不一致。 已和北京沟通 维持目前 @chulifu @wangjing1230 @zerocoolys 
这里再备注解释下：
页面转化展示
假设环境： IP(如192.168.1.102) 用搜狗、百度都搜索了 www.best-ad.cn 
第一层展示：搜索引擎行，用来源(rf_type)分组 测试 IP计数为 1
第二层展示：（搜索引擎点击跳转） 用搜索引擎(se)分组  百度 统计上述IP 计数1  搜狗也会统计上述IP 计数1 此时汇总为2 与第一层展示不同

**Comment by iammybest** [comment]
@wangjing1230 加好展开后 展示内容不随动问题已解决
