### ISSUE TITLE
【功能实现】导出功能的兼容问题

### ISSUE THREAD

**Issue by fangzhenping** [zerocoolys/sshuiyan#78]
![image](https://cloud.githubusercontent.com/assets/11955235/7806460/c18a785c-03b3-11e5-8d2e-eca789c72131.png)
以下页面都有 刷新与导出（下载）按钮
![image](https://cloud.githubusercontent.com/assets/11955235/7806744/3a637578-03b7-11e5-9b53-2b97bf8dff33.png)

![image](https://cloud.githubusercontent.com/assets/11955235/7806694/9b756b24-03b6-11e5-965f-ef1b850ac30b.png)
![image](https://cloud.githubusercontent.com/assets/11955235/7806710/c74c2684-03b6-11e5-9b69-6fe846373c96.png)
![image](https://cloud.githubusercontent.com/assets/11955235/7806718/e0ddc0e4-03b6-11e5-9b47-d431b447976c.png)
![image](https://cloud.githubusercontent.com/assets/11955235/7806724/fbb74ec6-03b6-11e5-9e0a-2e36fcd55845.png)
![image](https://cloud.githubusercontent.com/assets/11955235/7806733/16ba2ec8-03b7-11e5-9de0-1d3991312351.png)
![image](https://cloud.githubusercontent.com/assets/11955235/7806741/2034d6b0-03b7-11e5-9c30-46485fd7f928.png)

**Comment by zymin** [comment]
@zerocoolys 网站概览不是只有刷新么？现在是要把导出加进来么？

**Comment by zerocoolys** [comment]
@zymin 需要有导出的功能. 
@Gongyufei 请确认导出功能包括的具体内容.

**Comment by zerocoolys** [comment]
@zymin 刷新的功能可以了吗?

**Comment by fangzhenping** [comment]
![image](https://cloud.githubusercontent.com/assets/11955235/7852343/b16029be-052e-11e5-8c24-8241ecb7b66c.png)
刷新样式统一下，如图标注

**Comment by zymin** [comment]
@zerocoolys 刷新功能可以了

**Comment by fangzhenping** [comment]
@zymin 辛苦把 导出的样式修改下，统一

**Comment by guochunyan** [comment]
![72](https://cloud.githubusercontent.com/assets/11551612/7900390/c313a690-0786-11e5-84f5-c42089f38bda.png)
![90](https://cloud.githubusercontent.com/assets/11551612/7900392/c8c8cae8-0786-11e5-8f62-f1963f9704f3.png)@fangzhenping 第一个为72PX 第二个为90PX

**Comment by fangzhenping** [comment]
@guochunyan 看到了，请问 是不是保存直接下载到自己本地电脑上而不是新开页面呢

**Comment by fangzhenping** [comment]
已确认，safari浏览器下 是新弹出窗口，看看有没有办法解决
![ye4 e 7b6tcy_sg 9xoz1 a](https://cloud.githubusercontent.com/assets/11955235/7901437/267e73b8-07b9-11e5-9074-20359e35a876.jpg)

**Comment by zerocoolys** [comment]
@SubDong 请确认一下UI-grid导出CSV之后http 头的类型是否正确?
是ostream那种

**Comment by SubDong** [comment]
@zerocoolys @fangzhenping 
出现safari浏览器下 csv 新弹出窗口，而不是下载 是因为safar现还不支持html5  download attribute
参考：https://github.com/angular-ui/ng-grid/issues/3102

**Comment by fangzhenping** [comment]
@SubDong 那这个是不是归为无法决解的问题

**Comment by zerocoolys** [comment]
@fangzhenping 我们用另外的办法来实现哈, 可以解决的
@SubDong 根据昨天开会的解决方案实现.

**Comment by fangzhenping** [comment]
@zerocoolys  好的
