### ISSUE TITLE
功能问题 来源分析-外部链接 下载pdf只有url，没有指标数据。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#787]
页面url：http://hy.best-ad.cn/#/source/externallinks

路径：慧眼-来源分析-外部链接

问题描述：下载pdf只有url，没有指标数据。
![bsnlw 8a vc7w6mapmq](https://cloud.githubusercontent.com/assets/14328394/11890820/8f287d5a-a593-11e5-8301-d88bad353cfa.png)

**Comment by wangjing1230** [comment]
ps：发送邮件，“外部连接”应为“外部链接”
![m t 7enme p _cw_ ph](https://cloud.githubusercontent.com/assets/14328394/11890837/b97c50ae-a593-11e5-9fa7-faa3a45f450d.png)

**Comment by sgWeiMinSheng** [comment]
单元格长度问题
