### ISSUE TITLE
【追UI信息】访客分析——访客地图：修改如图

### ISSUE THREAD

**Issue by fangzhenping** [zerocoolys/sshuiyan#79]
![qq 20150526140007_markman](https://cloud.githubusercontent.com/assets/11955235/7806925/0f57c332-03b9-11e5-8d58-5b1358263b63.png)

**Comment by fangzhenping** [comment]
刚刚跟小燕燕沟通完，
除了![image](https://cloud.githubusercontent.com/assets/11955235/7807249/764a8c16-03bc-11e5-8cb3-c1030c801072.png)这处外的 ，其他地方辛苦修改下

**Comment by guochunyan** [comment]
![qq 20150526164303](https://cloud.githubusercontent.com/assets/11551612/7808496/34f1c4be-03c6-11e5-90d2-8d5bbe7e18bf.png)

**Comment by guochunyan** [comment]
![qq 20150526175217](https://cloud.githubusercontent.com/assets/11551612/7809878/0d439244-03d0-11e5-948e-a301beb41a82.png)

**Comment by zerocoolys** [comment]
@fangzhenping 请确认bug

**Comment by fangzhenping** [comment]
很好，已解决
