### ISSUE TITLE
UI-

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#791]
请统一为0.00%，辛苦修哈
![image](https://cloud.githubusercontent.com/assets/12438962/11891793/c8520a02-a59c-11e5-8b91-733483a03cac.png)

**Comment by wangjing1230** [comment]
@sgWeiMinSheng 还有些版块没有改到

![14](https://cloud.githubusercontent.com/assets/14328394/11894953/a506d8ca-a5b5-11e5-9a7e-8e01b257000a.png)

**Comment by sgWeiMinSheng** [comment]
好的。。
