### ISSUE TITLE
数据问题 转化分析-事件转化 时间对比状态下，表格当页汇总不应直接求和，应和单独查看的数据一致。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#794]
页面url：http://hy.best-ad.cn/#/transform/transformAnalysis

路径：慧眼-转化分析-事件转化

问题描述：时间对比状态下，表格当页汇总不应直接求和，应和单独查看的数据一致。
![3](https://cloud.githubusercontent.com/assets/14328394/11916856/02026474-a726-11e5-9779-94eced274439.png)

**Comment by iammybest** [comment]
这个BUG已解决大部分 涉及到转化率的 使用多列计算的 暂无法实现
