### ISSUE TITLE
受访页面-指标显示

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#795]
1.首次进入统计指标和列表指标的显示和自定义指标默认选中的指标显示不一致
![qq 20151220144601](https://cloud.githubusercontent.com/assets/11189612/11916909/8aca6a5c-a728-11e5-8279-00c11dd36c6d.png)

2.点击默认指标并确定后统计指标和列表指标的显示和自定义指标默认指标显示不一致
ps:受访页面没有访问次数指标
![qq 20151220144746](https://cloud.githubusercontent.com/assets/11189612/11916920/4ec0f76e-a729-11e5-8157-f4a3283941d4.png)

3.选中其他指标后方可选中入口页次数指标 确定后  统计指标显示不一致,列表入口页次数数据显示不出
![qq 20151220145455](https://cloud.githubusercontent.com/assets/11189612/11916944/5bd76022-a72a-11e5-80a0-fc6ccbb9af25.png)

**Comment by wangjing1230** [comment]
昨天悲催姐修复#785后，产生的后续问题。

**Comment by icepros** [comment]
点击系统默认指标后列表显示不对
![20150125](https://cloud.githubusercontent.com/assets/11189612/11947466/2a4b2dda-a8a2-11e5-86d8-c0160edea4fe.jpg)
