### ISSUE TITLE
算法纠正-平均访问页数

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#799]
![image](https://cloud.githubusercontent.com/assets/12438962/11917170/b8927a20-a736-11e5-8095-1701692f0cf1.png)，请修改一下，辛苦了，多谢！
慧眼里的平均访问页数应该有问题，请检查，多谢！
![image](https://cloud.githubusercontent.com/assets/12438962/11917175/e31c6102-a736-11e5-92d2-7c3b39084afe.png)

**Comment by wangjing1230** [comment]
最近30天和自定义时间段，算法还不对。
