### ISSUE TITLE
【追UI】访客分析——新老访客：修改如图

### ISSUE THREAD

**Issue by fangzhenping** [zerocoolys/sshuiyan#80]
![image](https://cloud.githubusercontent.com/assets/11955235/7807342/539b9f92-03bd-11e5-94b3-60c08a1d4f3b.png)
![image](https://cloud.githubusercontent.com/assets/11955235/7807374/a7e63ada-03bd-11e5-8148-9daecc88380b.png)

**Comment by guochunyan** [comment]
![qq 20150526162606](https://cloud.githubusercontent.com/assets/11551612/7808169/e4704148-03c3-11e5-887c-4aaac8c35d9d.png)

**Comment by fangzhenping** [comment]
ok，收到
