### ISSUE TITLE
页面转化-只选中基础指标,指定时间段对比后,无对比数据

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#802]
![qq 20151220170717](https://cloud.githubusercontent.com/assets/11189612/11917291/a8f55dc0-a73c-11e5-88bd-67770e67947e.png)

**Comment by iammybest** [comment]
这是当前也汇总 你选的日期本来就无数据 对页面转化来说 如果没有 页面转化次数 则都不显示
