### ISSUE TITLE
事件转化,页面转化-在管理设置配置后,删除对应的配置数据前面的统计数据也会相应的删除

### ISSUE THREAD

**Issue by icepros** [zerocoolys/sshuiyan#806]
配置数据
![qq 20151221164335](https://cloud.githubusercontent.com/assets/11189612/11926715/04706008-a802-11e5-8fa6-5646ae9be0db.png)
造数据查看
![qq 20151221164235](https://cloud.githubusercontent.com/assets/11189612/11926701/e09427dc-a801-11e5-87b8-e48af8769604.png)
删除配置数据
![qq 20151221164425](https://cloud.githubusercontent.com/assets/11189612/11926730/21de2ef4-a802-11e5-8d29-42164e526d5c.png)
再查看统计数据
![qq 20151221164456](https://cloud.githubusercontent.com/assets/11189612/11926738/34fb11e6-a802-11e5-959c-63b52d80b5c8.png)

**Comment by icepros** [comment]
上面只对事件切图,页面转化同样的

**Comment by iammybest** [comment]
配置是有更新事件的 只统计新增时刻开始的数据
