### ISSUE TITLE
UI-事件转化目标

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#823]
事件转化目标 点击 “删除”按钮的时候，增加一友好提示弹窗
![image](https://cloud.githubusercontent.com/assets/12438962/11972431/1913ddba-a987-11e5-9951-d59eea82c4f9.png)

弹窗样式如下：
![image](https://cloud.githubusercontent.com/assets/12438962/11972457/7bef1bc0-a987-11e5-9681-9ec3ec6c7e75.png)

**Comment by zymin** [comment]
@Gongyufei 有友好提示弹窗啊，只是样式和你这个不同

**Comment by Gongyufei** [comment]
样式和房房确认哈，看时间是否充足。主要是文字要修改哈，多谢
![image](https://cloud.githubusercontent.com/assets/12438962/11988887/c821f4ba-aa2f-11e5-9efd-eefd871350d3.png)

**Comment by zymin** [comment]
好的
