### ISSUE TITLE
数据问题 页面分析-入口页面-新访客分析 访客数和新访客数一致，和指标概览数据不一致。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#829]
页面url：http://hy.best-ad.cn/#/page/entrancepage_nv

路径：页面分析-入口页面-新访客分析

问题描述：访客数和新访客数一致，和指标概览数据不一致。
PS：查看历史趋势页面访客数和新访客数一致。
![9](https://cloud.githubusercontent.com/assets/14328394/11989573/1131e006-aa3b-11e5-968c-b2dd806f84d4.png)
![10](https://cloud.githubusercontent.com/assets/14328394/11989574/1144ea16-aa3b-11e5-8ace-b42017a4e706.png)

**Comment by iammybest** [comment]
过滤条件问题

**Comment by iammybest** [comment]
@wangjing1230  目前新访客数已经一致，访客数 因为是 跳转的新访客分析 直接过滤掉了所有老访客情况 结果为 访问次数和新访客一样 确认下这样解释是否合理

**Comment by wangjing1230** [comment]
@iammybest 访客数应该包含老访客。
![njm dm7d2bkky0f 7d p5 8](https://cloud.githubusercontent.com/assets/14328394/12048195/c690a050-af12-11e5-8ff9-d845f05b8831.png)
