### ISSUE TITLE
数据问题 页面分析-受访页面/入口页面，访客数和访问次数指标算法调整。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#838]
页面url：http://hy.best-ad.cn/#/page/entrancepage

路径：慧眼-页面分析-受访页面/入口页面

问题描述：访客数和访问次数指标算法调整。

重现步骤：百度搜索“百思 慧眼”-访问-浏览量，访客数和访问次数均加1-再次访问-浏览量，访客数和访问次数均再加1

通过百度第二次访问，正常情况下，应该浏览量加1，访客数和访问次数均不再加
![4](https://cloud.githubusercontent.com/assets/14328394/12014822/1aaf6a28-ad6e-11e5-9f7d-caca6e089cde.png)

**Comment by iammybest** [comment]
@zerocoolys 
@Gongyufei @chulifu 
@zhanghr @sgWeiMinSheng 
@wangjing1230 

该ISSUE 下修正所有页面的 访客数 新访客数  访问次数 算法 解释请测试 需求童鞋悉知，计算方式请开发同学悉知
访问次数：解释---开一个标签访问网页 算一次 标签内跳转或者刷新页面（F5 若Ctrl+F5会累加）不累加（PV会累加）
                 计算方式----tt 去重
访客数：解释---同一个浏览器访问一个网站 在COOKIE时效内 算一个访客，刷新 重开不累加
                 计算方式----_ucv 去重
新访客数：解释---同一个浏览器第一次访问一个网站  算一个新访客，刷新 重开不累加
                 计算方式----_ct=0 情况下 _ucv 去重
如有误，请指出！！！！

**Comment by iammybest** [comment]
@icepros

**Comment by icepros** [comment]
如果这个cookie相隔一天后继续访问呢.算什么@iammybest

**Comment by iammybest** [comment]
@icepros  cookie 隔一天后 新访客不增加 访客数增加 访问次数照旧

**Comment by wangjing1230** [comment]
@iammybest 
动作：关闭浏览器再次访问
预期结果：浏览量+1，访客数不变，访问次数+1，新访客数不变
实际结果：浏览量+1，访客数+1，访问次数+1，新访客数不变

访客数定义：一天之内您网站的独立访客数(以Cookie为依据)，一天内同一访客多次访问您网站只计算1个访客(uv)。

**Comment by wangjing1230** [comment]
@iammybest 
动作1：清除cookie，打开浏览器，访问页面
预期结果：浏览量+1，访客数+1，访问次数+1，新访客数+1
实际结果：浏览量+1，访客数+1，访问次数+1，新访客数+1
动作2：关闭该页面标签，再次访问该页面
预期结果：浏览量+1，访客数不变，访问次数不变，新访客数不变
实际结果：浏览量+1，访客数+1，访问次数不变，新访客数不变

重复动作2，访客数不再+1

**Comment by iammybest** [comment]
@zhanghr @sgWeiMinSheng 修正
uv 中访客数计算为 vid 去重
nuv 为 过滤 ct=0 vid 去重

**Comment by icepros** [comment]
CTRL+F5 强刷不会对访问次数有影响哈

**Comment by wangjing1230** [comment]
@iammybest 半小时后，刷新页面，访问次数没有增加。

ps:2
访问次数
访客在您网站上的会话(Session)次数，一次会话会浏览一个或多个页面。在百度统计里，以下三种情况会记为新的访问：
1. 访客关闭浏览器后重新进入您的网站；
2. 访客不关闭浏览器，但是在您网站上不活动超过30分钟，30分钟后访客再次点击您网站上的链接；
3. 访客任何时候从其他网站到达您的网站。
