### ISSUE TITLE
样式问题 历史趋势页面，单点时间状态（昨天，今天，自定义1天），图表显示调整。

### ISSUE THREAD

**Issue by wangjing1230** [zerocoolys/sshuiyan#839]
页面url：http://hy.best-ad.cn/#/source/source/history

路径：慧眼-历史趋势页面

问题描述：单点时间状态（昨天，今天，自定义1天），图表显示调整。

![6](https://cloud.githubusercontent.com/assets/14328394/12015156/43b5b396-ad73-11e5-901f-a3bd3499452d.png)
调整成这样，看起来会不会更好？
![5](https://cloud.githubusercontent.com/assets/14328394/12015162/4a4bc876-ad73-11e5-8138-9275a5d9c374.png)

**Comment by zymin** [comment]
@wangjing1230 这是一天的时间，是必须要的哈

**Comment by icepros** [comment]
我之前问过晟哥  晟哥说这个没问题

**Comment by wangjing1230** [comment]
敏敏，如果能改就改，不能改我们就关掉哈。
