### ISSUE TITLE
[指标] 计算错误

### ISSUE THREAD

**Issue by zerocoolys** [zerocoolys/sshuiyan#85]
![image](https://cloud.githubusercontent.com/assets/2757581/7827360/f160029a-0458-11e5-9dcd-276d2af09f7f.png)

按照搜索引擎统计的指标有问题

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/7827732/74a2b39c-045d-11e5-9f4c-5ba3c125410c.png)

**Comment by zerocoolys** [comment]
@sgWeiMinSheng 在提交代码之后才能将issue设置成已解决哈..方便测试人员验证
