### ISSUE TITLE
[图表] 优化tooltip显示

### ISSUE THREAD

**Issue by zerocoolys** [zerocoolys/sshuiyan#86]
当前效果:
![image](https://cloud.githubusercontent.com/assets/2757581/7827410/95a7dae4-0459-11e5-8356-0553bb6a4f5b.png)

鼠标移动上去之后会导致所有数据都显示出来.

需求:

修改成鼠标在某个数值上,就显示当前指标的数值.

**Comment by xiaoweiqb** [comment]
这个已经在一期解决了！
