### ISSUE TITLE
ui&图表：网站概览

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#88]
1，最近30天，从今天算起，往后推30天；现日历为31天：(  （应为4月28日-5月27日）
![image](https://cloud.githubusercontent.com/assets/12438962/7827429/c09cadec-0459-11e5-99c0-b82148196c3a.png)
2，日历应该是4月份和5月份； 3，日期区间需修改，是选择的起始时间：）
![image](https://cloud.githubusercontent.com/assets/12438962/7827478/54b6fb2c-045a-11e5-93d5-9befe9e4a606.png)

**Comment by Gongyufei** [comment]
最近7天，从今天开始往后推的7天：）
![image](https://cloud.githubusercontent.com/assets/12438962/7827786/f5779dca-045d-11e5-935a-003ff83f2688.png)

最近30天，按周选择，时间段有误。    用自然周（周一--周日）
![image](https://cloud.githubusercontent.com/assets/12438962/7827772/d924e0a6-045d-11e5-9539-97ce0b08f4a7.png)

**Comment by Gongyufei** [comment]
![image](https://cloud.githubusercontent.com/assets/12438962/7827882/0b17deaa-045f-11e5-9a3c-b8a1acc29552.png)

**Comment by Gongyufei** [comment]
最近30天，从今天算起，往后推的30天；（别推出个31天） ：）

**Comment by Gongyufei** [comment]
慧眼中最近7天，最近30天，都统一一下，谢谢，辛苦啦

**Comment by Gongyufei** [comment]
@zerocoolys

**Comment by xiaoweiqb** [comment]
@Gongyufei 

近7天包不包括今天？近30天包不包括今天？

**Comment by Gongyufei** [comment]
近7天和近30天都包括今天，从今天开始往后推。:)
周为自然周（周一-周日）
月为自然月（从1号开始-月尾）

**Comment by Gongyufei** [comment]
@xiaoweiqb quxia 趋向分析模块 也修改一下哈：）
![image](https://cloud.githubusercontent.com/assets/12438962/7828694/93e0c9a4-0469-11e5-911f-e7039f942a17.png)
