### ISSUE TITLE
UI:推广概况

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#89]
日期调整一下
![image](https://cloud.githubusercontent.com/assets/12438962/7828088/7bc08006-0461-11e5-84f5-e02d6e7d9fd4.png)

**Comment by xiaoweiqb** [comment]
哦，这个近30天还是斜着吧！

**Comment by Gongyufei** [comment]
这是网站概览的效果
![image](https://cloud.githubusercontent.com/assets/12438962/7833732/a2215326-049b-11e5-9254-5f965514dabe.png)
