### ISSUE TITLE
所有涉及到的 对比时间段问题

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#9]
对比时间段不能选择

**Comment by zerocoolys** [comment]
是UI上无法选择还是选择了时间段之后没有对应的数据查询

**Comment by Gongyufei** [comment]
选择不了
![image](https://cloud.githubusercontent.com/assets/12438962/7664391/71ae9c22-fbb7-11e4-8620-fd0b626d0a5f.png)

**Comment by guochunyan** [comment]
![qq 20150520180619](https://cloud.githubusercontent.com/assets/11551612/7723423/089f09a8-ff1b-11e4-9534-7e8562100db1.png)
时间段范围选择已OK
