### ISSUE TITLE
[图表] 搜索词

### ISSUE THREAD

**Issue by zerocoolys** [zerocoolys/sshuiyan#93]
![image](https://cloud.githubusercontent.com/assets/2757581/7829556/2ac0924e-0476-11e5-9b09-914311810012.png)

上下数据完全不一致.

**Comment by sgWeiMinSheng** [comment]
![image](https://cloud.githubusercontent.com/assets/10495048/7876227/c50fa792-05fa-11e5-85de-8037da9828f4.png)

**Comment by zerocoolys** [comment]
已确认.
