### ISSUE TITLE
UI：统一数据指标文字

### ISSUE THREAD

**Issue by Gongyufei** [zerocoolys/sshuiyan#94]
![image](https://cloud.githubusercontent.com/assets/12438962/7829976/4522e69c-047a-11e5-9b53-594190ad39e0.png)
![image](https://cloud.githubusercontent.com/assets/12438962/7829980/550cbfce-047a-11e5-8ab1-a1959e5da89e.png)

**Comment by zerocoolys** [comment]
![image](https://cloud.githubusercontent.com/assets/2757581/7840077/432a82fc-04c8-11e5-9c81-04f94a02660f.png)
